### ISSUE TITLE
Improved 'opening hours' support

### ISSUE THREAD

**Issue by rutgerplantenga** [ocpi/ocpi#1]
Request to add a structured approach to exchanging opening hours (strictly formatted time notations, possibly taking into account time zones?).

As an EV-driver I only want to see chargepoints around me that are actually available, both in terms of chargepoint status as well as in terms of physical accessibility. OCPI should support the exchange of opening hours in such a way (no free text) that apps and such could start to support this.

**Comment by EV-Box** [comment]
I understood this was in plain text to allow additional information, such as 'Only for visiting customers' and the iCalendar RRule would be able to display a restricted format.

Nonetheless, I'm in favor for removing the display text as we only see this field being used.

**Comment by RobertdeLeeuw-IHomer** [comment]
was fixed in 2.0
