### ISSUE TITLE
Add a range of custom status codes

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#100]
For custom implementations and modules, further status codes are needed. Proposal is to add a reserved range of 100 status codes per group.
### Example:

Reserved Range `X9XX`
- `19xx`   Custom cuccess codes
- `29xx`   Custom Client errors
- `39xx`   Custom Server errors

**Comment by RobertdeLeeuw-IHomer** [comment]
If we add this, we also need to explain that they are not unique, that when you receive a custom  status code they probably mean something else then you have defined yourself

**Comment by poohsen** [comment]
We have not derived much value from the codes in our integration efforts. In our own implementation we try our best to formulate a helpful error message

We would have to put a lot of thought into formulating the exact meaning of codes for all modules. And I can't say if there's enough value in having them to justify the effort.
