### ISSUE TITLE
link header (pagination) written in small case in table but capital case in example

### ISSUE THREAD

**Issue by poohsen** [ocpi/ocpi#102]
just realized we wrote 'link' in the table in https://github.com/ocpi/ocpi/blob/master/transport_and_format.md#paginated-response

According to the RFC, which we seem to be using when looking at the _value_ of the header, it should be a capital 'L': https://tools.ietf.org/html/rfc5988#section-5
We're doing it right in the example so we should correct the table IMO.

**Comment by RobertdeLeeuw-IHomer** [comment]
Sharp!! 
Should we fix bugs like this in git? 2.1 is tagged.

**Comment by poohsen** [comment]
I don't know why I didn't simply correct it upon seeing it but I'll do it now
