### ISSUE TITLE
String size of (u)id's is not enough

### ISSUE THREAD

**Issue by bdenbiesen** [ocpi/ocpi#104]
We, at EVBox(@rturtoi), are currently running into the fact that the size of (u)id 's is not enough.
We would like to increase the size from 15 to a minimal of 36 characters, so that Guids can used to uniquely identify an object (Guid: "9DE5B68F-F40A-E611-966D-001B21AF8474").

Example:
For CDR's and Sessions, we use Guids to uniquely identify a transaction.
For EVSE, we need a String that can contain "EVB-P1224001*B1244073" (string of 21 chars).

I created a pull request #103 for this change.

**Comment by piotrpl** [comment]
@bdenbiesen right now the id's are 36 characters and this seems to be solving the problem. Can this be closed as "fixed"?

**Comment by bdenbiesen** [comment]
@piotrpl  It is currently in the RC of 2.1.1 , but yes after 2.1.1 is final, this can be closed
