### ISSUE TITLE
Session reference in the CDR

### ISSUE THREAD

**Issue by Gingonic** [ocpi/ocpi#105]
Hi there,

as far as I can see there is no reference to the session in the CDR object.
Up to the moment the CDR is sent, the eMSP only works with the session resource that will be used for all comunication with the customer.
So it would make sense to update the session data with the CDR information as it those who are billing relevant and display those to the customer.

Even if the session was used for invoicing the customer, the eMSP still might want to crosscheck the CDR against the sessions to find potential inconsistencies when the CPO invoice comes in.

Except some matching on based on auth_id and charging time,  I see only one way to achieve this right now: declare that CDR ID must be equal to the session ID. But this is not clearly stated in OCPI and might lead to problems in the central systems.

Did I oversee something here?

**Comment by RobertdeLeeuw-IHomer** [comment]
The Session and CDR can easily be matched based on auth_id and start_date_time. I personally do see a reason to add a reference to the session.

**Comment by ahzf** [comment]
There is no guarantee that the auth_id is not used by multiple poeple at the same time. And timestamps are very often a cause of problems in distributed systems. Therefore this is not really a robust way to match a session and/or cdr.

**Comment by RobertdeLeeuw-IHomer** [comment]
True, there might be multiple RFID cards for the same contract. But, the timestamps in the session and CDR should be the same, they come from the same Charge Point.

**Comment by Gingonic** [comment]
May be I wasn't clear enough. The matching between session and CDR is already a bit fuzzy, but yes you could guess it and hope that the CPO does implement his session module the same way he does CDRs (which by experience is not always the case, as the CDR handling are mostly older system).

More challenging : How do we keep a remote start request and a session start togehter? 
For us it is quite important as we lead the customer from his remote start request  to the session view (in the UI), were he will see a approximate the state of the session, price, consumption etc...

I think the problem comes from the fact that fro the CPO the sesison only starts when the EVSE says so but for the EMP it actually starts when the customer hits the "start" button.

I think there should be a proposed way in OCPI to keep remote actions, sessions and finaly CDRs all together as they all are part of one customer journey.

**Comment by RobertdeLeeuw-IHomer** [comment]
I agree that it would make things easier to implement if we would have 1 reference that binds all this together. I think we have to discuss this for OCPI 2.2. If you look at OCPP 1.6, it also has no support to bind the remote start to a started/stopped transaction. But I known there are some discussion going on in the OCPP community to look into this as well. If both OCPI and OCPP would support this in the future then it can be very usefull.

**Comment by Mathieu-Castets** [comment]
This is also a big issue for us. Indeed, in our system, thanks to remote commands, we allow to start two sessions at the same start_date_time (considering second is the most precise time unit).

It would be so much easier to have a reference to bind session and cdr together. We hope it will be discussed for the next version.

**Comment by bramus** [comment]
+1 on including a `session_id` in the CDR.

Additionally I also see some opportunity to remove excessive/redundant data – such as the location – from the CDR format when having a `session_id`.

**Comment by RobertdeLeeuw-IHomer** [comment]
@bramus The reason to have all that data is the CDR, and no reference... The data inside the references can be changed. And a CDR can never be changed. So If a CDR is received, the MSP can use it for billing. When we would use a reference to a Location, it will happen that the Tariff changes for that location. That way you could never check if the CDR was correct after a change in the Tariff.

**Comment by RobertdeLeeuw-IHomer** [comment]
Added: https://github.com/ocpi/ocpi/commit/c25c4da7f0ced0db45f1f5af12e7ab862117173c
