### ISSUE TITLE
Define a tariff free of charge

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#109]
Currently it is not clear how to define a tariff "free of charge". possible interpretations are:
- **Do not set a tariff_id in the connector object.** This could also be understood as _tariff unknown_.
- **Set the price to 0.** This can be in multiple ways for the different element types.
#### Proposal:

A free tariff is one with only one `TariffElement` with only one `PriceComponent` of type `FLAT` and a price and step_size of 0:

```
{
    "id": "12",
    "currency": "EUR",
    "elements": [{
        "price_components": [{
            "type": "FLAT",
            "price": "0.00",
            "step_size": 0
        }]
    }]
}
```

**Comment by RobertdeLeeuw-IHomer** [comment]
Good idea to add this, not only as an example, but as a rule how it should be done.

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed
