### ISSUE TITLE
Allow to limit the maximum session price for a tariff

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#110]
In mod_tariffs, section _4.5 TariffRestrictions class_, a element limiting the maximum cost is missing. I found a TNM tariff, reading "2.90 per hour, maximum 27€". This is currently only to be covered by limiting the total hours. However, when tariffs consist of multiple elements, the calculation is tricky.
#### Proposal:

Add properties `min_session_price` and `max_session_price` to the [`TariffRestrictions`](https://github.com/ocpi/ocpi/blob/master/mod_tariffs.md#45-tariffrestrictions-class) class.

**Comment by KevBelisle** [comment]
I do not think TariffRestrictions is the correct place to add a min/max_session_price.

Tariff restrictions are used to determine which Tariff Element should be used to calculate the price:
> When the list of elements contains more then 1 element, than the first tariff in the list with matching restrictions will be used.

I believe min/max_session_price parameters could be added either to the `TariffElement` class or directly to the `Tariff` class.

.

I could see it added as a `price_limits` property, containing a list of `PriceLimit`s.

`PriceLimit` being a small class containing 2 properties :
- type: MIN_PRICE or MAX_PRICE
- price: number

**Comment by RobertdeLeeuw-IHomer** [comment]
I agree that adding it as optional to the `Tariff` class is the best option.
I already added `max_price`, I will also add a `min_price`
