### ISSUE TITLE
Default step_size should get renamed to 'unit of step_size'

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#111]
In [4.4 TariffDimensionType enum](https://github.com/ocpi/ocpi/blob/master/mod_tariffs.md#44-tariffdimensiontype-enum) of mod_tariffs, the default step size per dimension is given. This is misleading as the property `step_size` of _PriceComponent_ is mandatory. What is meant is the unit or multiplier of the `step_size` value.

**Comment by RobertdeLeeuw-IHomer** [comment]
I have add some description and changed it to "step_size multiplier" We might introduce something that has a different multiplier then 1 second, but for example "25 apples" We cant do that with 'unit of step_size'  I hope it is clear now.
