### ISSUE TITLE
Number fields kwh & total_cost still represented as Strings in samples

### ISSUE THREAD

**Issue by markvandenbergh** [ocpi/ocpi#116]
Numbers are still represented as Strings in samples.

https://github.com/ocpi/ocpi/blob/master/mod_sessions.md#223-patch-method (total_cost)
https://github.com/ocpi/ocpi/blob/master/mod_sessions.md#simple-session-example-of-a-just-starting-session (kwh & total_cost)
https://github.com/ocpi/ocpi/blob/master/mod_sessions.md#simple-session-example-of-a-short-finished-session (kwh & total_cost)

**Comment by RobertdeLeeuw-IHomer** [comment]
fixed
