### ISSUE TITLE
Link to "Realtime Authorization" broken in mod_tokens

### ISSUE THREAD

**Issue by apheleia** [ocpi/ocpi#118]
Given that I am on the [mod_tokens](https://github.com/ocpi/ocpi/blob/master/mod_tokens.md) page,
When I click on any of the [realtime authorization](https://github.com/ocpi/ocpi/blob/master/13-real-time-authorization) links at the very bottom,
Then I should get to the documentation about realtime authorization,
But instead I get a `HTTP 404 Not found`.

**Comment by poohsen** [comment]
fixed. thx.
