### ISSUE TITLE
use of X-Total for pagination in OCPI

### ISSUE THREAD

**Issue by poohsen** [ocpi/ocpi#119]
We specified the X-Total header to give the total number of objects on the server side.

I wonder if anybody actually uses this in their implementation. It makes sense for UIs but not for M2M communication like we have in OCPI. I'd propose to drop that header as I don't see it's value.
Any thoughts?

**Comment by RobertdeLeeuw-IHomer** [comment]
I could envision a solution where you ask for the last X (10?) objects on the CDR module. When this module returns the same amount of objects in the X-Total header as allready known in the client... you know there are now CDR objects missing.... but I understand why you are indoubt about the usefulness of the "X-Total" header. 
I will not take this issue into account for 2.1.1 if you don't mind.

**Comment by RobertdeLeeuw-IHomer** [comment]
I read and edited the pagination part. I think you will need to check if the X-Total changed while crawling over the pages. When a 'date_to' filter is used you could run into concurrency issues. A client implemention needs to take that into account.
