### ISSUE TITLE
"OCPI messages should not be queued" could be elaborated on

### ISSUE THREAD

**Issue by mountain65** [ocpi/ocpi#121]
If I understand this short sentence right, it means that I SHOULD NOT (as an eMSP) use some sort of retry-mechanism when pushing information to a CPO. We were planning to use a Message Queue to retry sending messages in case of a communication failure, creating some guaranteed-delivery mechanism.
If I understand this remark well, it says that we should not do such a thing. Whenever there is a server that has been off-line for a while, that server itself is responsible to retreive any information it might have missed during its absence.

A little more text in this paragraph to explain the exact meaning of "queued" would be welcome.

**Comment by mountain65** [comment]
Maybe if the next sentence in the paragraph "When the connection is re-established, it is up to the client of a connection to GET the current status from to server to get back in-sync" would read something like:

When the connection is re-established, it is up to the **target**-server of a connection to GET the current status from the **source**-server to get back in-sync.

**Comment by RobertdeLeeuw-IHomer** [comment]
fixed, added some more explenation.
