### ISSUE TITLE
postal_code should not be mandatory for Location

### ISSUE THREAD

**Issue by kiequoo** [ocpi/ocpi#125]
For a Location all address fields are mandatory (address, city, postal_code and country), however not all countries use postal codes, therefore it would be better if this field at least is optional.  

You could also argue that address_1 and address_2 (with address_2 being optional) would also be more flexible than address and city, at not all Locations are located in (or even near) a city

**Comment by goelectricstations** [comment]
I agree

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed, even countries with postal_codes, sometimes don't have postal_codes for location at highways.
Also added `state`
I looked into adding: `address2`, but everything I found about `address2` does not seem to be needed for Charge Points.
