### ISSUE TITLE
Token authorization URL should contain token type

### ISSUE THREAD

**Issue by kiequoo** [ocpi/ocpi#128]
For the token object (https://github.com/ocpi/ocpi/blob/master/mod_tokens.md#32-token-object), it says 

> The combination of uid and type should be unique for every token.

However, when the CPO wants to authorize a token, the example URL given is

`/ocpi/emsp/2.0/tokens/{token_uid}/authorize`

This does not include the token type, and as the token_uid is not unique by itself, how to find the correct token if there were two with same uid but different types?  Also isn't `uid` a misnomer in this case, if it's only unique in combination with the type?

**Comment by RobertdeLeeuw-IHomer** [comment]
Yes, but other solutions might also work.
Maybe add a ID which is really the ID of the Token, like a database ID, and rename the UID to hidden_id. but that does not work for Tokens that are not RFID.
Token might need some rework, also see: #131

**Comment by RobertdeLeeuw-IHomer** [comment]
Already fixed in 2.1.1:

Now:  `/ocpi/emsp/2.0/tokens/{token_uid}/authorize?{type=token_type}`

**Comment by ahzf** [comment]
This seems to be a big anti pattern to me.

There is even the TokenType QueryParameter on the HTTP PUT URL, which is in my eyes completly redundant.

And does an CPO know if he should query a token multiple times for multiple token types? This idea seems to be very unrealistic to me.

An EMP has to ensure, that a token is unique. Within roaming you can not be sure, that it is unique, and you can receive multiple answers and have to deal with all those situations anyway.

So please remove this QueryParameter.

**Comment by RobertdeLeeuw-IHomer** [comment]
OCPI States: "The combination of uid and type should be unique for every token within the eMSP’s system."
So as long as OCPI does not require the Token.uid to be unique on itself, we need the Token.type to identify exactly which Token we want to perform an action on. 

I think what you want to propose: Replace requirement: "The combination of uid and type should be unique for every token within the eMSP’s system." with something like: "The Token.uid SHALL be unique for every Token winthin the eMSP's system."
