### ISSUE TITLE
Tariff & CDR clarification request

### ISSUE THREAD

**Issue by anthonyjmartinez** [ocpi/ocpi#134]
Within the **Location Module**, and specifically the *Connector Object*, there appears to be a single possible **tariff_id** at any given time. However, the **CDR Module** supports a *list* of tariffs which creates what seems to be a significant conflict. Are there use case descriptions available that might illustrate what the intent is in allowing multiple tariffs to apply in a given CDR?

As discussed in recent ROEV meetings aimed towards facilitating greater adoption of OCPI 2.1.1 the model as defined leaves a few questions:
- How does the Tariff Module address demand response pricing?
- There must be active driver opt-in to any tariff change beyond what was explicitly approved by the user at the onset of a session, it's unclear how this fits with OCPI
- By what means are CDR calculations able to be verified by the receiving party?

**Comment by rudolphfroger** [comment]
I would also like to know why a CDR can have multiple tariff id's while a tariff already has the option for multiple Tariff elements. What's the use case?

**Comment by RobertdeLeeuw-IHomer** [comment]
@rudolphfroger 
For OCPI 2.1.1 it is less obvious. Only use case is (something I would not recommend) When switching to a new tariff during charging. The only valid reason to do this, in my view: When the tariff changes starting of a new month/year. Then you might change the tariff during a session that started before the change and ends after this change. But then it has to be clear to the driver before starting the session that the tariff will change in the near future, possibly during his new session.

For OCPI 2.2 the use case is more clear: a driver might switch Charging Preferences and different Charging Preferences might have different tariffs.
