### ISSUE TITLE
CDR Records: `total_usage` or `total_energy` and `total_time`?

### ISSUE THREAD

**Issue by bramus** [ocpi/ocpi#137]
Hi,

The [CDR Object description](https://github.com/ocpi/ocpi/blob/master/mod_cdrs.md#31-cdr-object) speaks of the fields `total_cost`, `total_energy` and `total_time`:

- `total_cost`: Total cost of this transaction.
- `total_energy`: Total energy charged, in kWh.
- `total_time`: Total time charging, in hours.

The [CDR Example following that definition](https://github.com/ocpi/ocpi/blob/master/mod_cdrs.md#example-of-a-cdr) however has no mention of the fields `total_energy` nor `total_time`, but sports a field `total_usage` with two objects containing the total time and energy:

```
	"total_cost": "4,00",
	"total_usage": [{
		"type": "TIME",
		"volume": "1.973"
	}, {
		"type": "ENERGY",
		"volume": "15.342"
	}]
```

Hereby I'm wondering which of the two is correct: is the description correct, or is the example correct?

Regards,
Bramus.

**Comment by RobertdeLeeuw-IHomer** [comment]
Good find.
The example is not up to date. The field was changed between 2.0 en 2.1.
See change log: https://github.com/ocpi/ocpi/blob/2.1-bugfixes/changelog.md#changes-between-ocpi-20-and-21

I will update the example.

**Comment by RobertdeLeeuw-IHomer** [comment]
fixed: https://github.com/ocpi/ocpi/commit/aea1adbaf555e8c9d3bd272ff09f8d3c9f996c1e
