### ISSUE TITLE
Token from Authorization header and corresponding status code

### ISSUE THREAD

**Issue by Mathieu-Castets** [ocpi/ocpi#148]
Hi, 

Working on `2.1.1` implementation, I could not find in the documentation any information about what the server must respond when the token from the `Authorization` header isn't valid or doesn't correspond to an existing token.

I'd have thought to return a HTTP `401` error but from the documentation:

> If a request is syntactically valid JSON and addresses an existing resource, no HTTP error should be returned. Those requests are supposed to have reached the OCPI layer. 

So which OCPI status code should be used? I'd create a dedicated 2xxx client error such as "Authentication failed".

**Comment by RobertdeLeeuw-IHomer** [comment]
Hi Mathieu,

Do you mean: What should the response be to a request from a client that does not contain the valid credentials token in the authorization header? 
You are right, there is nothing written about this.
I would say: If authorization of the request files, the server should return a HTTP 403 - Forbidden 
(Authorization was found, but not valid)

This is inline with a remark also on page 16: "As is customary for RESTful APIs:
if the resource does NOT exist, the server should return a HTTP 404 - Not Found."

**Comment by Mathieu-Castets** [comment]
Hi Robert, 

> What should the response be to a request from a client that does not contain the valid credentials token in the authorization header?

Yes exactly what I mean. So I will send a `403 - Forbidden`. This bit, in the documentation, was misleading "If a request is syntactically valid JSON and addresses an existing resource, no HTTP error should be returned."

And what about if **no** `Authorization header` was found ? `401 - Unauthorized` seems suitable here.

Thanks for your input

**Comment by RobertdeLeeuw-IHomer** [comment]
Hi Mathieu,

I did a bit of reading about the difference about 401 and 403 (don't know them by head myself)
You are right, I think 401 is better. User is unauthorized, providing a different authorization will make it work.
Use: 401 - Unauthorized

403 - Forbidden is more for use when nothing will help this, maybe there is an IP whitelist or something like that.

Would you like to create a pull-request for this?

**Comment by poohsen** [comment]
cf. https://stackoverflow.com/a/6937030/1823536

**Comment by RobertdeLeeuw-IHomer** [comment]
https://stackoverflow.com/a/3297081

So it is a bit of a discussion when to use 403 or 401....

**Comment by RobertdeLeeuw-IHomer** [comment]
Fix in 2.1.1 bugfix branch, will be pulled to develop, so will also end up in 2.2
