### ISSUE TITLE
Profile Request Add profile_type to request message

### ISSUE THREAD

**Issue by buurenmi** [ocpi/ocpi#15]
Profile Request Changes
The profile request message will be extended with an extra Attribute:
• Profile_type
The attribute will indicate the kind of profile that is send in the request. The kind of profile will be used in determining the support of the profile on the selected Charge Point.

Accept or deny Profile
Not all charge points will accepted delayed charging. The CSO will determine where delayed charging is supported. This will be send to the eMSP in the find result as a capability.
If the charge point doesn’t support profile_type 
1.  the CSO will send NDR event profile_denied.
2.  The CSO will  leaf the set tarifftype in the CDR to the default value
If the charge point does support profile_type
1.  The CSO will send NDR event Profile_accepted
2.  The CSO will change the TariffType in the CDR to the tarifftype found in the request.

Revoke Profile
If the Driver wants to cancel (charge me now) the selected profile a profile request is send with: 
profile_type = normal
tariff_type = null or default tariff_type of the Charge Point involved
if the tarrif_type is null The CSO will use its default settings to determine the tariff_type
If the CSO is not the CSA the tariff type will be string.empty or null in the CDR.
The CSA will determine the correct tariff_type and calculate the wholesale costs.

Billing
In order to set the correct billing information in the charge detail request it is necessary to know the charging profile type used during the charging session. In the OCPi spec it is possible to send a tariff_type connected with the charging. 
The tariff_type used is an agreement between CSO and eMSP
Tariff_type is not a centralized set used by all.
For this project we will use D1 as the tariff_type for delayed charging.

Rules 
• profile_type must be capability of the charge point involved.
• capability is not a set enum but will be exposed by CSO.
• Capabilities supported are agreed between CSO and eMSP
• CSO and eMSP negotiate the tarriff_type used for an specific profile_type 
• The eMSP will determine the correct tariff_type for the profile_type
• Find results will not override the tarifftype of a post based on the received pricing scheme

**Comment by RobertdeLeeuw-IHomer** [comment]
OCPI 2.2 adds charging preferences to Token objects, and the ability to set a charging preferences for a driver on a session.
