### ISSUE TITLE
separate Token type for the commands module

### ISSUE THREAD

**Issue by poohsen** [ocpi/ocpi#153]
we say that StartSession should contain a Token object, but that object's type definition contains a `uid` field that should be supplied by the CPO. Either we can just use the token.uid, referencing a token that has previously been shared with the CPO, or we should create a `CommandToken` type with the essential information needed to start a session. 

Can a party that implemented the commands module already comment on this and share their experience?

**Comment by rolandschroth** [comment]
We are currently implementing this and also had our problems with the specification requirement for a fully qualified `Token` object as defined for the Tokens module.

Our development point of view at the moment is: 
As a CPO we do not necessarily need to know (or store) the provided `Token` (by the means of the specification) at all. Per definition (registration process) we shall trust the EMSP to be allowed to issue `StartSession` commands with any `auth_id`. Therefore we have defined that the `token` only needs to contain the `auth_id` field and all others are optional (for now). 
As there is no requirement to store/update or handle the `Token` from `StartSession` in any specific way, we decided to use it only as far as it is needed in context of the charging session. Therefore we consider a provided `auth_id` as sufficient here.

We would appreciate a specification that better suits the `Commands` use-case. Having a `CommandToken` seems like a reasonable way to go here.

**Comment by RobertdeLeeuw-IHomer** [comment]
I'm trying to understand this issue, I'm working on OCPI 2.2.
Somethings have already changed in OCPI 2.2:
- CDR now contains the full Token object, not just `auth_id`.
- Token now has type `APP_USER`

I see 2 scenarios for using `StartSession`:
- Either the RFID based Token of a user is used. This means the user can also use the RFID to stop the session. Does the CPO need to have received this Token from the Tokens Module? Before the `StartSession`? I don't see why that is needed. 
- An APP is used, no connection the an RFID of a user. So a Token for an APP_USER is generated for the APP. The this `APP_USER` Token is used in the `StartSession`

Both scenario's:
- The CPO needs to store the Token and put the same object in the CDR.
- If the Charge Point does an Authorize request, and the Token has: Whitelist: `ALWAYS`, the CPO knows this Token from the `StartSession`.
- The `Token.uid` contains either a generated ID or the RFID Hidden ID, depending on the scenario.

"field that should be supplied by the CPO"? No, that is not what the specification says.

**Comment by RobertdeLeeuw-IHomer** [comment]
@poohsen @rolandschroth With all the changes currently already made in OCPI 2.2 (see development branch) is this still an issue?
