### ISSUE TITLE
EnvironmentalImpact.amount has 4 decimals while the example has 5

### ISSUE THREAD

**Issue by simonphilips** [ocpi/ocpi#157]
[EnvironmentalImpact.amount](https://github.com/ocpi/ocpi/blob/master/mod_locations.md#48-environmentalimpact-class
) has no decimals specified, which means it uses the default (4). However, the example at https://github.com/ocpi/ocpi/blob/master/mod_locations.md#complete uses 5 decimals for NUCLEAR_WASTE:

> { "source": "NUCLEAR_WASTE",  "amount": 0.00006, },

**Comment by poohsen** [comment]
rule of thumb: if the text/tables don't match the examples, it's the examples that are wrong.
Can you make a PR pls?

**Comment by RobertdeLeeuw-IHomer** [comment]
I hope I can find the time to generate the examples from some java project, hope that fixes a lot of issues in the future, but all depends on amount of time available to work on the document. I want to add more examples, they really help more then the tables.

This example is fixed now.
