### ISSUE TITLE
Ability to exchange origin of chargepoint's electricity-mix via OCPI

### ISSUE THREAD

**Issue by rutgerplantenga** [ocpi/ocpi#16]
EV-drivers are often interested in the origin (background/sources) of the electricity provided by a chargepoint. 

The request is therefore to enable exchange of this type of information via OCPI in a way that is internationally applicable (ie. if industry classifications would be used then those should be internationally acknowledged classifications).   

This would allow MSP's to communicate to their customers what the source is (solar, biomass, hydro-power, etc).

**Comment by rutgerplantenga** [comment]
Marking as a duplicate: https://github.com/ocpi/ocpi/issues/33 is more detailed.

**Comment by simonschllng** [comment]
uplicate of #33
