### ISSUE TITLE
CDR attribute 'tariffs' (list) should be 'tariff' (one)

### ISSUE THREAD

**Issue by fbuve** [ocpi/ocpi#165]
A CDR contains an attribute 'tariffs' which supposedly can hold a list of tariffs, but that cannot be correct. A charge point connector can only have 1 tariff (with multiple tariff elements). Therefore, the attribute cdr.tariffs (*) should be changed to cdr.tariff (0..1) which points to the tariff used to calculate the cost of the session.

**Comment by RobertdeLeeuw-IHomer** [comment]
What if the tariff is changed during charging? For example: until end of 2018 tariff 1 is valid, from 1-1-2019 tariff 2 comes in use. With allowing 2 tariff in 1 CDR, this is possible. 

Or should OCPI disallow the changing of a tariff during a charging session?

**Comment by fbuve** [comment]
Legally it is in most countries not allowed to change the tariff during a session, unless you communicated also the changed tariffs before start of the session (via display or app).  As far as I know, it is customary to keep the tariff that was valid at start of the session.
Note, that when having 2 tariffs in a CDR, that you need to have validity dates on the tariffs, which we do not have know.

**Comment by RobertdeLeeuw-IHomer** [comment]
If we introduce: https://github.com/ocpi/ocpi/issues/168 then it would be possible.

**Comment by RobertdeLeeuw-IHomer** [comment]
With the introduction of Charging Preferences, a Driver can change Smart Charging Profile from "Green" to "Fast", so both tariffs are needed. Which reminds me:  I need to add the event somehow to a CDR...
