### ISSUE TITLE
Add maximum price and direct payment mark-up to tariff structure

### ISSUE THREAD

**Issue by fbuve** [ocpi/ocpi#167]
I need a way to represent the following (real live) conditions in OCPI tariffs:
    1. Specify a mark-up for direct payment sessions: e.g. `if payment_method == 'visa' then add 0.25 euro`.
    2. Limit the maximum price to a certain maximum: e.g. `max_price == 50 euro` to specify that no matter how long you connect, you will never pay more than 50 euro.

**Comment by RobertdeLeeuw-IHomer** [comment]
I added max_price.

Dont known how to add something like: `if payment_method == 'visa' then add 0.25 euro` without making everything much more complex then it already is. For now I would add the 0.25 euro to the start_fee. And add to the `tariff_alt_text` a description, explaining that a driver gets a discount if he uses a cheaper payment method: debet card?
