### ISSUE TITLE
Why is CDR endpoint different from others?

### ISSUE THREAD

**Issue by jmace35** [ocpi/ocpi#169]
_CDRs_ and _Sessions_ are owned by the CPO back-end system. So on eMSP interface, the _Sessions_ endpoints need to contain the required extra fields: {party_id} and {country_code}. 

Why is this not the case for endpoints of _CDRs_ eMSP interface ?

**Comment by KevBelisle** [comment]
Might this be because CDRs cannot be modified after their creation?

**Comment by RobertdeLeeuw-IHomer** [comment]
CDRs are used for billing purposes, so it would not be a good idea if a CDR could be modified. For the next version of OCPI we will look into revoking a CDR, when the CPO finds something wrong with a CDR it has send we need a way of telling the MSP that the old one is replaced by a newer one. Without deleting the first one. I'm not a financial specialist... but it has to be something like that.
