### ISSUE TITLE
AuthMethod is missing a value for StartSession command

### ISSUE THREAD

**Issue by rolandschroth** [ocpi/ocpi#170]
Hi everyone,

I think that `AuthMethod` enum is missing a value for the case of a session start via command `StartSession`.
The currently available values do not cover that scenario and/or the current description is not clear:
> `AUTH_REQUEST` Authentication request from the eMSP
> `WHITELIST` Whitelist used to authenticate, no request done to the eMSP

Reason: In case of a `StartSession` command, no authentication request will be made from or towards the EMSP as the `Token` to be used is already provided within the request. Neither will it be authenticated via Whitelist.

I would therefore propose to
- Modify the description of `AUTH_REQUEST` to "Authentication request towards the eMSP" because a CPO either asks the EMSP for authentication (not the opposite way) or uses the whitelist.
- Add a new value `COMMAND` to the enum to also cover the StartSession command use case.

I would appreciate other opinions on this.

Best regards, Roland

**Comment by RobertdeLeeuw-IHomer** [comment]
It is not that simple. 
Yes, we could add:  `COMMAND`, that sound logical.
But, it is not true that there will never be an authorize request to the CPO from the Charge Point for a Remote Start. This depends on the OCPP version, and the configuration of a Charge Point. It can happen. Then the correct value will still be: `AUTH_REQUEST` or `WHITELIST`. 

Question is: does a CPO know that the Charge Point has or has not done an Authorize request over OCPP? The authorize request is not bound to a session. It just authorizes the RFID to be used. Not for a specific transaction. 

Even with the current OCPI 2.1.1, if a Token has the value: `ALLOWED_OFFLINE`. How does the CPO know if a real-time-authorization was done for a specific transaction? Authorization is not connected to a transaction.

**Comment by RobertdeLeeuw-IHomer** [comment]
During the meeting in Strasbourgh it was decided that after a StartSession no real-time authorization is allowed, which takes away my concerns. 
I have added Command to the AuthMethod
