### ISSUE TITLE
Additional fields in CommandResponse

### ISSUE THREAD

**Issue by rolandschroth** [ocpi/ocpi#171]
Hi everyone,

I would like to discuss adding further fields to the `CommandResponse` object.
Referring to #99 where the case is discussed, how to immediately respond to a command, I think there should also be a more convenient way of passing information in the CommandResponse object which is no HTTP response and therefore section _3.1.5 Response format_ of the specification does not apply.

Following the example of #99 and given the case that the CPO does not immediately reject the command but accepts it (e.g. because the known EVSE state is inaccurate), a command to the EVSE will be issued. If then in turn the EVSE rejects the command, maybe with a qualified error message, or is not reachable there is no way to tell the original caller, what actually went wrong. So the potentially more qualified error reason gets lost whereas rejecting right away (maybe only based on assumptions about the state) allows transporting such information.

## Proposal for discussion
Therefore I would like to propose adding an optional field `reason` of new type `CommandResponseReason` to the `CommandResponse` object.

**CommandResponseReason** object

Property | Type | Card. | Description
------------ | ------------- | ------------ | -------------
type | CommandReasonType | 1 | The type of reason, why the command could not be executed in the desired way.
message | DisplayText | ? | Human-readable description of the reason (if one can be provided).

**CommandReasonType** enum

Value | Description
------ | ------
COMMUNICATION_ERROR | Communication with the EVSE failed.
EVSE_INOPERATIVE | EVSE is currently inoperative.
EVSE_OCCUPIED | EVSE is currently occupied.
EVSE_NO_AUTH | EVSE currently does not accept authentication commands (e.g. it is currently set to no-authentication / free of charge mode)
...

I would like to hear from others, what you think about this and will be happy for any additions or even better proposals.

Best regards and thanks in advance for any comments and input on this.
Roland

**Comment by rolandschroth** [comment]
I think, #154 points into similar direction

**Comment by RobertdeLeeuw-IHomer** [comment]
I have added the `message` field, really useful.
Good idea to make it DisplayText, I made Card. '*' so the message can be provided in more then one language.
