### ISSUE TITLE
DateTime type allows too large format possibilities

### ISSUE THREAD

**Issue by jmace35** [ocpi/ocpi#173]
OCPI specifies a DateTime type which must respect the ISO 8601 standard. But ISO 8601 standard allows a lot of differents patterns (with or without hour, minute, seconds, decimal fraction of a seconds, time zone, ...) and causes compatibility problem.

Could OCPI impose a more precise format like RFC 3339 or W3C DateTime?

RFC 3339 : https://www.ietf.org/rfc/rfc3339.txt
W3C DateTime : https://www.w3.org/TR/NOTE-datetime

**Comment by RobertdeLeeuw-IHomer** [comment]
This is the first time I hear about issues with the DateTime.
For most: https://github.com/ocpi/ocpi/blob/master/types.md#12-datetime-type
Is enough. But I will put it on the list for a next version to try to specify this more strict, inline with how it is now used, so no new format.

**Comment by RobertdeLeeuw-IHomer** [comment]
Added some text to explain that only the given examples are allowed. This means there are no different patterns allowed.

**Comment by RobertdeLeeuw-IHomer** [comment]
For OCPI 2.2 this is now changed.
