### ISSUE TITLE
How do step_sizes work when we switch from one TariffElement to another?

### ISSUE THREAD

**Issue by KevBelisle** [ocpi/ocpi#175]
Here's the scenario:

An EVSE's Tariff has the following TariffElements:
```javascript
"elements": [{
		"price_components": [{
			"type": "TIME",
			"price": 1.00,
			"step_size": 900 //15min
		}, {
			"type": "PARKING_TIME",
			"price": 1.00,
			"step_size": 900 //15min
		}]
	}]
```

An EV driver plugs in, charges for 2 min (TIME), stops charging but stays plugged in for 2 min (PARKING TIME), and then leaves. Total session time = 4min.

Will the driver be charged for a full step of each price component (900s of TIME and 300s of PARKING TIME) ?

This would work out to a total of 30 "billable" minutes and $2 for a 4min session.

**Comment by RobertdeLeeuw-IHomer** [comment]
Very good point. I dont known. I guess we should have some agreement on this.

Your example: Would be:
- 15 billable minutes charging time: 1 euro p/hour = 0.25 euro
- 15 billable minutes parking time: 1 euro p/hour =  0.25 euro
0.50 euro total for this 4 minute session

My first guess: When switching from one TariffElement to another, the stepsize should still be taken into account when switching to a different kind of price_component. From TIME to PARKING_TIME.
But the step_size should not be taken into account when switching from one TIME price_component to another price_component of the same type. So if charging is 1.20 euro p/hour before 17:00, but 2.40 euro p/hour after 17:00..

Different example, based on your example, but then with the difference in pricing before and after 17:00":
An EV driver plugs in at 16:55, charges for 10 min (TIME), stops charging but stays plugged in for 2 min (PARKING TIME), and then leaves. Total session time = 12min.
Would be:
- 5 billable minutes charging time: 1.20 euro p/hour = 0.10 euro
- 10 billable minutes charging time: 2.40 euro (minimum is 15 minutes total?) = 0.40 euro
- 15 billable minutes parking time: 1 euro p/hour = 0.25 euro
0.75 euro total for this session.

**Comment by RobertdeLeeuw-IHomer** [comment]
Added example and explanation for this in commit: 94d129312bf2137f87f91df9ea92e773d3a215bb
