### ISSUE TITLE
Add more info in mod_session

### ISSUE THREAD

**Issue by goelectricstations** [ocpi/ocpi#180]
because OCPP already have this data and as MSP we need. 
Please, add the follow info as optional in mod_sessions.

energyActiveImport
energyActiveExport
powerActiveImport
powerActiveExport
SoC

Thank you,

**Comment by RobertdeLeeuw-IHomer** [comment]
@goelectricstations: Is this also needed for billing? Or is this only for information that might be needed for Smart Charging?

**Comment by goelectricstations** [comment]
Hi Robert,

thanks for asking.

Only energyActive.

**Comment by RobertdeLeeuw-IHomer** [comment]
Do you need the other information for Smart Charging?
If so, it is input for a Smart Charging Module, which is on the list for a next version

**Comment by goelectricstations** [comment]
Only as info for the customer, not for Smart Charging.

**Comment by goelectricstations** [comment]
But energyActiveExport can be use i the future for billing

**Comment by RobertdeLeeuw-IHomer** [comment]
Looked into this. Currently the CdrDimension class. We would need to add values to CdrDimensionType. But because it is from CDR, these new values also become available to CDR.. Which would result in values that have no meaning because they dont have any billing purpose. 

Only solution I see, create a SessionDimension class, and add the values to SessionDimensionType... more work for everybody implementing OCPI. So but hesitated to add this.

**Comment by goelectricstations** [comment]
Those values should be not mandatory, there are so many field on the OCPI that have not meaning for me, but I do not ask to remove, I implemented.

**Comment by RobertdeLeeuw-IHomer** [comment]
@goelectricstations I propose to do the following:
Add new values to CdrDimensionType, but mark them as not allowed for CDRs, this to prevent getting question from MSPs that receive the values, but dont know what to do with them.
Then see what kind of feedback we get from OCPI 2.2 RC2. 

SoC is clear to me.

Questions: 
- energyActiveImport/energyActiveExport: OCPI already support CdrDimension: ENERGY, do you need to make a distinction between ENERGY_IMPORT and ENERGY_EXPERT? If so, should I define the 'old' ENERGY value as the sum of the others?

- powerActiveImport/powerActiveExport: Current draft of OCPI already supports: MIN_CURRENT, MAX_CURRENT and MIN_POWER, MAX_POWER see:  https://github.com/ocpi/ocpi/blob/develop/mod_cdrs.asciidoc#143-cdrdimensiontype-enum
As the ChargePeriod is not one point in time, but a period, we can either provide an average of that time, or the MIN/MAX over that period. Currently OCPI can give MIN/MAX values, would that work for you? If we then define that negative values are allowed those values are the Export values.

**Comment by goelectricstations** [comment]
Hi @RobertdeLeeuw-IHomer , why you say about the CDR, the request was about the mod_session, in order to give to the end user real time information?

for questions 1: is better the distinction.
for questions 2: is not the same because user wants to know the currect active power.

let me know, thanks,

**Comment by RobertdeLeeuw-IHomer** [comment]
@goelectricstations: Why I ask for CDR? Session and CDR use the same ChargePeriod object. So If we add extra values to: CdrDimensionType, they also become available to CDRs. Which only confuses implementers when they have no use for CDRs.

I propose to add the following to CdrDimensionType:
- CURRENT: Average charging current during this `ChargingPeriod` defined in A (Ampere). When negative, the current is flowing from the EV to the grid. SHALL NOT be used in `CDR`.
- ENERGY_IMPORT: Total amount of energy charged, defined in kWh. SHALL NOT be used in `CDR`.
- ENERGY_EXPERT: Total amount of energy feed back into the grid, defined in kWh. SHALL NOT be used in `CDR`.
- POWER: Average power during this `ChargingPeriod` defined in kW (Kilowatt). When negative, the power is flowing from the EV to the grid. SHALL NOT be used in `CDR`.
- STATE_OF_CHARGE: Current state of charge of the EV. SHALL NOT be used in `CDR`.

Change description of:
- ENERGY: Total amount of energy (dis-)charged during this `ChargingPeriod`, defined in kWh. When negative, more energy was feed into the grid then charged into the EV. Default step_size is 1.
- MIN_CURRENT: Sum of the minimum current over all phases, reached during a charging session, when negative, current has flowed from the EV to the grid. Defined in A (Ampere)
- MIN_POWER: Minimum power reached during a charging session: defined in kW (Kilowatt), when negative, the power has flowed from the EV to the grid.


I also would like to add a note about SoC: OCPI makes it possible to provide SoC in the Session object. This information can be useful to show to an EV driver during charging. Implementers should be aware that SoC is only available at some DC Chargers. Which is currently a small amount of the total amount of Chargers. Of these DC Chargers, only a small percentage currently provides SoC via OCPP to the CPO. Then there is also the question if SoC is allowed to be provided to third-parties as it can be seen as privacy sensitive information. So if an implementer wants to show SoC in for example an App, care should be taken, to make the App work without SoC, as this will probably not always be available.

**Comment by goelectricstations** [comment]
Thank you so mutch, to add this info on mod_session / mod_cdr. Please, correct **ENERGY_EXPERT** with **ENERGY_EXPORT** . This will be added on 2.2?

**Comment by RobertdeLeeuw-IHomer** [comment]
Yes, I hope to release OCPI 2.2 RC2 in coming days

**Comment by FrancescoBarrile** [comment]
I do not see POWER and the other field in sessions, also should not be an Average but the realtime at that moment, if is a Average  is easy to calculate from charge period.

**Comment by RobertdeLeeuw-IHomer** [comment]
@FrancescoBarrile OCPI is not designed to provide realtime information. So currently OCPI reports information in "periods". How long these periods are is left open to the CPO to define. Over every period, the CPO can provide information like: POWER (which is the average over the that period) But also the MAX_POWER and MIN_POWER. 

If you would want to receive the current POWER, almost realtime? What would the use case be for this? To show to a driver? Why would the Average over a period not work?

**Comment by FrancescoBarrile** [comment]
Hi Robert, 

I meant not litteraly realtime. I see now that are in chargePeriods, sorry. I understand now why there is 3 key MIN_POWER MAX_POWER and POWER. I bit different than the logic of OCPP, but ok.

Regards
