### ISSUE TITLE
Want to unserstand, Why there is no Previous link in OCPI specification?

### ISSUE THREAD

**Issue by ajaysharmamca** [ocpi/ocpi#181]
Ref:
Link Link to the ‘next’ page should be provided, when this is NOT the last page. The Link
should also contain any filters present in the original request. See example below
ink: <https://www.server.com/ocpi/cpo/2.0/cdrs/?offset=200&limit=50>; rel="next"

**Comment by poohsen** [comment]
cf. the answer to the same question in our NewMotion/ocpi-endpoints repo.
