### ISSUE TITLE
session id and cdr id

### ISSUE THREAD

**Issue by goelectricstations** [ocpi/ocpi#182]
Please, make as mandatory to have the same associate id between session a cdr.

**Comment by RobertdeLeeuw-IHomer** [comment]
We currently think the best solution is to add the Session.ID to the CDR, so they are linked.

**Comment by goelectricstations** [comment]
@RobertdeLeeuw-IHomer I agree, but why need mod session + mod cdr when are the same ? 

In my option / experience I bealive will be  better to have only CDR, With added the STATUS = BILLED after CLOSED.  More light and reliable, What do you think?

**Comment by RobertdeLeeuw-IHomer** [comment]
My view on this? Session is real-time information to the Driver, CDR is for billing only. 
I have a feeling that they might become more different in the future.

**Comment by goelectricstations** [comment]
I understand, at moment is redundant and for companies have to deal with more coding.

**Comment by RobertdeLeeuw-IHomer** [comment]
It depends on the implementation, I know companies that do not have apps or portals to show near-real-time charging information. They don't implement Sessions. If we would combine Sessions and CDRs, these companies also need to be able to handle all the updates during a session, much more load then only handling the CDR. 
For other companies, that do implement Sessions, it is more work, I agree

**Comment by RobertdeLeeuw-IHomer** [comment]
#c25c4da
