### ISSUE TITLE
Charging station registration beginner question

### ISSUE THREAD

**Issue by gxmarkos** [ocpi/ocpi#188]
Dear all,
I am new to the ocpi protocol and I would like to express some questions.
Before I start I'd like to mention that my cpo has provided me with:
• ENDPOINT (example / ocpi / emsp / versions)
• CPO TOKEN
• EMSP TOKEN

After reading the ocpi 2.1.1 documentation , I decided to asign a charging station as well as a RFID card to the emsp interface. 
As i can understand, I need to create a location object and include in it the EVSE object and the connector object as well. As far as the RFID card is concerned , my cpo made the card registration from its back office and I can read it by doing a GET request  (example /ocpi/emsp/ 2.1.1/tokens).

While i am trying to find a flow to follow, I decide to register charging station  ID by myself.

If i'm right, the addition of the location object should be done by the CPO endpoint (ocpi / cpo / 2.1.1 / locations) with the CPO Token as a header and as body I should put something like this (https://github.com/ocpi/ocpi/blob/master/mod_locations.md#example).

My problem here is that i don't have a party_id , should i ask this from cpo ?
When i do a GET request (ocpi/emsp/2.1.1/credentials) it returns only token and url , other entries are marked as null.
If anyone have a better flow to follow please let me know.

Many thanks
George

**Comment by RobertdeLeeuw-IHomer** [comment]
Hi George,

Welcome. I'm trying to understand what you are trying to accomplish. 
Are you going to do an eMSP implementation? 

In which country are you located. Some countries have a central register for party_ids. If your country does not have a central register, you can choose your own party_id. If there is a central register, you have to ask them for a party_id. (there might be some fee)

**Comment by gxmarkos** [comment]
Hello Robert,
My goal is to retrieve data from the charging station such as when a charging session started, when a charging session finished, how many kWh has been consumed e.t.c. and store these data to my database.

In order to do that I have to register the charging station from the eMSP interface if I understand correctly.
Right now 'ocpi/**cpo**/2.1.1/locations' returning an empty data array : [https://imgur.com/pOBRpCa](url).
As i can understand i need to push a new location object to 'ocpi/**emsp**/2.1.1/locations' in order to retrieve data from the charging station.
I am from Greece and i want to do an eMSP implementation.

**Comment by RobertdeLeeuw-IHomer** [comment]
You seem to receive a correct OCPI message, but there dont seem to be any Charging Stations that match your request. Ask the CPO you are sending the request to, what is wrong with your request. 

As an eMSP, never have to push a new location to the CPO, the CPO can push a location to you, if they have implemente push.

**Comment by RobertdeLeeuw-IHomer** [comment]
You provided the Charging Station ID to the CPO? Why? Dont they own the Charging Stations?

**Comment by RobertdeLeeuw-IHomer** [comment]
All CPOs I known, provide information of all their charging stations via OCPI locations.
This is useful for drivers, this information is used the provide drivers with the location and availability of charging stations.

**Comment by RobertdeLeeuw-IHomer** [comment]
I think a Skype call will be easier: robert_ihomer

**Comment by gxmarkos** [comment]
Mr Robert good morning,
We finally managed to find the reason why the charging station can't register. According to our CPO it's because is already added to another platform. As I can understand a charging station can register to only one platform. 
Let me give you a better view on what is happening right now:
There are 2 companies A and B.(I represent company B)

- Company  A owns N charging stations (included the Demo station) witch is registered to a CPO.

- Company B wants to access data from the charging stations and decide to communicate with the company's A CPO.CPO create for us (company B) new credentials (TOKENS).

- Company B wants to add the charging stations (that is already registered to company A) to their new account that was created by the cpo.

Yesterday I received an email from the CPO that said that i can't register the charging stations to my company account because it's already registered to company A.

One possible solution to this problem would be that if company A give us access to the CPO with company's A credentials we would see all stations that company A owns and both sides don't want that.

At this point I have inform my supervisors for this issue and I am waiting to find a solution.
I don't think a skype call would be nesecary at the moment 
Thank you so much for your support ! 

George

**Comment by RobertdeLeeuw-IHomer** [comment]
They way you describe these companies work is very different from what I'm use to. In most countries I know, the MSP is not the owner of the Charge Point. The CPO is owner, or the CPO manages charging station for a location owner. And the way you describe that a MSP registers a Charge Point at a CPO? I really dont understand.

**Comment by gxmarkos** [comment]
The word owner it's not correct actually my bad. CPO it's the owner as you mentioned before.
The reason that you can't understand it's because we were trying to do a wrong implementation of the whole process. We have not been presented correctly since the first moment how the implementation should take place so the wrong process led us to make the wrong decisions. Now we are waiting to start the whole process again.
Thank you so much for the interest you offered us. If I face future difficulties, I will re-create a new post.
Best regards

**Comment by RobertdeLeeuw-IHomer** [comment]
You are welcome
