### ISSUE TITLE
How does a CPO tell an eMSP that a connector is removed?

### ISSUE THREAD

**Issue by julius-yang** [ocpi/ocpi#195]
I apologize if this is a resolved issue but I couldn't find anything about it.

Section 8.4.21 of OCPP 2.1.1 implies that the Connector should have a status of INOPERATIVE to indicate deletion.  However the status field of Connector no longer exists.

Section 8.2.2 of OCPP 2.1.1 says HTTP DELETE is not valid for the eMSP's connector endpoint (the CPO should use HTTP PATCH).

How should a CPO tell the eMSP that a connector is removed?  RIght now it seems like the only way is for the eMSP to send a GET to the CPO.

**Comment by YuriyDurov** [comment]
Except you can not remove connectors from the list, even using Push?

![image](https://github.com/ocpi/ocpi/assets/16725576/c08a995b-3c54-48c2-a8e2-17c7f50f5639)

**Comment by julius-yang** [comment]
Connectors can be removed/replaced arbitrarily.  EVSEs are permanent.  Every EVSE must have at least one Connector -- even if the EVSE has status REMOVED.

That, as I understand it, are the core design decisions for the existence of Connectors.

**Comment by YuriyDurov** [comment]
@julius-yang How do you deal with existing sessions that were done on these connectors that are being removed?
