### ISSUE TITLE
Session object retrieve problem 

### ISSUE THREAD

**Issue by gxmarkos** [ocpi/ocpi#197]
Dear all , 
 First of all, let's clear that I am trying to do an eMSP implementation.
 What I have done so far:
 

**1)** Received 2 tokens from the CPO

**2)** Registered both tokens at the "example.com/ocpi/emsp/versions" by doing a PUT with a body like: [credentials_example](https://github.com/ocpi/ocpi/blob/master/credentials.md#example.)
(After that CPO emailed me that I activated the connection)
(Let me note here that the party_id and country_id was a choice by me for eMSP.(I emailed the values to my CPO but it seems like they don't use it))

**3)** I added my RFID card details from back office.I can see it from : example.com/ocpi/emsp/tokens

**4)** Next step I decided to retrieve the location object from example.com/ocpi/cpo/locations.The result was like this: [locations_example](https://github.com/ocpi/ocpi/blob/master/mod_locations.md#example)
 All good here .

**5)** I started a charging session to see what data I'll retrieve.
I tried to access example.com/ocpi/cpo/sessions but no data in there (also did a GET request with pagination but still nothing).
 Let me note here that from the back office I can see the session record(It's called transaction in the back office) .

Is something that i'm not doing right?
Let me also note that the session was with 0 payment values . 
My CPO has not good knowledge of the OCPI protocol so they can't help me .

**Comment by RobertdeLeeuw-IHomer** [comment]
The CPO has OCPI implemented? Did they implement OCPI themselves? or did an IT company do it for them? If so, can that IT company help you. Most of the times it really helps if somebody can view the logging at the CPO system to see what goes wrong. 

If the CPO has everything implemented, and a transaction/session is started for your customer, you would expect Session information to become available.

**Comment by gxmarkos** [comment]
Thank you once again Robert, I emailed the CPO and asked them to investigate the issue.
