### ISSUE TITLE
Add support for multiple tariffs, depending on day of week and time of day

### ISSUE THREAD

**Issue by rutgerplantenga** [ocpi/ocpi#2]
Request to add ability to exchange different price levels depending on day of week and time of day. So not only to communicate the current tariff but also the upcoming tariffs. 

Most likely this will come down to the ability to exchange tariffs for every day of the week and every time of day, in addition to the current exchange of the current tariff.

As an EV-driver I want to be able to see the tariff-structure of a public charge point over time so that I can plan when to plug in-plug-out. This is because increasingly public charge points have tariffs that vary, with e.g. reduced tariffs during evening and night.

**Comment by RobertdeLeeuw-IHomer** [comment]
Was added in OCPI 2.0
