### ISSUE TITLE
use of connector_no in ChargingProfiles

### ISSUE THREAD

**Issue by poohsen** [ocpi/ocpi#20]
ChargingProfiles currently do not specify a connector_no, but the NDRs types ChargingProfile(Accepted|Failed|Denied) will contain a connector_no. It is not clear from the spec what the use of the connector_no is when answering a 'RequestChargingProfile'.

**Comment by RobertdeLeeuw-IHomer** [comment]
In OCPI 2.2 the Charging Profile can only be send to an ongoing session, not a Charge Point, this to prevent MSPs/SCSPs from sending ChargingProfiles that influence sessions not belonging to their customers.
