### ISSUE TITLE
Whitelist in case of remote activation

### ISSUE THREAD

**Issue by cluettig** [ocpi/ocpi#200]
Hi,

we've noticed an odd thing with the remote Activations via Commandsmodule

In case of the Role as CPO you can receive a Session start Command from an EMSP containing a Token with whitelist NEVER.
According to the Specification we need to do a remote authorization back to the EMSP.

![remote activation](https://user-images.githubusercontent.com/45224537/52852933-464ef080-311a-11e9-88fa-132935852934.png)

In case of a remote Activation from the EMSP we would assume, that the EMSP has already checked the Token.
Therefore from our Point of view "whitelist" either should be explicitly ignored in case of remote Activations via Commandsmodule
or should be an Attribute that is only mandatory for Token like RFID were the Activation is triggered within the CPO's System.

**Comment by RobertdeLeeuw-IHomer** [comment]
Which version of OCPI? 2.1.1? 

Were does the OCPI specification say:  `need to do a remote authorization back to the EMSP.`??

**Comment by cluettig** [comment]
Yes it's version 2.1.1

The Specification claims for ["whitelist" in Token](https://github.com/ocpi/ocpi/blob/master/mod_tokens.md#44-whitelisttype-enum):


NEVER | Whitelisting is never allowed/forbidden, only realtime authorization allowed. Token should always be authorized by the eMSP.
-- | --

**Comment by RobertdeLeeuw-IHomer** [comment]
Now I understand your question/issue.

As CPO I would never check the information in the START_SESSION, just send it to the Charge Point. It is then up to the Charge Point to authorize the Token, if needed. There might be Charge Points that dont need any authorization. Token might be in the Local Authorization List of the Charge Point.

If the Charge Points uses the OCPP protocol it will send an Authorize request. The CPO then needs to check the info in the Authorize.req. Is that a token it knowns, is that Token WhiteList: NEVER. Then the CPO needs to do a RealTime authorization.

By keeping these 2 things split in the implementation. Implementations become less complex. The Authorize parts needs to be implemented anyway. 
I will update the 2.2 spec with a sequence diagram and text to explain this.

![start_session_whitelist_never](https://user-images.githubusercontent.com/11439081/52939946-aa192980-3365-11e9-8337-6eb42c4bf2f5.png)

**Comment by poohsen** [comment]
can we not follow the pattern from the other modules and created a CommandToken object that will not contain the whitelist field? 

Having it is an unnecessary complication. If the MSP allows a remote start then that fact should clear the token for authorisation for the duration of the request-response cycle, as proposed above.
Is there really a good usecase for calling back to the MSP in the context of a remote start?

**Comment by RobertdeLeeuw-IHomer** [comment]
I fail to see how this is more complicating then without the whitelist field? I think removing the whitelist field will make things more complicated.

Scenario: (OCPP 1.5/1.6)
- OCPP 1.6: AuthorizeRemoteTxRequests = true (Default behavior of OCPP 1.5)
- Token X is pushed to the CPO as being whitelist NEVER.
- MSP send a SESSION_START with Token X.
- CPO send RemoteStartTransaction.req to the Charge Point.
- The Charge Point does an Authorize.req. 
- The CPO now needs to figure out which Token to use, the one provided via SESSION_START? or the Token that was Pushed via the Token module. How does the CPO now which one to choose? How long should it keep the Token that was received via the SESSION_START?

**Comment by rolandschroth** [comment]
I am still confused about the intended meaning of the whitelist field in context of a START_SESSION command. How is it supposed to be treated, especially, if it differs from what was provided to the tokens module? A clean API should not contain fields, that make no sense or are unclear in the given context.
Additionally, OCPI should not care about charger protocols at all (there is not only OCPP out there) but be consistent within it's own domain.

**Comment by RobertdeLeeuw-IHomer** [comment]
There are 2 ways to look at APIs. For OCPI with all its different modules, the requests the lasts years was to make a more clear separation between modules. To make Commands possible without implementing Tokens, we have chosen to put the Token in the START_SESSION object. We could have chosen to only put in the Token ID, but then the Token module is needed.

The Whitelist is part of the Token object. We could go for a CmdToken Object. But then the CPO might need to threat this differently. Store it for the Authorize request for a specific transaction only....

**Comment by rolandschroth** [comment]
Fair enough, it was not meant offensive.
Still my question remains: How is the whitelist field to be treated in START_SESSION context? If the answer is "ignore it", it's fine for me, but then the documentation should just say so and not leave the reader in doubt how to deal with it.

**Comment by cluettig** [comment]
I would agree to @rolandschroth a roaming protocol should not care about the communication of the CPO System with a Charger.

I agree that it make sense to seperate the Token Module which is keeping a focus on activations which were triggered in the CPO System (RFID, NFC, Bluetooth, ... ) 
from activations that were triggered in the EMSP System via Command Module

With this in mind it makes sense to create something seperate for remote activations,
but is it really nessesary to create a whole "new" Object or would it be sufficent to just send a auth_id.
This would also allow an EMSP to create a unique auth_id for the authenthication in his System, so he can trace the activation in Session and CDR's.

**Comment by RobertdeLeeuw-IHomer** [comment]
I'm not offended, I always hope to work with developers to find the best solutions possible, that take into account as much different business cases/use cases as possible. For this we need to get as much feedback and input as possible. 

I foresee 2 different ways START_SESSION can be used. 

1: The MSP (or APP) generates a unique ID for the user that it always uses when sending a START_SESSION. This has a drawback. Sessions started this way can only be stopped with an APP. 

2: The MSP uses the information of an RFID to send a START_SESSION. For this the RFID Token is send in the START_SESSION. Advantage: the RFID can still be used to stop the session.

I have not seen anybody using: Whitelist = NEVER and use Real-time authorization yet. (But that does no mean it is not used yet, I just have no seen it being used)

So I want to keep use cases. 
Can we use auth_id? (which is renamed to contract_id in OCPI 2.2), dont think so. That will not work for use case 2. There might be multiple tokens with the same contract_id (auth_id) So the CPO does not know which Token to use to start the session. You want the correct Token.uid (RFID Hidden ID)

So you want at least: Token.uid, Token.contract_id
With OCPI there is a lot of extra information in a Token that you really like to have in START_SESSION:
Token.group_id, Token.language, Token.default_profile_type.
So the only field that is a question: Whitelist.
If we don't want Whitelist anymore (not sure yet) we have 2 options, special CmdToken object or add requirement that Whitelist in START_SESSION SHALL be ignored.

If the RFID is used as Token in START_SESSION, the MSP has to send the same Token it has already send via the Tokens module. And the MSP requires real-time authorization for that Token
Questions: 
- What if the CPO does not support real-time authorization? Should the CPO reject the START_SESSION with Whitelist = NEVER?
- What if the MSP has send the Token with Whitelist = NEVER via the Tokens module. But sends the Token via the Commands module with Whitelist = ALWAYS. Should the Token received via Tokens module be updated? So the next day the RFID can be used without real-time authorization? 
- If the Token is not replaced, how long is the Token allowed to be used until it is no longer allowed to be used without real-time authorization? What if the driver uses his RFID to stop the session. Should then real-time authorization be used?

This is not a simple topic. We have to take as much use cases in mind. But I really hope we can improve this for OCPI 2.2

**Comment by RobertdeLeeuw-IHomer** [comment]
During the Strasbourg meeting it was decided to not allow real-time authorization after StartSession, the token in StartSession is already authorized by the MSP._That also solves this issue.

**Comment by Treesa-SteamA** [comment]
Hi , I have a doubt in this flow.

The EMSP Customer taps his RFID card in the CPO's charger.
The CPO sents the real-time authorisation request to the EMSP based on the whitelist field of the Token.
The EMSP responds to it accordingly.

But then what happens once the Token is authorised by EMSP.
Will the EMSP initaite START COMMAND?

Please help me understand what happens with the START and STOP flow if the session is started via RFID ?
