### ISSUE TITLE
Contradicting HTTP Status Code description

### ISSUE THREAD

**Issue by jakubnabrdalik** [ocpi/ocpi#201]
Documentation in 2.1 version says
"If a request is syntactically valid JSON and addresses an existing resource, no HTTP error should be returned. Those requests are supposed to have reached the OCPI layer. As is customary for RESTful APIs: if the resource does NOT exist, the server should return a HTTP 404 - Not Found."

When a client sends a GET request to 
```
/ocpi/emsp/2.0/locations/{country_code}/{party_id}/{location_id}
```
where {location_id} does not exists in the system, should we:
-  return HTTP status 404 with an OCPI response message with a status_code 2003 (Unknown Location)
- return HTTP status 200 with an OCPI response message with a status_code 2003 (Unknown Location)
- return HTTP status 404 without any body

The documentation later says "When the status code is in the success range (1xxx), the data field in the response message should contain the information as specified in the protocol". which suggests that it should be 200 with status_code 2003, but that contradicts the previous quotation ("if the resource does NOT exist, the server should return a HTTP 404") when the "resource" is understood according to HTTP protocol.

**Comment by RobertdeLeeuw-IHomer** [comment]
My opinion: either 1 or 3: return HTTP 404, with or without a body. 

I don't see were the documentation contradicts. It says: return 404.

The OCPI status code is never in the (1xxx) range for an error. So the text that says a response to a successful request has to contain a response format body is not relevant for an error.

**Comment by RobertdeLeeuw-IHomer** [comment]
For 2.2 we have added that the JSON format should always be used.
So in this example: "return HTTP status 404 with an OCPI response message with a status_code 2003 (Unknown Location)"

https://github.com/ocpi/ocpi/commit/914d616154e029806a8e5f8164470041d0b6b00c
