### ISSUE TITLE
Locations: Hours class required fields

### ISSUE THREAD

**Issue by iaicam** [ocpi/ocpi#202]
Reading the description for the mod_locations [Hours class](https://github.com/ocpi/ocpi/blob/master/mod_locations.md#413-hours-class). I would like some clarifacation on.

It states "Choice: one of two" for `regular_hours` and `twentyfourseven`. With `regular_hours`'s cardinality being `*`. So would this mean the following configurations of the class are valid?

```
{
	"regular_hours": null,
	"twentyfourseven": false
}
```

```
{
	"twentyfourseven": false
}
```
```
{
	"regular_hours": null
}
```

I don't think these should be considered valid. If these are valid can there be some improvement in the documentation to state that a Hours doesn't have to provide any opening times. If they are not valid can there be some improvement to state a collection can either be omitted or have one or more items?

**Comment by RobertdeLeeuw-IHomer** [comment]
All 3 examples given here are indeed not valid.
For 2.2 we have made changes, you are not the only one that though it was unclear.

The "Choice" is removed. The `twentyfourseven` is now required. 
`regular_hours`: Only to be used if twentyfourseven=false.

https://github.com/ocpi/ocpi/blob/develop/mod_locations.asciidoc#1414-hours-class

**Comment by iaicam** [comment]
Thanks for the feedback. Shouldn't the cardinality for `regular_hours` be + if only used twentyfourseven=false?

**Comment by RobertdeLeeuw-IHomer** [comment]
I think '+' would be incorrect for `regular_hours`, that would mean: "A list of at least one object."

**Comment by iaicam** [comment]
But `*` says it can be null. But you're saying it can be null if twentyfourseven=false. If when it is used it can't be null I would expect `+`.

**Comment by RobertdeLeeuw-IHomer** [comment]
You right, Need to tweak that text a bit more for 2.2: 

Only to be used if twentyfourseven=false, then this field needs to contain at least one RegularHours object.
