### ISSUE TITLE
Datamodel for version 2.2 

### ISSUE THREAD

**Issue by andersnissencph** [ocpi/ocpi#203]
Does anyone have v.2.2 implemented yet ?
We are planning to impl. this version but was wondering if anybody would like to share experiences and if possible a datamodel ?

Thanks

/anders @clever.dk

**Comment by andersnissencph** [comment]
Going for 2.1.1

**Comment by mbayings** [comment]
Hi Anders,

My advise would be for sure to implement v2.2. as it does solve several issues and complaints we had about v2.1.1.
However most companies currently implemented 2.1.1.  But as they also complained about a few things that are solved in the new version, I expect them to upgrade on short notice.

It might also be good to have those discussions on OCPI Slack channel, as there more people will see it I think. If I am right you already have an account for it. If not or if it need to be reactivated, let me know: mbayings@NKLnederland.nl
