### ISSUE TITLE
Should a session be started when a reservation is made?

### ISSUE THREAD

**Issue by RobertdeLeeuw-IHomer** [ocpi/ocpi#204]
OCPI 2.2 makes it possible to handle reservations better, reservation costs in tariffs, RESERVATION Time in CDR and Session. But unclear when to start a Session in case of a reservation.

Is it better to start a session when a reservation is created/started?
Or would it be better to start the session when the EV is connect/start charging?

**Comment by ahzf** [comment]
A reservation means you have to maintain some sort of state within your backend and the charging station. The best place for this is the charging session. Also when reservation time costs money you should send a CDR later, even when no charging ever happend.

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed: https://github.com/ocpi/ocpi/commit/81cc339b0d402bc4ded732e1a16af99f9cf6a263

**Comment by RobertDeLeeuw** [comment]
@ilaydabalik That will depend on the CPO. OCPI makes it possible to give the driver a "penalty" when the reservation is not used. Tariffs can be used for this.

**Comment by ilaydabalik** [comment]
Dear Robert de Leeuw,

Thank you for your answer and sorry about my late return, I am just trying
to get familiar with Github! Your answer was helpful for me, thank you



Robert de Leeuw ***@***.***>, 18 Şub 2022 Cum, 16:23
tarihinde şunu yazdı:
