### ISSUE TITLE
Why is cdrs total_cost mandatory?

### ISSUE THREAD

**Issue by labtrax** [ocpi/ocpi#209]
Hey,
I've a question regarding the field total_cost of the cdr:
Why is it mandatory and shouldn't it be optional?
From my point of view the tariffs module is optional for a working/essential cpo-emsp connection, so as the tariffs are optional for the cdr. But regarding this you do need tariffs to calculate a valid price.
If there is a price contract between cpo and emsp which cannot or is not covered by Ocpis tariffs, the cannot be calculated, right?
Besides the price calculation the responsibility could be located at a third party clearing house... How should the cpo know the price when creating the cdr?

Any thoughts about that? Thank you!
Malte

**Comment by RobertdeLeeuw-IHomer** [comment]
What is the use of a CDR without a price? Then just the information in the Session.

In my opinion, the CPO should know what they want to receive as payment for a Charging Session. If the clearing house is in between the eMSP and CPO, the CPO sends it CDR to the clearing house, the clearing house updates the CDR with their information and sends it to the eMSP.

**Comment by labtrax** [comment]
Hey Robert and Michel,
thanks for the quick responses!

@ Robert
_"the CPO sends it CDR to the clearing house, the clearing house updates the CDR with their information and sends it to the eMSP"_
--> There is no role 'clearing house' in V211. Beside that you are breaking the V211 protocol corresponding to
_"Because a CDR is for billing purposes, it cannot be changed/replaced, once sent to the eMSP, changes arenot allowed in a CDR."_

@ Michel
-->Sure, I only speaking about the B2B cost.

I had a look into V22 and seemingly the issue could somehow be covered with Cdrs 'credit' field. But for V211 I'm a bit clueless.

I speak to our business and come back to you, thanks for now!
Malte

**Comment by RobertdeLeeuw-IHomer** [comment]
@labtrax what is the business case you are trying to solve? Can you try to explain it? So we can try to help you find the best solution.

**Comment by KevBelisle** [comment]
From my understanding, price calculation is the CPO's responsibility.

In any case, with the information about a charging session that is exposed through OCPI's Session object, you do not have enough information to calculate the cost of a session from its Tariff.

For example, in a Session object's ChargingPeriods you do not have access to kW, therefore you have no way of applying a Tariff that contains a TariffRestriction with min_power or max_power.

**Comment by RobertdeLeeuw-IHomer** [comment]
@KevBelisle Session is not for billing, the CDR is.
But you still have a good point here, I had a discussion with other developers about this lasts week. 
It is not good that Tariff has: min_power/max_power, while CDR (and Session) ChargingPeriod has: MIN_CURRENT/MAX_CURRENT. We are discussion if we would need both Power and Current in both ChargingPeriod and TariffRestriction. And then add requirement that implements must provide MIN_CURRENT/MAX_CURRENT in the CDR when a tariff contains a min_current/max_current and the same for Power. But this also depends on the difference in AC or DC charging, so we have not finished the discussion.

**Comment by KevBelisle** [comment]
@RobertdeLeeuw-IHomer Yes, I should've said CDR in my previous comment.

Let's suppose we want to include enough information in the CDR and Session objects so an eMSP or other entity could use that and a Tariff object to calculate pricing*. Considering what we were/are discussing [here](https://github.com/ocpi/ocpi/issues/176#issuecomment-493758426), a CPO would need to start new ChargingPeriod every time the treshold for any of the Dimensions.

For example, if a Tariff defines :
- a TariffElement for energy from 0 to 10 kWh,
- a TariffElement for energy from 10 to ∞ kWh,
- a TariffElement for duration from 0 to 2 h,
- a TariffElement for duration from 2h to ∞ h,
then the corresponding CDRs and Sessions objects would need to define a new ChargingPeriod when the 10kWh threshold is crossed and when the 2h threshold is passed.

* I'm not sure this is a good idea, however the current definition of the ChargingPeriods property does support this use case: _"An optional list of charging periods that can be used to calculate and verify the total cost."_

**Comment by RobertdeLeeuw-IHomer** [comment]
I agree that that would be required. We are trying to write something for 2.2 that would be along these lines. OCPI will not require the eMSP to recalculate the price, but the CDR should contain enough information so the eMSP is able to do the recalculation. Yes, if the tariff has complex structures, that will mean that generating a CDR will also be ore complex. I suspect that 90% of all tariffs are very simple: some fixed start tariff and an X amount per kWh charged or time spend charging. That will be very simple in the CDR, only 1 or 2 ChargingPeriods are needed.

**Comment by labtrax** [comment]
Some additions corresponding to my initial posts:
At this time there is no problem regarding our clearing house. If there will be any, this could probably somehow handled by the mentioned V22 credit field.
The same for the spot market and electricity stock exchange. Here prices could be fixed much later after the charging, up to 3 three months, as far as I know. For now, we have a fixed pre-existing negotiated price for this, which probably could also be corrected by the credit field.

**Comment by RobertdeLeeuw-IHomer** [comment]
A lot depends on the country you live in, but I know a lot of consumer organisations really dont like it when the price of something is not clear up front. And they think it is not acceptable when the price is higher then expected, especially if that is know 3 months later. And personally I agree with them on this point. If you dont know the price for sure, I would show them the highest price possible and give them a deduction (lower price) later.

**Comment by RobertdeLeeuw-IHomer** [comment]
@labtrax with OCPI 2.2 you can revoke a CDR, so if the final price of a CDR changes, you could revoke a CDR and send a new one to replace it. In cases where indeed spot market prices are used, that might be the case.  But then still, you want to show a customer the price ASAP. If the prices changes later, you better lower the price, not increase it. 

So my advice either:
- First send a CDR with a price that is the maximum you expect it will cost, and then when the final price is known: revoke the original CDR and send a new one with the lower final price.
- Send the CDR when all the information is known.

Would this work? Can I close this issue?

**Comment by KevBelisle** [comment]
How would you define a Tariff in OCPI that is dependant on the going rate for electricity?

I’m not sure this is a use case that OCPI even tries to cover at the moment.

**Comment by RobertdeLeeuw-IHomer** [comment]
for OCPI 2.1/2.2 I would use the `tariff_alt_text` field and try to explain it to the customer.
Some text that explains to the customer that the price depends on the spot market and give him a maximum price and an average, something like that.

Spot price tariff is on the wish list for OCPI 3.0.

**Comment by mbayings** [comment]
Be aware of the laws that require you to send a correct transaction information incl cost immediately after the transaction. This must be in lign with the information the customer received before he started the transaction. Changing a price during a session might not be allowed, unless you informed the customer very well before and it is in line with his/her expectations. 
My advice would be: do not change tariff of a session during the session. In most cases this will be against consumer laws.
