### ISSUE TITLE
Are URL paramters inclusive or exclusive?

### ISSUE THREAD

**Issue by Namoshek** [ocpi/ocpi#215]
The question is basically already in the title. While reading the OCPI 2.2-rc1 documentation, I noticed that the description of URL parameters is mostly ambiguous. For example the URL parameters of chapter 7.2.1.1:

Parameter | DataType | Required | Descrpition
------------|-----------|------------|--------------
|date_from |DateTime |no |Only return Locations that have `last_updated` after this Date/Time. 
|date_to |DateTime |no |Only return Locations that have `last_updated` before this Date/Time. 

What exactly do **after** and **before** mean in this context? Are they inclusive (`>=`/`<=`) or exclusive (`>`/`<`)?

**Comment by RobertdeLeeuw-IHomer** [comment]
Hmm, I thought I had added something for this to 2.2, but you are right, that is currently not in any OCPI spec. I don't really have a strong preference. In tend to go for inclusive.

**Comment by Namoshek** [comment]
It might be that I haven't come across the section where you specified it yet. The cited table is from the `mod_locations.asciidoc` part.

Anyway, in my opinion it would make sense to:
- make sure all occurences of parameters are handled consistently regarding inclusiveness/exclusiveness (I prefer **inclusiveness** as well).
- write something in chapter **2. Terminology and Definitions** about this matter.

If it is ok for you, I'll do the first point as part of my review in #214 and the second one afterwards.

**Comment by RobertdeLeeuw-IHomer** [comment]
Did some searching: https://stackoverflow.com/questions/9795391/is-there-a-standard-for-inclusive-exclusive-ends-of-time-intervals 
Seems to propose: From inclusive, To exclusive. Which seems to make sense to me. I have asked the OCPI community for their opinion.

**Comment by poohsen** [comment]
the comments to the accepted answer are quite convincing. +1 for the `[A, B)` interpretation.
