### ISSUE TITLE
Description for Session Object start_datetime

### ISSUE THREAD

**Issue by cluettig** [ocpi/ocpi#216]
Hi,

we've noticed during the development that there is a description for the start_datetime in the [SessionObject](https://github.com/ocpi/ocpi/blob/master/mod_sessions.md#31-session-object) that migth be a bit confusing or incorrect

The description claims that start_datetime is a mandatory field that describes:

> The time when the Session became active

In comparison with the the description for end_datetime:

> The time when the session is completed

It could be assumed that the start_datetime is  related to the [SessionStatus](https://github.com/ocpi/ocpi/blob/master/mod_sessions.md#41-sessionstatus-enum), even if it seems more as the Time when the Session is created or started within the System of a CPO, if we take the Session Status "PENDING" into account.
![ActiveSession](https://user-images.githubusercontent.com/45224537/59014510-1b111e00-883d-11e9-9c0d-ed1bf27cdb64.png)

**Comment by jirouette** [comment]
So the documentation should claim that `start_datetime` is maybe inaccurate when the status is `PENDING`, but has to be correct for `ACTIVE`, `COMPLETED` and `INVALID`. Is that what you mean ?

**Comment by cluettig** [comment]
From my Point of view should the description be adjusted to something like

> The time when the Session was started in the System of the CPO

**Comment by RobertdeLeeuw-IHomer** [comment]
I agree that this text can be improved. 
I would go for the time the transaction was started at the Charge Point. If the Charge Point was offline, it could theoretically take days before the transaction is received by the CPO, and the point in time is of no use to the driver.

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed: https://github.com/ocpi/ocpi/commit/0b94f50efc7a34c9c6711a86d095830722273b3e
