### ISSUE TITLE
Suggested Facility type: Park&Ride

### ISSUE THREAD

**Issue by Namoshek** [ocpi/ocpi#217]
The `Facility` enum contains a few options that could serve as alternative like `TRAIN_STATION` or `CARPOOL_PARKING`. Yet I think a `PARK_AND_RIDE` option would still make sense as Park&Ride parking lots are often related to the metro and not so much to trains in the general sense.

**Comment by poohsen** [comment]
could you explain what park&ride is?

**Comment by Namoshek** [comment]
In Austria and Germany we have park&ride parking lots which are parking lots especially designed for people that commute by car into town and travel the last mile(s) by other means of transportation. These parking lots are normally located a bit outside of the cities in order to keep car traffic in cities low while offering people that have no other choice to still use their car for most part of their commute. People using P&R are normally parking for 8-10 hours per workday and cannot unplig or repark their vehicle in between.

**Comment by RobertdeLeeuw-IHomer** [comment]
I understand what you mean. But a park&ride for me is a parking lot. I would propose to add both: `PARKING_LOT` and `METRO_STATION` Then you can add `PARKING_LOT` and also the different types of transport that are available. But also makes it possible to add `PARKING_LOT` when there is no public transport.

**Comment by Namoshek** [comment]
Sounds reasonable to me and gives more flexibility as well. Maybe it's also worth thinking about additional options when we are extending the spec (to prevent regular extensions if that's an issue). 

What comes to my mind right away is `TRAM_STATION`. It fits right in with `BUS_STOP`, `TAXI_STAND`, `TRAIN_STATION`, `METRO_STATION` and `AIRPORT`.

Also quite obvious seems something along the lines of `BIKE_SHARING` (but a more general form like `LAST_MILE_OFFER` maybe). I don't know too much about other European cities, but at least in Vienna (e-)bike sharing and e-scooter sharing services have gotten more important recently.

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed: https://github.com/ocpi/ocpi/commit/169340e15a264f6b99d76539cbf06e5e5a4539a9

**Comment by Namoshek** [comment]
@RobertdeLeeuw-IHomer Did you miss `METRO_STATION`?

**Comment by RobertdeLeeuw-IHomer** [comment]
Oeps. fixed: https://github.com/ocpi/ocpi/commit/ce6d22c60bf17d4c8ee665ee249f7c2e9a1ab3ca
