### ISSUE TITLE
Locations: Hours class properties overriding each other

### ISSUE THREAD

**Issue by Namoshek** [ocpi/ocpi#218]
**Branch:** develop

There is a piece of text in the `mod_locations_hours_class` definition that is unclear to me:

> **exceptional_closings:** Exceptions for specified calendar dates, time-range based. Periods the station is not operating/accessible. Overwriting regularHours and exceptionalOpenings. Should not overlap exceptionalOpenings.

The text says that the option `exceptional_closings` overrides `exceptional_openings`, yet the provided values should not overlap with said `exceptional_openings`. This makes me wonder if the `should not` is actually a `MUST NOT` or if the last sentence should be removed from the description as it is not true (anymore?).

**Comment by poohsen** [comment]
the way i understand it is that if you have:

```
exceptional_opening: |-----------------------------|
exceptional_closing:             |------------|
```
then the closing times "overwrite" the opening times in the sense that the result is 2 open periods:
```
resulting_opening:   |----------|             |----|
```

but you should **not** produce resulting opening times such as
```
exceptional_opening: |-----------------------------|
exceptional_closing:                            |------------|
```

If this is the correct interpretation then the 2nd rule could better  be formulated as "should at all times satisfy `exceptional_opening.period_begin <= exceptional_closing.period_begin && exceptional_opening.period_end >= exceptional_closing.period_end`".

**Comment by Namoshek** [comment]
That's an interesting interpretation and if this is what is meant, I'd support adding example graphics like your ascii art to the docs.

**Comment by RobertdeLeeuw-IHomer** [comment]
I added some diagrams to explain exceptional opening and closing. But the combination of exceptional opening and closing hours? In the same time period? I dont see the advantage of this. The exceptional_opening/closings are DateTime, they are not recurring. so if you want to create what @poohsen has draw above, you could just as easily used 2 exceptional_opening periods. 

Also exceptional_openings contains a confusing sentence: "May overlap regular rules." What would that mean? Did they mean: an `exceptional_opening` period may overlap `regular_hours`? If so, I dont see the advantage in allowing this. 

My proposal: 

exceptional_openings: "Exceptions for specified calendar dates, time-range based. Periods the station is operating/accessible. Additional to regular hours. May not overlap with `regular_hours` and `exceptional_closings`"

exceptional_closings: "Exceptions for specified calendar dates, time-range based. Periods the station
is not operating/accessible. Overwriting `regular_hours` and `twentyfourseven`. Should not overlap `exceptional_openings`."

**Comment by poohsen** [comment]
>  Did they mean: an exceptional_opening period may overlap regular_hours? If so, I dont see the advantage in allowing this.

I think it's the other way around: there's no advantage from allowing this. You don't have to adjust the exception to not overlap with the rule since overlapping doesn't change anything: during the time where they overlap, the location is open.

**Comment by RobertdeLeeuw-IHomer** [comment]
So you mean the: `exceptional_opening` may overlap and partially overlap `regular_hours`, since it does not change anything. 

Problem I see with allowing overlap for: `exceptional_opening`. What will have priority? When for the same moment: `regular_hours`, `exceptional_opening` and `exceptional_closing` are given. Is the location open or closed?

**Comment by poohsen** [comment]
my apologies. I meant to write

"I think it's the other way around: there's no advantage from **dis**allowing this."

I corrected my post above now.

And you're right, if we allow overlaps we need to define the priority for all three.  I'd say `exceptional_closing > exceptional_opening > regular_hours` where `a > b` means that `a` takes precedence before `b`. 

I think this is nicer to work with from the POV of whoever has to code this up. Curious to hear what others think.

**Comment by Namoshek** [comment]
I think both solutions (overlapping and not overlapping) have pros and cons. Clearly, overlapping is easier to implement as no validation/calculation is required at all, but for newcomers their priority may be ambiguous as well. No overlapping on the other hand doesn't mean you cannot use overlapping dates in your application - it only means you may not send overlapping data within OCPI (i.e. calculation of non-overlapping periods is required).

Simplified that means:
- either OCPI specifies a priority between these types of opening/closing hours and allows members to transfer overlapping periods, or
- each developer decides for themselves if they allow overlapping periods and what priority each type of period has in their system, but transfered are only non-overlapping periods which must be calculated before sending the data to OCPI partners.

I prefere the first solution because calculating non-overlapping periods is quite difficult and the only situation where one needs to utilize a priority with the first solution is when the opening state (`open` or `closed`) is displayed. And this decision is quite simple if the priority is known.

**Comment by RobertdeLeeuw-IHomer** [comment]
Allowing overlapping periods makes it easier for the sender (CPO) to implement: They do not have to prevent overlap.
But this is harder for the the receiver (eMSP/NSP) to implement, they have to convert the opening hours to human readable text.

Non-overlapping periods is the other way around.
