### ISSUE TITLE
What information do we need to include on the CDR charging period

### ISSUE THREAD

**Issue by vadimcherniy** [ocpi/ocpi#222]
I've a question regarding CDR implementation:
What information do we need to include on the CDR charging period?
OCPI documentation has example (https://github.com/ocpi/ocpi/blob/master/mod_cdrs.md#31-cdr-object), but it can't explain everything, because it very simple tariff. What if we have complex tariff?

For example, if a Tariff defines :
a TariffElement: pay for time, restrictions: from 0 to 10 kWh,
a TariffElement: pay for time, restrictions: from 10 to ∞ kWh,
a TariffElement: pay for energy, restrictions: from 0 to 2 h,
a TariffElement: pay for energy, restrictions: from 2h to ∞ h,

For my opinion in this case CDR charging period looks like: 
```
"charging_periods": [
        {
            "start_date_time": "2019-06-29T12:39:093Z",
            "dimensions": [
                {
                    "type": "TIME",
                    "volume": 1.237
                }
            ]
        },
        {
            "start_date_time": "2019-06-29T13:12:194Z",
            "dimensions": [
                {
                    "type": "TIME",
                    "volume": 2.419
                }
            ]
        },
        {
            "start_date_time": "2019-06-29T14:23:600Z",
            "dimensions": [
                {
                    "type": "ENERGY",
                    "volume": 12.26
                }
            ]
        },
        {
            "start_date_time": "2019-06-29T16:23:600Z",
            "dimensions": [
                {
                    "type": "ENERGY",
                    "volume": 6.12
                }
            ]
        }
    ]
```

If it's true, how we can calculate session after it end? We have four tariff element and four different price with them. We need to know which element apply to cdr charge period. In this case it is impossible. If we have kWh restriction we need to include energy consumed also.

**Comment by Namoshek** [comment]
For me, your given charging periods example doesn't make any sense. To get a bit more concrete, here is how I understand your pricing logic:

| kWh \ Time | 1   | 2   |
|------------|-----|-----|
| 1          | 101 | 102 |
| 2          | 103 | 104 |

_101-104 are tariff identifiers._

 With these tariff elements, you should have the following charging periods:

#### With average charging power >5kW (energy limit reached before time limit)

_We assume a session from 06:00 until 09:00._

1. One that starts around the same time as your session (when the actual charging starts) _[assume 06:00]_
    - Dimension **ENERGY** with value **10**
    - Dimension **TIME** with value **0.75**
    - Tariff ID **101**
2. One that starts as soon as the first **10 kWh** are charged _[assume 06:45]_
    - Dimension **ENERGY** with value **15** _[just an assumption based on the previous charging speed]_
    - Dimension **TIME** with value **1.25**
    - Tariff ID **103**
3. One that starts **2h** after charging start _[which is 08:00]_
    - Dimension **ENERGY** with value **12** _[just an assumption based on the previous charging speed]_
    - Dimension **TIME** with value **1** _[because session ends at 09:00]_
    - Tariff ID **104**

As you reached the 10 kWh limit for the energy dimension before the time limit has been reached, the tariff with ID **102** never occurs in the CDR.

#### With average charging power <5kW (time limit reached before energy limit)

_We again assume a session from 06:00 until 09:00._

1. One that starts around the same time as your session (when the actual charging starts) _[assume 06:00]_
    - Dimension **ENERGY** with value **8** _[result of random charging speed <5kW]_
    - Dimension **TIME** with value **2**
    - Tariff ID **101**
2. One that starts **2h** after charging start _[which is 08:00]_
    - Dimension **ENERGY** with value **2**
    - Dimension **TIME** with value **0.5** _[assumption based on previous charging speed]_
    - Tariff ID **102**
3. One that starts as soon as the first **10 kWh** are charged _[which is 08:30]_
    - Dimension **ENERGY** with value **2** _[assumption based on previous charging speed]_
    - Dimension **TIME** with value **0.5** _[because session ends at 09:00]_
    - Tariff ID **104**

This time you reached the time limit of 2h before charging 10 kWh, which means the tariff with ID **103** never occurs in the CDR.

---

In my opinion, the important part is that both, time and energy, are always relevant for your pricing as you are using both dimension all the way through. This means that all charging periods must contain both dimensions in my opinion.

**Comment by mbayings** [comment]
Quote: If it's true, how we can calculate session after it end? We have four tariff element and four different price with them. We need to know which element apply to cdr charge period. In this case it is impossible. If we have kWh restriction we need to include energy consumed also.

Be aware that you have a legal requirement to show the tariff before a charge session is started in an understandable way. And after the session you must receive transaction information that you can verify with the information you received before. 
If you use 4 different tariff elements and 4 different prices with them, you can never do this. 

So my strong advice: don't make it so difficult that know one can understand it anymore. It is not only against the laws, but also will results in complaints from EV drivers.

**Comment by RobertdeLeeuw-IHomer** [comment]
You should at least send a ChargingPeriod, everytime the tariff changes to a different element. 
So on would be exactly at 2 hours, the moment it switches from a tariff before 2 hours to a tariff after 2 hours. The same goes for the moment that 10kWh has been charged. So for a long charging session with more then 10kWh I would expect at least 3 ChargingPeriods. 

- ChargingPeriod from start of charging until either 2 hours of charging or 10 kWh of energy is charged.
- ChargingPeriod from the pervious moment until after 2 hours and 10 kWh is charged.
- ChargingPeriod that ends with the end of charging.

That is the bear minimum.
