### ISSUE TITLE
"token" or "cdr_token"?

### ISSUE THREAD

**Issue by mhirschbvkw** [ocpi/ocpi#227]
Hi all,

in https://github.com/ocpi/ocpi/blob/develop/mod_cdrs.asciidoc#mod_cdrs_cdr_token_object , the token-fieldname is "cdr_token":

> 

cdr_token | CdrToken | 1 | Token used to start this charging session, includes all the relevant information to identify the unique token.
-- | -- | -- | --

, in the CDR-example of 2.2 RC2, the field name is just "token" (https://github.com/ocpi/ocpi/blob/develop/releases/2.2-RC2/examples/cdr_example.json):
```
    "token": { 
    "uid": "012345678",
    "type": "RFID",
    "contract_id": "DE8ACC12E46L89",
    "visual_number": "DF000-2001-8999-1",
    "issuer": "TheNewMotion",
    "group_id": "DF000-2001-8999",
    "valid": true,
    "whitelist": "ALLOWED",
    "last_updated": "2015-06-29T22:39:09Z"
   },
```
Additionally, I can't find the field-definition of  "visual_number" ff. in https://github.com/ocpi/ocpi/blob/develop/mod_cdrs.asciidoc#mod_cdrs_cdr_token_object 

thx and br
Mike

**Comment by RobertdeLeeuw-IHomer** [comment]
I think I have forgotten to update the CDR example in OCPI 2.2

**Comment by RobertdeLeeuw-IHomer** [comment]
fixed: https://github.com/ocpi/ocpi/commit/b41198d106d22c4954a59f960edbfce6a4f4296b
