### ISSUE TITLE
OpenAPI/Swagger definition?

### ISSUE THREAD

**Issue by webprofusion-chrisc** [ocpi/ocpi#228]
Hi, 

Open Charge Map (https://openchargemap.org) has recently had interest from network operators who would like to push data to us using the OCPI API. I've been looking at the specification PDF etc but it would be great if an API definition could also be maintained as an OpenAPI (Swagger) definition, this would help greatly in keeping client/server models up to date with the spec.

Perhaps this is already being done?

There is an example of this here which might be useful as a starting point:
https://github.com/emerout/ocpi-swagger-sample/blob/master/spec/swagger.yaml

**Comment by RobertdeLeeuw-IHomer** [comment]
We are working on Swagger/OpenAPI files for OCPI 2.2. Hope the publish a first version with a couple of weeks.

**Comment by webprofusion-chrisc** [comment]
Great! I look forward to testing it out.

**Comment by corneliusweig** [comment]
@RobertdeLeeuw-IHomer Are you still planning to publish an OpenAPI spec for OCPI? We are also interested :)
cc @nikosgraser @Hupka

**Comment by RobertdeLeeuw-IHomer** [comment]
Yes, I'm working on it. Issue is getting the documentation generated in a format to looks good. 
OpenAPI/Swagger 2 does not support enum datatypes. They are converted to String with a list op allowed values. That is workable, but looks a lot different from 2.1

**Comment by corneliusweig** [comment]
@RobertdeLeeuw-IHomer that's great to hear, just wanted to know whether this has been dropped or is still being worked on.

I also have a concern about the licence this OpenAPI work will be published under. If I understand correctly, the current repository license does not allow derivatives of the works therein. The OpenAPI spec would however be much more useful, if it can be used as a basis to derive the actual spec for an implementation of it. For example, deleting parts of it (if functionality has not been implemented yet), or amending passages (when functionality has been implemented partially and placeholders are added). Will it be possible to do such things?

**Comment by RobertdeLeeuw-IHomer** [comment]
@corneliusweig good that you point this out. We have not thought about a license for the OpenAPI documentation. I think we want everybody to use it as they feel fit. But we don't wont people to start distributing a kind of variants on OCPI 2.2. I think the market is not helped when a lot of variants are being used and it becomes unclear what the standard version is.

**Comment by corneliusweig** [comment]
> I think the market is not helped when a lot of variants are being used and it becomes unclear what the standard version is.

That makes absolute sense and is in anybody's interest who implements this standard.

Now the first question is, if the OpenAPI spec can even be released under a less restrictive license, without compromising the goal of preventing derivations of the OCPI standard. If this can be allowed, the next question is how to release the OpenAPI documents under a different license. Here it makes most sense to me, if a different sub-repo in the https://github.com/ocpi is created.

---

Maybe I should also explain our situation: we are implementing the OCPI standard, but our work is far from finished. As we want to document the endpoints we implemented with OpenAPI, it would be useful to have an official OpenAPI spec as a baseline. From that we would need to remove the parts that are not implemented yet and add placeholders. If this kind of derivative is prohibited, an official OpenAPI spec is not really useful for our purpose.

**Comment by webprofusion-chrisc** [comment]
Regaring license - most open licenses allow derivative works but will retain copyright of the name (even MIT etc). So someone couldn't use the name OCPI as the branding for some other derived thing.

As with any specification you should be free to implement whichever parts you need (and you may even need to extend with your own metadata/endpoints etc). However, using and being based on a standard is different from being officially compliant with a standard (i.e. certified as compliant).

What is the current license and how does it affected implementations? As this is mostly a specification a Creative Commons license would make sense?

**Comment by RobertdeLeeuw-IHomer** [comment]
Current license is: _Creative Commons Attribution- NoDerivatives 4.0 International Public License_

See: https://github.com/ocpi/ocpi/blob/master/version_history.md

**Comment by webprofusion-chrisc** [comment]
Thanks, I see the problem. I think there could be a simpler license for this type of resource - perhaps a change to just CC-BY-A? The issue with the No Derivatives clause as I see it is that transforming the spec into an API definition and then hosting that as a different body of work creates a derivative work (for example), as is using any API specification you provide (swagger/ OpenAPI) and transforming that into client/server model code for inclusion in a new software product. Obviously I'm not a lawyer and neither are most people who come along looking to use OCPI.

What losses do you anticipate in a worst case scenario that lead you to require a restrictive license? 

For Open Charge Map we have frequently came up against inflexible licensing issues and have considered just a public domain license (basically a 'who cares, use it if you want' license) but have held onto the attribution requirement because otherwise users don't know where the data is coming from in order to feedback changes.

**Comment by logemann** [comment]
any news on that?

**Comment by RobertdeLeeuw-IHomer** [comment]
Currently looking into the files that have been created by Share&Charge: https://shareandcharge.atlassian.net/wiki/spaces/OCN/blog/2020/06/29/697106433/Open+API+3.0+specification+for+OCN+1.0+released

After a good review they might become the official files for OCPI, but for now, look at them, them might be a very good starting point for an OCPI 2.2 implementation

**Comment by adamstaveley** [comment]
Just to add to what @RobertdeLeeuw-IHomer said, we generated the Open API 3.0 spec based on the existing OCPI v2.2 API implemented by the Open Charging Network Node: https://bitbucket.org/shareandcharge/ocn-node.

There are some (not many) OCN-specific parts which would need to be removed for any official 2.2. spec, but otherwise it's a full OCPI 2.2. implementation. I would say the OCPI data types will probably need some improvement (the OCPI typing in the OCN is fairly forgiving), but your mileage may vary.

**Comment by webprofusion-chrisc** [comment]
@adamstaveley nice! Looks like some very serious work has gone into the OCN stuff (first time I've seen it). Are you guys interested in running/helping with an open data repository for charging locations at all? This is what we do with Open Charge Map but it's not particularly integrated with any networks and mostly relies on crowdsourcing of data. Our aim is basically to get the data out there for others to use (including the public) instead of having it locked up in private data silos. We currently serve a little over 3.5 million queries per month from our API to various consumers. We're not particularly attached to our current technology/data, for us it's more about having one reliable source of open data people can use without licensing fees.

**Comment by corneliusweig** [comment]
cc @nikosgraser

**Comment by chrisburgahn** [comment]
@webprofusion-chrisc Very interesting idea and could definitely be something to combine with the OCN. UI guess you an Adam already had a chat? Are you on the OCPI Slack Channel? Then we could take the conversation there. Just look out for my name: Christopher Burgahn

**Comment by webprofusion-chrisc** [comment]
Further to this I have taken the liberty of forking OCNs open-api definition and removing the OCN extensions (which clearly could not be part of an official OCPI specification file) happy to make this a PR. 

Regarding OSS licensing of the content, this file is entirely different to the original so I'm unsure if the Apache license needs to apply [technically it's not a derivative work if it only binds by name to the same interfaces, which is literally what this does]:

https://github.com/openchargemap/ocm-docs/blob/master/Model/schema/ocpi-2.2-openapi-spec.yaml

I have no idea how complete this specification file is relative to OCPI 2.2 itself, that would require a knowledgeable reviewer. While I'm not sure that OCPI should be defined solely as an Open API spec it would be great if the OCPI spec and Open API spec were built in tandem, kind of as a proof/test of each other.

**Comment by reinierl** [comment]
Thanks!

It doesn't seem to be copying wording from the OCPI spec. That means that one the positive side indeed I don't see how there could be legal issues with it. The downside is that I also don't think it is anywhere near complete when it comes of descriptions of the behavior of OCPI parties, that is, when they should call these endpoints and how they should respond to the calls.

For OCPI 3.0 we plan to release official OpenAPI files, but OCPI 3.0 development happens in private.

**Comment by webprofusion-chrisc** [comment]
@reinierl great, I think now more than ever OpenAPI is extremely important for API development and documentation, it saves a lot of pain in implementing compatible clients (and server implementations) and provides a sense-check that would be difficult to achieve otherwise. While it's obviously difficult to keep both a spec document and an OpenAPI spec in sync I do think it will benefit everyone in the long term.

**Comment by webprofusion-chrisc** [comment]
@reinierl it's also worth saying that even an incomplete OpenAPI spec is better than none at all, as long as the parts that are there are indeed correct. OCPI 2.2 (and older versions) will be around for a very long time. Note that I used https://stoplight.io/studio/ to edit this file, it can be useful to jump between a couple of OpenAPI editors because the catch different validations errors and you can get a sense of how effective the documentation is when you see it in different contexts.

**Comment by rkettelerij** [comment]
@reinierl Is an OpenAPI (Swagger) spec still on the roadmap for OCPI 2.2.x? The website mentions for OCPI v2.2.1 (https://evroaming.org/downloads/):

> This version is also getting better implementation support; Swagger files will be available soon. Join the community to get the latest information when available.

**Comment by reinierl** [comment]
We're not working on it for 2.2.1 at the moment. We do plan to release OpenAPI documentation for 3.0 when that comes.
