### ISSUE TITLE
Charging Point Information Exchange

### ISSUE THREAD

**Issue by simonphilips** [ocpi/ocpi#23]
I've written a draft of the Charging Point Information Exchange message format based on the decisions from last OCPI meeting (2015-04-30).

I was thinking of cloning the repository but I'm not sure how to organise the chapters. Different files? One file? I didn't want to update README.md because its layout is a bit different than what I have in mind so I'll write it as an issue first.

I'll write my further thoughts on the content as replies to this post.

Note that in my examples I did not specify "PRICINGSCHEMES", I want to look into the OCPP2.0 pricing schemes format first.

----

# Charging point information exchange

## Message format

	{
		"locations": Location[],
		"evses": EVSE[]
	}

A charging point information exchange message consists of two parts:
- an array of Location objects
- an array of EVSE objects

	
### Location objects

The *Location* object describes the location and its properties where a group of EVSE's that belong together are installed. Typically the *Location* object is the exact location of the group of EVSE's, but it can also be the entrance of a parking garage which contains these EVSE's. The exact way to reach each EVSE can then be further specified by its own properties.

A *Location* without valid *EVSE* objects can be considered as expired and should no longer be displayed.

#### Format

    {
        "id": required string,
        "operator_id": required string,
        "operator_name": string,
        "operator_phone": string,
        "operator_logo": string,    # URL
        "operator_website": string, # URL

        "latitude": required decimal,
        "longitude": required decimal,

        "address": required string,
        "postcode": required string,
        "city": required string,
        "country": required string,

        "name": string,
        "directions": string,
        "opening_hours": string,    # iCalendar format
        "opening_description": string
    }
    
#### Description:
    
- string **id**: uniquely identifies the location, a location id is only unique per Charge Point Operator.
- string **operator_id**: uniquely identifies the operator
- string *operator_name*: display name of the operator
- URL *operator_website*: public URL to the website of the operator
- URL *operator_logo*: public URL to the logo of an operator
- decimal **latitude**: the latitude coordinate for this location
- decimal **longitude**: the longitude coordinate for this location
- string **country**: ISO 3166-1 alpha-2 for the country of this location
- string **city**: name of the city
- string **address**: street or block, and number
- string *name*: display name of the location
- string *directions*: optional directions on how to reach the location
- string *opening_hours*: rfc5545 iCalendar format for the opening hours
- string *opening_description*: a human readable description of the opening hours

### EVSE objects

The *EVSE* object describes the part that controls the power supply to a single EV in a single session. It always belongs to a *Location* object. It will only contain directions to get from the location to the EVSE (i.e. *floor*, *physical_number* or *directions*). Whem these properties are insufficient to reach the EVSE from the *Location* point, then it typically indicates that this EVSE should be put in a different *Location* object (sometimes with the same address but with different coordinates/directions).

An *EVSE* object has a list of connectors which can not be used simultaneously: only one connector per EVSE may be used at a time. The list of connectors is seen as atomic. This implies that for any changes or updates to a single connector, the full list of all connectors will have to be specified. Any connector not on that list is considered as deleted.

#### Format

    {
        "id": required string,
        "location_id": required string,
        "status": required enum Status,
        "capabilities": required Capability[],
        "connectors": required Connector[],

        "physical_number": int,
        "directions": string,
        "floor": decimal,

        "valid_from": string,   # ISO 8601 time format
        "valid_until": string   # ISO 8601 time format
    }
    
#### Description:
    
- string **id**: uniquely identifies the EVSE, unlike the location id, the EVSE id must follow the specification of ISO/IEC 15118-2 - Annex H "Specification of Identifiers".
- string **location_id**: the id of the *Location* object that contains this EVSE. If the *Location* object does not exist, this EVSE may be discarded (and it should not have been sent in the first place).
- enum Status **status**: indicates the status of the EVSE
  - AVAILABLE: the EVSE is available to use
  - RESERVED: the EVSE is reserved by someone
  - CHARGING: the EVSE is occupied
  - OUT_OF_SERVICE: the EVSE is currently unavailable
- Capability[] **capabilities**: a list of functionalities that the EVSE is capable of
  - RESERVABLE: the EVSE can be reserved
  - CHARGING_PROFILE_CAPABLE: the EVSE supports Charging Profiles
- Connector[] **connectors**: a list of all available connectors on the EVSE, see the specification for the *Connector* object.
- int *physical_number*: a number on the EVSE for visual identification.
- decimal *floor*: the number of the floor where this EVSE located, typically for parking garages.
- string *directions*: human readable directions when more detailed information on how to reach the EVSE from the *Location* is required.
- string *valid_from*: ISO 8601 formatted timestamp to describe when the EVSE becomes available. When this field is null, the EVSE has been made available.
- string *valid_until*: ISO 8601 formatted timestamp to describe when the EVSE expires. When this field is null, the EVSE is not expired.

### Connector objects

A connector is the socket available for the EV to make use of. A single EVSE may provide multiple sockets but only one of these sockets can be in use at the same time. A connector always belongs to an *EVSE* object.

#### Format

    {
        "id": required string,
        "type": required enum ConnectorType,
        "charge_protocol": enumeration ChargeProtocolType,
        
        "power_type": required enum PowerType,
        "voltage": required int,
        "amperage": required int,

        "price_schemes": required PricingScheme[],
        "terms_and_contitions": string,  # URL
    }
    
#### Description:
    
- string **id**: uniquely identifies the connector within the EVSE. Two connectors may have the same id as long as they do not belong to the same *EVSE* object.
- enum ConnectorType **type**: see *ConnectorType* specification in OCPP2.0
- enum ChargeProtocolType *charge_protocol*: 
  - MODE3
  - CHADEMO
  - ISO15118
  - UNCONTROLLED
- enum PowerType **power_type**:
  - AC_1_PHASE
  - AC_3_PHASE
  - DC
- int **voltage**: voltage of the connector (line to neutral for AC_3_PHASE), in volt [V]
- int **amperage**: maximum amperage of the connector, in ampere [A]
- PricingScheme[] **price_schemes**: list of applicable price schemes (see *PriceScheme* specification in OCPP2.0)
- string *terms_and_contitions*: URL to the operator's terms and conditions

### Synchronisation messages

Synchronisation messages are based on a PULL model: the eMSP pulls the information from the Charge Point Operator. A synchronisation message contains all information of all available locations and EVSE's. Any older information that is not specified in the message is considered as no longer valid. 

Each object must contain all required fields. Fields that are not specified may be considered as null values.

#### Example

	{
		"locations": [
			{
				"location_id": "LOC1",
				"operator_id": "BC",
				"operator_name": "BeCharged",

				"latitude": 51.04759,
				"longitude": 3.72994,

				"address": "F.Rooseveltlaan 3A",
				"postcode": "9000",
				"city": "Gent",
				"country": "BE",

				"name": "Gent Zuid",
			}
		],
		"evses": [
			{
				"id": "BE-BEC-E041503001",
				"location_id": "LOC1",

				"status": "AVAILABLE",
				"capabilities": ["RESERVABLE"],

				"connectors": [
					{
						"id": "1",
						"type": "cType2",
						"price_schemes": PRICINGSCHEMES
					},
					{
						"id": "2",
						"type": "sType2",
						"price_schemes": PRICINGSCHEMES
					}
				],

				"physical_number": 1,
				"floor": -1,

				"valid_from": "2015-04-27T10:00:00+0200"
			},
			{
				"evse_id": "BE-BEC-E041503002",
				"location_id": "LOC1",

				"status": "RESERVED",
				"capabilities": ["RESERVABLE"],

				"connectors": [
					{
						"id": "1",
						"type": "sType2",
						"price_schemes": PRICINGSCHEMES
					}
				],

				"physical_number": 2,
				"floor": -2
			}
		]
	}

### Update messages

Update messages are based on a PUSH model: the Charge Point Operator notifies the eMSP of changes to any objects. Update messages are similar to synchronisation messages except that only the object id is required. Only the fields that are updated are specified. Any fields or objects that are not specified in the update message are considered unchanged.

#### Example: a simple status update

This is the most common type of update message to notify e-MSP's that an EVSE is now occupied.

	{
		"evses": [
			{
				"id": "BE-BEC-E041503001",
				"status": "OCCUPIED",
			}
		]
	}

#### Example: advanced update

In this example the name of the location is updated and connector 2 of EVSE *BE-BEC-E041503001* receives a new pricing scheme. Note that since the connectors property is atomic, we also have to specify the information for connector 1. 

	{
		"locations": [
			{
				"id": "LOC1",
				"name": "Interparking Gent Zuid",
			}
		],
		"evses": [
			{
				"id": "BE-BEC-E041503001",
				"status": "AVAILABLE",
				"connectors": [
					{
						"id": "1",
						"type": "cType2",
						"price": PRICINGSCHEMES
					},
					{
						"id": "2",
						"type": "sType2",
						"price": NEW_PRICINGSCHEMES
					}
				]
			}
		]
	}
	
#### Example: add an EVSE

To add an *EVSE* or a *Location*, simply put the full object in an update message, including all its required fields. Since the id is new, the receiving party will know that it is a new object. The new object should be processed in the same way as in a synchronisation message. When not all required fields are specified, the object may be discarded.

	{
		"evses": [
			{
				"evse_id": "BE-BEC-E041503003",
				"location_id": "LOC1",

				"status": "AVAILABLE",
				"capabilities": ["RESERVABLE"],

				"connectors": [
					{
						"id": "1",
						"type": "sType2",
						"price_schemes": PRICINGSCHEMES
					}
				],
				
				"physical_number": 3,
				"floor": -1,
				
				"valid_from": "2015-05-21T10:00:00+0200"
			}
		]
	}

#### Example: delete an EVSE

An EVSE can be deleted by updating its *valid_until* property.

	{
		"evses": [
			{
				"id": "BE-BEC-E041503001",
				"valid_until": "2015-04-27T13:00:00+0200"
			}
		]
	}

**Comment by simonphilips** [comment]
I encountered a problem with *Location.opening_hours*. In the current draft it is mentioned as an "RRULE". However, an RRULE does not have a duration (it is only a part of the iCalendar format), i.e. we would only know when the opening hours start but not when they end. So we would have to switch to a full iCalendar message. I wonder if that is not adding too much complexity? Shouldn't the human readable variant *Location.opening_description* suffice?

**Comment by simonphilips** [comment]
In the meeting we said that all prices must be listing prices. I don't think this is necessary and in fact rather limiting. Since both CPO and eMSP communicate with each other, we know who receives the message and can change the prices accordingly. If you want, you can still send list prices, but it should not be a requirement to do so.

**Comment by cristinarc** [comment]
As discussed in today's meeting: 
1. The opening hours will be expressed in local time and based on OCHP, https://github.com/e-clearing-net/OCHP/blob/master/OCHP.md, but using JSON format.
2. The pricing scheme should be able to be specified for 'all' or the specific eMSP. Therefore two different pricing schemes could be sent: [(1, default pricing scheme), (0, pricing scheme between the CPO and the eMSP)]
3. The schema will look as it is specified on OCPP2.0 for now: http://www.openchargealliance.org/sites/default/files/OCPP%202.0%20Release%20Candidate%202.pdf page 212 (chapter 10.6)

**Comment by EGBarten** [comment]
We have a big problem with the Location proposal. It means we have to rewrite our code (both ocpi interface implementation and mobile app) and have to introduce an entity which has no meaning for us. So I would suggest that an EVSE can have a location OR an own address.

**Comment by EV-Box** [comment]
This is the exact conclusion we had aswell 2 weeks ago. I believe this is
the case for all of our Dutch partners.

I sincerely suggest we use the proposed alternative by Cristina.

Kind regards,
Deniz Kayapinar

Op woensdag 27 mei 2015 heeft EGBarten <notifications@github.com> het
volgende geschreven:

> We have a big problem with the Location proposal. It means we have to
> rewrite our code (both ocpi interface implementation and mobile app) and
> have to introduce an entity which has no meaning for us. So I would suggest
> that an EVSE can have a location OR an own address.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocpi/ocpi/issues/23#issuecomment-105912072>.
>


-- 
Verzonden via iPhone

**Comment by simonphilips** [comment]
This is not an issue, as discussed in the meeting about a month ago. Suppose you have no location concept in your database and you have the following EVSE's:

    {
        id: "EVSE1",
        address: "Dam",
        city: "Amsterdam",
        country: "NL",


        "status": "AVAILABLE",
        "capabilities": ["RESERVABLE"],

        "connectors": [
            {
                "id": "1",
                "type": "cType2",
                "price_schemes": PRICINGSCHEMES
            },
            {
                "id": "2",
                "type": "sType2",
                "price_schemes": PRICINGSCHEMES
            }
        ],
    }


    {
        id: EVSE2,
        address: "Dam",
        city: "Amsterdam",
        country: "NL",


        "status": "AVAILABLE",
        "capabilities": ["RESERVABLE"],

        "connectors": [
            {
                "id": "1",
                "type": "cType2",
                "price_schemes": PRICINGSCHEMES
            },
            {
                "id": "2",
                "type": "sType2",
                "price_schemes": PRICINGSCHEMES
            }
        ],
    }


    {
        id: EVSE3,
        address: "Wetstraat 6",
        city: "Brussel",
        country: "BE",


        "status": "AVAILABLE",
        "capabilities": ["RESERVABLE"],

        "connectors": [
            {
                "id": "1",
                "type": "cType2",
                "price_schemes": PRICINGSCHEMES
            }
        ],
    }


Then you can easily map that in the protocol without having to store any location objects whatsoever:

    {
        locations: [
            {
                id: EVSE1, // Simply use your EVSE id for each location!
                address: "Dam",
                city: "Amsterdam",
                country: "NL",
            },
            {
                id: EVSE2,
                address: "Dam",
                city: "Amsterdam",
                country: "NL",
            },
            {
                id: EVSE3,
                address: "Wetstraat 6",
                city: "Brussel",
                country: "BE",        
            }
        ],

        evses: [
            {
                id: "EVSE1",
                location_id: "EVSE1",


                "status": "AVAILABLE",
                "capabilities": ["RESERVABLE"],

                "connectors": [
                    {
                        "id": "1",
                        "type": "cType2",
                        "price_schemes": PRICINGSCHEMES
                    },
                    {
                        "id": "2",
                        "type": "sType2",
                        "price_schemes": PRICINGSCHEMES
                    }
                ],
            },
            {
                id: "EVSE2",
                location_id: "EVSE2",

                "status": "AVAILABLE",
                "capabilities": ["RESERVABLE"],

                "connectors": [
                    {
                        "id": "1",
                        "type": "cType2",
                        "price_schemes": PRICINGSCHEMES
                    },
                    {
                        "id": "2",
                        "type": "sType2",
                        "price_schemes": PRICINGSCHEMES
                    }
                ],
            },
            {
                id: EVSE3,
                location_id: "EVSE3",

                "status": "AVAILABLE",
                "capabilities": ["RESERVABLE"],

                "connectors": [
                    {
                        "id": "1",
                        "type": "cType2",
                        "price_schemes": PRICINGSCHEMES
                    }
                ],
            }
        ]
    }

In other words, you do not need the location concept internally. Just split your "big" evse objects into a location part and a evse part and use the same ID for both. The way you transmit data through the protocol and the way you store and process data do not have to be the same! Besides, sending and receiving raw database objects without any formatting/processing layer is a pretty bad practice.

However, the location concept is useful for those that do store it, because then they can tell you that EVSE1 and EVSE2 belong to the same location. It also reduces redundant information.

Allowing address information in the EVSE object just adds more complications and confusion for other parties, especially when your data can easily be split up (only while transmitting, not in your database/internal logic!) as mentioned above without any side effects.

(Note: I left out some optional fields in the example above, it's just to illustrate the point.)

**Comment by poohsen** [comment]
we briefly mentioned data reduction again as a goal today so I'd like to ask @all, because it's not clear to me: do we expect there to be android or iOS Apps made by MSPs in the future that will talk OCPI to operators directly? Or isn't it more likely that there will be an MSP backoffice that talks OCPI and an Android/iOS app that talks to it via a custom protocol?

**Comment by simonphilips** [comment]
No, OCPI is between charging operator and eMSP only, other applications should talk to their own backoffice system (which in turn can use OCPI to sync data with operators). They can use their own protocol, which can look similar to OCPI but doesn't have to be. That is beyond our scope.

I think as a charging operator you don't want thousands of queries from all kind of smartphone apps. Each application provider should be responsible for his own data/bandwidth.

The reduction of redundant data is always a good idea though, but it's not related to smartphones.

**Comment by EGBarten** [comment]
I agree with Simon.

Greetz,

Erwin Barten

senior programmeur

Movements Group - CODE44
T - 088 345 66 00
E - erwin.barten@movements.nl

2015-05-28 15:52 GMT+02:00 Simon Philips <notifications@github.com>:

**Comment by poohsen** [comment]
reduced redundancy of data is good but we're trading it for a more complex deserialization (as Erwin noted today) and we should motivate why the former is more important to us than the latter.
 
It seems to me like the synchronisation messages would still most intuitively be constructed as a list of location objects which _include_ a list of EVSEs, like it was in the latest version of the spec. Below I took the example message from the spec and changed the list of connectors to a list of EVSEs according to the discussion 4 weeks ago and which I also wrote up in #19 (this was brought up by Erwin today and I regret that I dismissed his concern there and then):

```
[
{
    "authorization_type": ...,
    "availability": ...,
    "evses": [
        {
            "evse_id": "NL-ELA-0001",
            "status": "available",
            connectors: [
            {
              "capabilities": ["reservable", "charge_profile_capable"],
              "charge_protocol": "mode3",
              ....
              "price_schemes": ... ,            
              "type": "ctype2"
           }
        }
    ],
    "identifier": "CHARGE_LOCATION_001",
    "location": {
        "address": "De Waag 6",
        "city": "Amersfoort",
        "country": "Nederland",
        "display_text": ...,
        "point": [
            5.3952443,
            52.1850078
        ],
        "postal_code": "3823 GE"
    },
 ...
 }
]
```

I assume one location can have one or more EVSEs but one EVSE cannot belong to more than one location. The "location" field specifying the address and/or coordinates is only obligatory on the top-level object (which represents the charging location). It is optional on the EVSEs. IMO, this already gets rid of any redundancy. In the regular case, there won't be any location information on the EVSEs in this message.  Since this issue proposes to diverge from this structure, we should give clear reasons for this.

Note that this comment only concerns synchronisation messages. The proposed structure for update messages is fine, IMO. As location and evse objects have unique IDs, the updates should be easy enough for an MSP to merge into existing data.

(I'm aware that I'm coming back to the same topic yet again but if nothing else, this comment can quickly be dismissed with good reasons and provide background reading for other interested parties in the future)

**Comment by simonphilips** [comment]
The idea is to have the update and synchronisation messages in the same format so that creating and parsing them works in pretty much the same way. It adds consistency which makes it simpler to understand.

**Comment by poohsen** [comment]
ok, I see. I'll re-evaluate the aspect of creating&parsing once we implement that proposal to see if the price of consistency is not too high

**Comment by simonphilips** [comment]
Perhaps an alternative is to send the list of locations and EVSE's as a map instead of an array.

The original structure:

    {
         "locations": [
             location_object1, 
             location_object2, 
             ... 
         ],
         "evses": [
             evse_object1,
             evse_object2,
              ...
         ]
    }

would then look like:

    {
         "locations": {
             location_id1: location_object1,
             location_id2: location_object2,
             ...
         },
         "evses": {
             evse_id1: evse_object1,
             evse_id2: evse_object2,
             ...
         }
    }   

So when processing an EVSE object, you can quickly fetch the relevant location by locations[evse.location_id]. This structure is possible because the location_id is unique per location anyway, although from a semantic point of view a normal array would be more correct (and more compact).

On the other hand, nothing is stopping the implementer from turning the original list of locations into a hashmap himself. In Python it would be just one line of code anyway for example.

    location_map = {location.id: location for location in location_array}

And then proceed to loop over all the evse's:

    for evse in evse_list:
        location = location_map[evse.location_id]
        ...

**Comment by poohsen** [comment]
there the implementation is leaking into the message structure too much, IYAM.

I also wonder why the EVSE is specifying which location it belongs to, while we could just as well have the location specify a list of EVSE IDs that belong to it. Any reason for that?

**Comment by simonphilips** [comment]
Yeah I agree that lists are better than maps in this case.

As for having the EVSE point to the Location object: it adds more consistency with the update messages, and it enforces the requirement that each EVSE belongs to a Location (in the protocol). 

It's also better to have an "atomic number" field than a "dynamic list of numbers" field because the latter is more annoying to update: "does this list only contain the new EVSE's or all the existing ones? How do you communicate that an EVSE is removed from a location?" This is more relevant in the update messages than in the sync messages but it's still a complexity that can easily be avoided by having the EVSE point to the Location instead.

**Comment by EGBarten** [comment]
Good work, now we have nice stucture in the message. A location with a
evse-id list would be perfect for us.


Erwin Barten

senior programmeur

Movements Group - CODE44
T - 088 345 66 00
E - erwin.barten@movements.nl

2015-05-29 13:32 GMT+02:00 Simon Philips <notifications@github.com>:

**Comment by poohsen** [comment]
@EGBarten I'm still trying to understand the pros and contras here
@simonphilips re consistency: locations linking to evses would work for update messages just as well. The list would contain the currently existing EVSEs:

```
{
    "locations": [
        {
            "id": "LOC1",
            "evses": ["EVSE1", "EVSE2"]
        }
    ]
}
```

looking at it from an OO perspective, I'd say that creating that list is trivial when serializing to a message such as the one above.

I'd argue that both, your way and this way work but this is more "top-down" and therefore more intuitive

**Comment by simonphilips** [comment]
Hm, I see some small complications, consider this:

**Scenario 1:** Adding a new EVSE to an existing location

* Updated objects in the top-down approach:
    1. the location object with an updated list of EVSE IDs
    2. the information about the new EVSE.
* Updated objects in the bottom-up approach:
    1. the new EVSE containing the location id of an existing location

**Scenario 2:** Moving an EVSE to another location

* Updated objects in the top-down approach:
    1. old location with the EVSE removed from its EVSE ID list
    2. new location with the EVSE added to its EVSE ID list
* Updated objects in the bottom-up approach:
    1. the EVSE containing an updated location id

In both cases, the bottom-up approach results in smaller and simpler messages. Also the order in which you process the locations in Scenario 2 may result in strange behaviour: what if the new location appears before the old location? Or do we simply not sent the updated old location when moving an EVSE? If we do that, then we can alter an entity by updating another unrelated entity. It just feels a bit dirty. I prefer explicit updates rather than implicit updates.

Of course, those are scenario's that are not very common in comparison to normal status updates. It's just something to consider. I'm not necessarily against the top-down approach but I think the bottom-up approach is more coherent and simpler by design as it avoids all these questions by not raising them in the first place. What do you think?

**Comment by cristinarc** [comment]
Might be a bit late to comment this out, but as I am taking this into the new documents I am creating I went through the comments. Here my comments:

I would opt for using the different lists option. In a way the 'location' is not more than a parameter of an evse. The evse name is as important as the location of the evse. If we try to look at it as it was just the 'address' we can easily understand it with the 2 lists structure:

{
    "locations": Location["Kinkerstraat", "Harleemstraat"],
    "evses": EVSE[
    	{"id": "1", "location": "Kinkerstraat"},
    	{"id": "2", "location": "Kinkerstraat"},
    ]
}

If 5 minutes after getting the static data, the evse 2 changes location, it would just imply updating the 'location':

{
    "evses": EVSE[
    	{"id": "2", "location": "Harleemstraat"},
    ]
}

Otherwise would become more confusing, by my point of view, with no specific advantages, since, most likely, the Locations and the EVSEs will be stored separately in the Data Base.

The advantages, as Simon said before, are that the EVSE is more decoupled of the location and gives us more freedom when updating the location of an EVSE, which can happen pretty frequently. If we compare this with the connectors e.g., they are not being taken out of the EVSE, because there is a dependency between each other that can not just disappear. If the connector is not sent, it's because it does not exist any more, but will never moved to a different EVSE.

Might there be added complexity that I am not able to see now, I hope we can find it when doing the implementation and being able to update this on the fly if required.

With regard to what you said Erwin, we don't have EVSEs still in our systems as entities neither (but in Charge Points), but we would prefer not to condition the specs with the implementation we have in our systems, since at the end, we will have to move to the EVSEs structure as well. OCPI could be taken as a perfect opportunity to update our models to what the market is moving us towards to.

**Comment by simonphilips** [comment]
> the EVSE is more decoupled of the location and gives us more freedom when updating the location of an EVSE, which can happen pretty frequently. If we compare this with the connectors e.g., they are not being taken out of the EVSE, because there is a dependency between each other that can not just disappear. If the connector is not sent, it's because it does not exist any more, but will never moved to a different EVSE.

Well put! There is a difference between the EVSE<>Location relationship and the connector<>EVSE relationship. The list of connectors is an inherent (atomic) characteristic of the EVSE, but the list of EVSEs is not a defining characteristic of the location (because it can change easily). It's a bit of an abstract concept which I find hard to communicate, but you explained it really well.

**Comment by RobertdeLeeuw-IHomer** [comment]
no longer relevant
