### ISSUE TITLE
No geodetic system specified on GeoLocation

### ISSUE THREAD

**Issue by reger** [ocpi/ocpi#230]
It's stated as WGS 84 for `AdditionalGeoLocation`, but not on `GeoLocation`. I would imagine it's the same, but would be good to explicitly state it in the docs for clarity.

**Comment by RobertdeLeeuw-IHomer** [comment]
@reger Good find, thanks for notifying us. 
I will add this to the 2.2 development branch so it becomes part of 2.2.
And also do the 2.1.1 bug fix branch!
