### ISSUE TITLE
Tariff and Location documentation contradictory

### ISSUE THREAD

**Issue by KevBelisle** [ocpi/ocpi#232]
In this tariff example : https://github.com/ocpi/ocpi/blob/develop/mod_tariffs.asciidoc#tariff-example-025-euro-per-kwh--start-fee--max-price--tariff-end-date

It says the following :
> This tariff has an end date: 30 June 2019, which is typically used when a tariff is going to be replaced by a new tariff. A **Connector of a Location can have multiple Tariffs (IDs) assigned. By assigning both, the old and the new tariff ID, they will automatically be replaced.** It is not required to update all Locations at the same time, the old tariff can also be removed later.

However, the Connector documentation states the following for tariff_id :
> Identifiers of the currently valid charging tariffs. Multiple tariffs are possible, **but each requires a unique Tariff.type**. Duplicates are not allowed.

_Emphasis mine._

**Comment by RobertdeLeeuw-IHomer** [comment]
I will look into this
