### ISSUE TITLE
Dealing with privately owned chargepoints and other CPO's / eMSP's

### ISSUE THREAD

**Issue by SvenLahmann** [ocpi/ocpi#233]
Hello,

We are using OCPI for both our eMSP and CPO role and haven't yet found a solution for the following issue, the locations module (or any other?) does not seem to support a way to set/identify whether a chargepoint is privately owned and thus if it can or cannot be shown in third party Apps. 

For our own App, we deal with this because we know for our own chargepoints if our customers want them to be shown as publicly available. For other eMSPs, who retrieve our chargepoints via a GET locations, we don't seem to have any way to let them know these cannot be shown in public. Yet, we still need to know them these locations exists, otherwise we cannot send them the CDRs for sessions at these chargepoints.

Is there a way to deal with this issue? Many thanks in advance.
GR

**Comment by jirouette** [comment]
Hello, 

If these chargepoints are private, why would a user from a third-party eMSP would start a session there ?

**Comment by SvenLahmann** [comment]
Hi,
Thanks for your quick reply. The situation arises when we have people owning our chargepoint, but have a contract with a chargecard supplier elsewhere (regrettably, and they wish to use these cards to charge.

**Comment by mbayings** [comment]
This is indeed happening more. The system for my charger that I use offers the possibility to set a setting 'roaming not showing on map'. The stations with this setting are not sent to the NSPs, only to the MSP's. I know that we also discussed this for V3.0 to add it to OCPI but can't remember the conclusions. Also not sure why we did not add it to v2.2. In my opinion a good additional property.

This is also applicable for private situations where you do want friends and family to charge at your station, but at their cost or via their own lease company. So you want it open for roaming but not visible on all kind of maps.

**Comment by RobertdeLeeuw-IHomer** [comment]
In OCPI 2.2, the Location does not need to be known to the MSP to send a CDR. The CDR itself contains a `CdrLocation` object. Which is a limited version of the `Location` object from the Location module. So I hope this will not be an issue anymore with OCPI 2.2.
See: https://github.com/ocpi/ocpi/blob/develop/mod_cdrs.asciidoc#131-cdr-object

But for OCPI 2.1.1 it is not that clear.
My proposal:
- Only send this Location to the MSP that needs to receive the CDR only.
- Set the EVSE.status to: `REMOVED`. That way it should show on any app of that MSP.

**Comment by mbayings** [comment]
So that means that for ensuring that a private location is not sent to everyone, the CPO system itself should have this switch/checkbox in their system so that owners can indicate if they want it published. And if they do not indicate it, the CPO system should internal manage that these locations are not distributed. Right? This is also how the system is working that I currently use which is from EV Box. I consider this as a great feature.

**Comment by RobertdeLeeuw-IHomer** [comment]
Yes, this is something the CPO has to solve. And it is also something a CPO can implement to stand out abode the crowd.

I don't think we should give this like something that could be configured via OCPI by the MSP?

**Comment by RobertdeLeeuw-IHomer** [comment]
Added some notes to explain this to OCPI 2.2

**Comment by SvenLahmann** [comment]
Thanks again for the replies!
So if I understand correctly, from OCPP 2.2 onwards, your proposed solution if to allow for CDRs being sent to MSPs without them having the location registered?

I think, unfortunately, the solutions offered for the as is situation won't help us.

> Only send this Location to the MSP that needs to receive the CDR only.

This can still be an MSP that is not us, who may publish our location? I suppose we could mitigate  some by doing something with only sending location information to MSPs for which we know a (list of) chargecard(s) is allowed to charge, but this may still be a party who we don't want to be showing the chargepoint publicly.  

> Set the EVSE.status to: REMOVED. That way it should show on any app of that MSP.

As we are currently only the administrative CPO, and rely on active EVSEs for our communication with the technical CPO as well as in other logic, I don't see how we could use this option. Or maybe we could keep a different for our internal communication with the technical CPO. We'll think about it!

**Comment by mbayings** [comment]
In your contract with the MSPs you can agree that the MSP is not allowed to publish certain locations. In the case of my operator, it is clear as I mentioned in the portal I use from the CPO to manage my charge station that is should not be published. The CPO should manage this in the contract with their MSPs.

**Comment by SvenLahmann** [comment]
Right, understood, thanks!

**Comment by RobertdeLeeuw-IHomer** [comment]
@SvenLahmann OCPI was designed for CPO to eMSP communication. But the market is evolving. So with 2.2 we are already introducing more and more new roles. But the Technical CPO to Administrative CPO communication has not been taking into account for 2.2. That is on the list for 3.0.

**Comment by kormeelker** [comment]
Reading the above thread, it is a possible route to handle this. But a lot of implicit actions are hidden in here. And even if you have covered this in the contracts, it is very hard to enforce this via the current interface. 
There should be a more explicit way of telling the MSPs what they are allowed to do with publishing of the location information. This is something to take along with 3.0.

**Comment by RobertdeLeeuw-IHomer** [comment]
@kormeelker is there a problem with what is in 2.2? 
Why would you publish a location to an MSP/NSP if you don't want them to publish it on there apps/web sites?

**Comment by kormeelker** [comment]
@RobertdeLeeuw-IHomer This is the case when a private charger needs to be controlled by a MSP App. We have that case for one of our customers, that wants to have the private home-charger visible for the driver (home owner) only in the MSP-app to start/stop sessions. And we also getting requests in to make chargers visible for a selected group of ev-drivers. This is the case with office chargers that should not be visible on every map, but only to the group of employees.

**Comment by RobertdeLeeuw-IHomer** [comment]
Good one: being able to control your home/office charger via the app of your MSP. But not making it available to the public.

Which party determines which Location is then shown to what group/individual? Is that CPO or the MSP?

**Comment by kormeelker** [comment]
Currently that is determined by the CPO. He is the one that installs and operates the home-charger and informs the MSP, that handles the EVCO, about this.

**Comment by RobertdeLeeuw-IHomer** [comment]
So the CPO determines which drivers might see the Charge Point?

**Comment by kormeelker** [comment]
Currently with this business case, yes.

**Comment by mbayings** [comment]
With the EV Box backend the owner of the charger can decide this and change it. Not the CPO. And the owner should also be in control. They might delegate it to the CPO for execution, but the owner is the one who should decide this.

**Comment by kormeelker** [comment]
In my case the owner is the fleet manager, that leases the car from a lease company and controls the behavior of the charger that is installed at the home of the lease driver. And we as a CPO have to perform the execution of the whole process, including informing the MSP-partner about the installation and charge card.

**Comment by RobertdeLeeuw-IHomer** [comment]
For OCPI, in both cased that will mean that the CPO will need to tell the MSP which Drivers are allowed to see and use a Location/EVSE. 
How can we do that? Add a list of Tokens.uid or Token.contract.id or even a list of Tokens to a Location or EVSE. So the MSP knowns which driver (in OCPI a Token) is allowed to use a Location.  An App will in most cases use an APP_USER type of Token. 
How can the CPO determine which Token belongs to which driver?
Does somebody have an idea for a solution?

**Comment by mbayings** [comment]
Maybe via the other way. At CPO system level you switch it of for visibility, but via the MSP app in one way or the other you can still request access to the CPO system, who then need to approve it. Something like that? 
We must be carefull that we focuss to much on exceptions. It should also not be dramatic if you only have the option: external visible Yes/No. Even in case of NO you can still see the transactions and sessions as it can still be open for roaming.

**Comment by RobertdeLeeuw-IHomer** [comment]
Question is, if this is an corner case. 
Is being able to use your MSPs app to start your home charger a corner case?
How many driver use the MSP app to start charging at home? I dont know, I guess not so many. 

You can still see the Session information, so you get status updates of the session.
Based on the session you can stop the charging.
You will still see the CDR.
I guess that most CPOs (or Charge Point manufacturer) have their own app that you can use to start the Charging Session of your home charger, MSP not needed?

Changes to 2.2 should be simple to implement. This does not seem that simple (at least, I cannot think of a simple solution) So then it can be on the list for 3.0.

**Comment by mbayings** [comment]
Hi Rbert, that is indeed what happens in most situations. Also because using the app from your own CPO is often the cheapest as using any system where external roaming and billing is involved will in almost alll cases result in more cost - either transaction or roaming fees. Although I can imagine that a BMW driver wants to use the BMW app and not the app from the CPO. But then indeed it will be more expensive.

**Comment by ahzf** [comment]
It is not a corner case, but a fundermental feature if you want to enable automatic continous integration tests of the charging infrastructure. I operate a couple of pure virtual charging stations for customers which do nothing but to test automagically if everything is running normally and fast enough - which is surisingly often not the case. Of course these charging stations should not be shown to normal endusers, but it should be able to make use of them in every app when you enter a correct EVSE/charging station id or know how to enable some sort of "debug mode" of the app.

**Comment by mbayings** [comment]
For testing purposes I totally agree with Achim. Question is if this requires a change in OCPI or if we can deal with this in test tools.

**Comment by Namoshek** [comment]
Test stations can already be declared as such, giving eMSPs the opportunity to mark them as unaccessible or not display them at all. Or am I missing something?

**Comment by ahzf** [comment]
You want to be as close at the "normal" product as possible.

**Comment by RobertdeLeeuw-IHomer** [comment]
@ahzf Is using the status: `REMOVED` for such a test case not an option? If not, what do you propose?
