### ISSUE TITLE
Question regarding InterfaceRole

### ISSUE THREAD

**Issue by labtrax** [ocpi/ocpi#234]
Hey there,

in V22
https://ocpi-protocol.org/app/uploads/2019/06/OCPI-2.2-RC2.pdf (I guess that is the most latest)
at chapter 6.2 InterfaceRole is an enum either SENDER or RECEIVER but in the examples it is "role": "CPO" or "role": "MSP".
Am I getting it wrong or is this wrong? From my understanding it should be SENDER or RECEIVER, shouldn't it?

Thanks
Malte

**Comment by RobertdeLeeuw-IHomer** [comment]
Correct, thanks for this report.
We are setting up a new way to build the specification. The will also generate Swagger/OpenAPI files. These are then used to validate the examples. So these kind of mistakes should hopefully be solved then. 

I have fixed this one manually.
