### ISSUE TITLE
Module ID ambiguity

### ISSUE THREAD

**Issue by onury** [ocpi/ocpi#235]
The ID of Charging Profiles module is defined as `charging_profiles` in [module definition](https://github.com/ocpi/ocpi/blob/develop/mod_charging_profiles.asciidoc) but it's defined as `chargingprofiles` (no underscore) in [version information document](https://github.com/ocpi/ocpi/blob/develop/version_information_endpoint.asciidoc) (within moduleID enum table).

I think `chargingprofiles` (no underscore) should be used for consistency with other module IDs.

**Comment by RobertdeLeeuw-IHomer** [comment]
Thanx
