### ISSUE TITLE
Fix example regex for RegularHours periods

### ISSUE THREAD

**Issue by onury** [ocpi/ocpi#237]
For `period_begin` and `period_end` fields of `RegularHours` class, the example regex for **24h format** is given as:
```js
[0-2][0-9]:[0-5][0-9]
```
But this will incorrectly match strings such as: `29:00`, `28:00`, etc..

Below is the correction for proper **24h format**:
```js
([0-1][0-9]|2[1-3]):[0-5][0-9]
```

**Comment by RobertdeLeeuw-IHomer** [comment]
Thanks for the nice improvement.
Could you change the pull request to the bug fix branch: release-2.1.1-bugfixes?

See: https://github.com/ocpi/ocpi/blob/master/CONTRIBUTING.md

**Comment by RobertdeLeeuw-IHomer** [comment]
While you are improving this one, could you also update: TariffRestrictions.start_time?
It uses the same regex

**Comment by onury** [comment]
Sure. Will update shortly.

**Comment by onury** [comment]
@RobertdeLeeuw-IHomer 

> Could you change the pull request to the bug fix branch: release-2.1.1-bugfixes?

It seems you've changed the branch already.

Sent #239 to fix `TariffRestrictions.start_time`

**Comment by RobertdeLeeuw-IHomer** [comment]
I will also merge this change to 2.2 development
