### ISSUE TITLE
start and end time fields have different spellings on cdrs and sessions

### ISSUE THREAD

**Issue by evjan** [ocpi/ocpi#240]
Hi,

I just noticed that on [CDRs](https://github.com/ocpi/ocpi/blob/master/mod_cdrs.md#31-cdr-object) the start and end time fields are called `start_date_time` and `stop_date_time`. But on [sessions](https://github.com/ocpi/ocpi/blob/master/mod_sessions.md#41-sessionstatus-enum) they're called `start_datetime` and `end_datetime`.

So in the former case the word 'stop' is used and the latter it's 'end'. Plus the last underscore is omitted in the sessions.

Is that intentional?

**Comment by RobertdeLeeuw-IHomer** [comment]
@evjan , we have also seen this. We have fixed this in 2.2.
