### ISSUE TITLE
Contradictory Versions Info description/example

### ISSUE THREAD

**Issue by adamstaveley** [ocpi/ocpi#245]
The example given in 4.1.6.1 seems to be contradictory with the versions description in 6.1. Based on this description I would expect `data` to have a single property, `versions`, which has type `Version`. Instead, the example given in 4.1.6.1 states that `data` is of type `Version`. 

Either 6.1 is correct, therefore 4.1.6.1 should be changed to:
```json
{
  "data": {
    "versions": [{
      "version": "2.1.1",
      "url": "https://example.com/ocpi/cpo/2.1.1/"
    }, {
      "version": "2.2",
      "url": "https://example.com/ocpi/cpo/2.2/"
    }],
  },
  "status_code": 1000,
  "status_message": "Success",
  "timestamp": "2015-06-30T21:59:59Z"
}
```

Or 6.1.1 should be changed to:

| Type | Card | Description |
|--------|--------|-----------------|
|Version|+|A list of suppported OCPI versions|

**Comment by RobertdeLeeuw-IHomer** [comment]
You are correct.
I think that 6.1.1 is not correct. If you look at the definitions of other definitions of GET on other modules, you will see that they define Response Data differently.
See for example: 12.2.2.1. GET Method of Tokens.

Can you create a pull-request on the 2.2 bugfix branch for this? https://github.com/ocpi/ocpi/tree/release-2.2-bugfixes
