### ISSUE TITLE
Change operator code EVnetNL (E-laad) from ELA to EVN

### ISSUE THREAD

**Issue by rutgerplantenga** [ocpi/ocpi#25]
There's a request from Bram van Eijsden from EVnetNL (formerly: E-laad) to change their operator code from ELA to EVN.

**Comment by LeonHuijsdens** [comment]
Are operator codes part of the protocol specification?  I would keep them in a separate list.

**Comment by rutgerplantenga** [comment]
Apparently so. But I agree that this should be separated. Or actually...
ideally it would not be necessary to maintain such lists centrally.


*Rutger Plantenga*
+316 2907 6069

Keizersgracht 585
1017 DR Amsterdam

Postbus 3966
1001 AT Amsterdam

**Comment by poohsen** [comment]
The list is in the ocpi repo but not in the specification document. The file is called registry.md

**Comment by simonschllng** [comment]
Which one is the leading list? I thought the public one on http://www.eviolin.nl/index.php/leden/ is relevant.

**Comment by rutgerplantenga** [comment]
For Dutch id's... yes, that is the leading list.


*Rutger Plantenga*
+316 2907 6069

Keizersgracht 585
1017 DR Amsterdam

Postbus 3966
1001 AT Amsterdam

**Comment by RobertdeLeeuw-IHomer** [comment]
no longer relevant
