### ISSUE TITLE
Incorrect `country_id`  code in examples

### ISSUE THREAD

**Issue by Jufik** [ocpi/ocpi#253]
Documentation specifies `ISO-3166 alpha-2` for country reference.
Looks like `ISO 3166-1 alpha-3` is being used in provided examples.

**Comment by jirouette** [comment]
I'm not sure where alpha-3 is being used instead of alpha-2 ? I've quickly checked the examples where alpha-2 is mentioned, it looks good to me

Some country fields are in alpha-3, though (such as `CdrLocation.country` and `Location.country`), but it is specified

**Comment by RobertdeLeeuw-IHomer** [comment]
@Jufik could you point the the incorrect examples you think you have found?

**Comment by Jufik** [comment]
Nevermind, I've over read specs details: 
Looking country_id used in path or Token modules, I took a shortcut and concluded the whole spec uses alpha-2

Looking at ressources specificites, it - indeed - uses alpha-3 codes.
