### ISSUE TITLE
Fix regex for RegularHours periods (issue with solution #237) in 2.1.1.

### ISSUE THREAD

**Issue by Broeck92** [ocpi/ocpi#258]
For period_begin and period_end fields of RegularHours class, the example regex for 24h format is given as:
([0-1][0-9]|2[1-3]):[0-5][0-9]

This format does not allow 20:00

Below is the correction:
([0-1][0-9]|2[0-3]):[0-5][0-9]

**Comment by RobertdeLeeuw-IHomer** [comment]
@Broeck92 You are right, keen eye!!
Can you create a pull request on the 2.1.1 bugfix branch?

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed
