### ISSUE TITLE
Over tariff have the transaction fee of two types: 1. flat 2. percentage.

### ISSUE THREAD

**Issue by ajaysharmamca** [ocpi/ocpi#262]
This question is regarding: 2.1.1 implementation.
On the tariff flat $1 can be applied as shown below.
				"price_components": [
                    {
                        "type": "FLAT",
                        "price": 1,
                        "step_size": 0
                    }
                ] 

On the tariff of $50, 2% will be added.
How can show this type of tariff: As there are ENERGY, FLAT, PARKING_TIME, TIME type for the component.

**Comment by RobertdeLeeuw-IHomer** [comment]
It is not possible to add 2% as some form of usage fee. Then you need to incease the price by 2%
