### ISSUE TITLE
Power Level in W, kW or both?

### ISSUE THREAD

**Issue by buti1021** [ocpi/ocpi#264]
Hey,

I am not 100% sure in which unit the power level should be? According to the docu it is W, but in the given example in the explanation it is kW, is this only to make the example better readable? Can I expect the power level to be always given in W?

https://github.com/ocpi/ocpi/blob/master/mod_locations.asciidoc#133-connector-object

Thanks!

**Comment by RobertdeLeeuw-IHomer** [comment]
It should be in W. I have add a bit to explain this better

**Comment by buti1021** [comment]
Thank you so much for your fast clarification!
