### ISSUE TITLE
How to respond on eMSP location PUT/PATCH requests in case of an error?

### ISSUE THREAD

**Issue by GoeHa** [ocpi/ocpi#269]
A question regarding HTTP response codes of erroneous requests or if some errors occurs while processing these requests makes me wondering which would be expected behavior related to OCPI 2.1.1.

If, for example, a CPO calls an eMSP on the locations PUT interface and has a mismatch between the evse_uid in the URL and the evse_uid in the body of the evse-object, then the specification recommends (according to chapter 3.1.4.1 Errors) to respond with 2001, "Invalid or missing parameters".
But what would the correct response be?
- HTTP 200 as the request is ok, JSON is valid and the resource exists or not (well, it's just an URL)?
- HTTP 400 due to malformed syntax/wrong uid with body 2001 invalid evse_uid

Another example, if while processing this PUT (or the PATCH) request, an internal error occurs, what response would be expected?
- HTTP 200 with some 3000 Generic server error 
- HTTP 500 Internal Server Error with some 3000 status code in the body

The confusion is based on:

Chapter 3.1.5 Response format says:
When a request cannot be accepted, an HTTP error response code is expected including a JSON object that contains more details. HTTP status codes are described on http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html.

Does HTTP error response code mean in this context 4xx/5xx or just 2xx and the response body as described in this chapter containing OCPI status code 2xxx/3xxx depending on client or server error.

And on the other hand Chapter 4 Status codes says
[...] If a request is syntactically valid JSON and addresses an existing resource, no HTTP error should be returned.

Would that mean HTTP 200 in any case if the request passes the HTTP Layer with success?
Because any JSON is accepted due to the Accept-Header.

What would the expected response be if the JSON is valid but has nothing to do with OCPI:
- HTTP 200 with some 2001 Invalid or missing parameters
- HTTP 400 with some 2001 Invalid or missing parameters

**Comment by RobertdeLeeuw-IHomer** [comment]
I would always advice to use HTTP errors for issues on the transport layer, things like 404 not found or 401 Not Authorized

So in your examples:
1: HTTP 200 as the request is ok, JSON is valid and the resource exists, will be created. But the content, evse_uid does not match the URL

2: If the HTTP server cannot get a response from the application layer: HTTP 500, if the Application internally has an error, but is able to respond to the HTTP Server: HTTP 200 with a 3000 range error code

I agree that the sentence: "When a request cannot be accepted, an HTTP error response code is expected... "  is a bit confusing, I will make a note that we should improve this.

**Comment by GoeHa** [comment]
I just recognized your answer. Thank you very much, also for possible improvements.
