### ISSUE TITLE
Tariff information in multiple sources

### ISSUE THREAD

**Issue by matthew-shiftleft** [ocpi/ocpi#273]
The locations module has a tariff_id under the connector. The CDR has a tariff_id in both the location section and the tariffs sections. If we get a CDR with conflicting information i.e. the location has tariff 1, the CDR location has tariff 2 and the CDR tariffs has tariff 3 which tariff shall we use for calculating the CPO price in our system?

**Comment by RobertdeLeeuw-IHomer** [comment]
It was a bit confusing in OCPI 2.1(.1), look at OCPI 2.2. the CDR only contains the CdrLocation, no longer the full location object. So it does no longer contain the tariff_id on the connector.
For checking the CDR, use the tariffs that are provided in the tariffs list in the CDR object itself.
If the location has a different tariff then provided in the CDR? Call the CPO. This can only happen if the tariff of a location has changed after charging has started. The Tariff of a location at the start of a transaction should be the same as the tariff in the CDR.

**Comment by matthew-shiftleft** [comment]
Thanks for a quick reply. I will check 2.2 but that sounds much better. We are on 2.1.1 right now so basically I should use the tariff id in the CDR and not the location (although they should match). We price based on the tariff active at the time of the start so if a change occurs during the session it will not affect the user. If, however, a CPO uses the tariff active at the time of the stop then they will of course send us incorrect information and it will affect our users.

**Comment by RobertdeLeeuw-IHomer** [comment]
Yes, I think in most countries the law requires the CPO to use the tariff that was active at the start of charging and not at the end of charging. So in almost all cases, using the tariff active at the end of charging is not allowed by law.
