### ISSUE TITLE
Documentation of TokenType 

### ISSUE THREAD

**Issue by buti1021** [ocpi/ocpi#274]
Hey,

is there any documentation describing the TokenType in the CdrTokenClass? The provided link (TokenType) at https://github.com/ocpi/ocpi/blob/master/mod_cdrs.asciidoc#145-cdrtoken-class doesn't seem to work.

Thanks!

**Comment by RobertdeLeeuw-IHomer** [comment]
somehow the link in github is not working. Please look at the PDF version. Link is working in the PDF: https://github.com/ocpi/ocpi/releases/download/2.2-d2/OCPI-2.2-d2.pdf

**Comment by buti1021** [comment]
Thank you very much @RobertdeLeeuw-IHomer!

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed

**Comment by buti1021** [comment]
Similar issue for GeoLocation at https://github.com/ocpi/ocpi/blob/master/mod_cdrs.asciidoc#144-cdrlocation-class

**Comment by RobertdeLeeuw-IHomer** [comment]
Thank you for reporting: fixed
