### ISSUE TITLE
Naming discrepancy between documentation and example

### ISSUE THREAD

**Issue by buti1021** [ocpi/ocpi#275]
According to the Documentation at https://github.com/ocpi/ocpi/blob/master/mod_cdrs.asciidoc#144-cdrlocation-class the name of the connector attributes is connector_... (e.g. connector_id). 
But according to the example at https://github.com/ocpi/ocpi/blob/master/examples/cdr_example.json the name is connector**S**_... (e.g. connectors_id). Which is the right name? 
The same issue applies for evse_uid and  and evses_uid (not for evse_uid though).

Best,

@buti1021

**Comment by RobertdeLeeuw-IHomer** [comment]
Thank you for reporting this!
