### ISSUE TITLE
Why there is a EVSE UId?

### ISSUE THREAD

**Issue by ahzf** [ocpi/ocpi#283]
I do not understand why there is some CPO-internal-additional-EVSE-identification in a public protocol. What is the use of it? I see only drawbacks as every other protocol just uses the standardized EVSE Ids.

Please remove this field.

**Comment by RobertdeLeeuw-IHomer** [comment]
We need a field to uniquely identify an EVSE within a CPO system. CPO's want to be able to rename/renumber/re-use the EVSE ID (eMI3 EVSE ID). By having the EVSE UID, we have an unique ID for an EVSE that will not change.

**Comment by ahzf** [comment]
Well, but for reusing an EVSE Id the same rules like for deleting a location apply: In general this in not a good idea!
The German calibration law identifies e.g. the public keys of energy meters by EVSE Ids. Price information might be depend on EVSE Ids. Therefore no one can simply remove or reuse those entities without breaking other processes.

**Comment by RobertdeLeeuw-IHomer** [comment]
I agree, I personally would never advice to reuse EVSE-IDs. 
But the majority of the group involved in the development of OCPI was strongly in favor of allowing/enabling this.

**Comment by simonschllng** [comment]
Old story discussed over and over again. We should finally define common rules for that. I do not see a roaming protocol do define these rules alone. If it is an industry-wide ruleset it would be easier to come to an implementation decision in the protocol level. As long as we do not have this, there will always be parties requesting such "features". Question here is how strict the group is.

**Comment by ahzf** [comment]
Well... @simonschllng within e-mobility you can easily lose all hope in the menkind ;) Also democratic voting on common rules need 51% people who know what this is all about. Too often we see a room full of management overhead and coffee cups requesting "simple", "easy", "fast" solutions... but we never see enough computer science people in a room solving the really hard issues. This is the first thing we have to solve.

**Comment by RobertdeLeeuw-IHomer** [comment]
@ahzf Please join the EV Roaming foundation so you an participate in the meeting in which we will define the next version of OCPI and thus also these kind of issues.

**Comment by ahzf** [comment]
Well... thank you very much for your invitation. Nevertheless you promised to all of us, that the OCPI contributor license agreement means something, that the development of OCPI is now and in the future really free and open for ALL. Now you added this management overhead and try to earn money via a closed "development group". **Sorry, I feel duped.** OCPI is now just another commercial product of one of the many ev cartels and I do not join any cartels, even when you are perhaps one of the smallest of all those cartels in e-mobility.

The EVRoaming Foundation seems to have its origins in this public funded EU project: https://www.evroaming4.eu
So as an absolut minimum you should strictly comply to the principle of "Public money, public code/specification."
And btw where do we, the tax payers, find all the (public) project results of https://www.evroaming4.eu ?

So please rethink how you want to design the community around OCPI. At the moment I only see that you became the exact copy of an organization that you wanted to abolish. We all know why OICP, OCHP, eMIP are all deadlocked. Why go into the same wrong direction with OCPI?

**Comment by mbayings** [comment]
@ahzf Sorry you feel duped. We know your thoughts on this. And we both know we will never agree. Which can happen. To be clear: OCPI will stay free to use and implement, incl discussions and some support. We never mentioned that participating in OCPI development will be at no cost for ever. That is simply not possible when you want to make it strong and sustainable. But it is open for everyone to join via the EVRoaming Foundation - but that comes with some cost. But again it is not a must. Even if you do not join, you can use it. The EVRoaming foundation is a non-profit foundation. However there are cost involved in developing protocols like OCPI. I am sure you also get money for things you do. 
We will not continue these discussions on OCPI Github nor Slack. But feel free to use OCPI and feel also free not to do it. You are also welcome to join the EVRoaming foundation if you really want to conctribute - not just for complaining. And yes, then there are some cost involved. But feel also free not to join the foundation.

**Comment by ahzf** [comment]
Well, please explain the Linux community, xBSD community, the IETF, the Microsoft .NET community, ... that their effort has no chance to be strong and sustainable ever ;) And they all have the problem to find the right way to finance their projects. But none of them ever charged their contributors. In most cases they pay their contributors especially when it comes to security and design issues.

And well... challenge accepted! If you look at GitHub you see all my contributions to OCPI and EV mobility in general, including an Open Source reference implementation of OCPI and there will be soon a specification how to solve the biggest OCPI flaws... let's call it "OCPI-Anwendungsregel" for the moment ;)

**Comment by poohsen** [comment]
Wouldn't it be possible to specify that the evse-ID is the primary identifier BUT it is to be ignored when the status is REMOVED? 
I always felt that the implementation (unique key in a DB) was leaking into the protocol design in this case.

As for not reusing the EVSE-ID: it is my understanding that assigning a new EVSE-ID to a chargepoint that's been refurbished is not an easy task. That's why CPOs have a strong preference for leaving it as is, even if the chargepoint changed hands and got installed in another location. (though I wonder what happens if it got installed in another country)
