### ISSUE TITLE
EVSE Id is optional in EVSE, but mandatory in CDRLocation.

### ISSUE THREAD

**Issue by ahzf** [ocpi/ocpi#286]
The EVSE Id is optional in its specification https://github.com/ocpi/ocpi/blob/release-2.2-bugfixes/mod_locations.asciidoc#mod_locations_evse_object but mandatory in the CDRLocation https://github.com/ocpi/ocpi/blob/release-2.2-bugfixes/mod_cdrs.asciidoc#mod_cdrs_cdr_location_class

**Comment by RobertdeLeeuw-IHomer** [comment]
A Location without EVSE can only exist when EVSE's have not yet been added or no longer exist at that location. But a CDR is the bill with total cost of charging. To be able to charge at a location, there needs to be an EVSE, so the EVSE Id can be required in the CdrLocation object.

**Comment by ahzf** [comment]
I'm not talking about EVSEs in general. I'm just talking about the "EVSEId" property of an EVSE having the "normal" eMI3 format,
