### ISSUE TITLE
Sending CDRs

### ISSUE THREAD

**Issue by ahzf** [ocpi/ocpi#287]
The specification for sending CDRs to EMPs seems to be unclear...

1.) What is the URL for the POST request?
Is it `https://www.server.com/ocpi/2.2/cdrs/` or `https://www.server.com/ocpi/2.2/cdr/CountryCode/PartyId` ?
Because I know of multiple people who accidentally implemented it the 2nd way, as it every other request also uses countryCode and partyId, but when reading the documentation it seems to be more the 1st way. In general it is not clear why a CDR is not send via a PUT request like all the other (client owned) objects.

2.) Within the response of a POST CDR there should be a `Location` parameter, but what means "The response should contain...". Are you talking about the well-known HTTP Location header, a JSON property within the general OCPI response header or even of an additional parameter within the CDR object which could be returned. Is the CDR anyway returned within the OCPI data property or is this empty? There seem to beno really complete specification about the POST response.

3.) "OCPI does not define a specific structure for this URL." What is the benefit of _not_ specifying the URL where a CPO can find his POSTed CDR? Sending CDRs is one of the most important features of any roaming protocol and we need excellent ways to verify, that every CDR was received correctly and we need also a way to verify, that ever CDR sent is still existing after a while. There are roaming networks and EMPs out there, which have from time to time issues with their database and then it happens, that some CDRs are lost during database recovery. Somehow we must dedect those issues automatically. Having to store an additional URL for every CDR sent seems really to be a very bad idea in my eyes. What is the problem to just define, that every CDR should be addressable via its CDRId like `~/ocpi/2.2/cdrs/cdrId`?

**Comment by RobertdeLeeuw-IHomer** [comment]
@ahzf could you please post 3 issues if you have 3 questions? I prefer to keep issues separate to make tracking easier.
