### ISSUE TITLE
Step size rounding example

### ISSUE THREAD

**Issue by ThomasHidrot** [ocpi/ocpi#289]
Hi,

I don't understand why the step size of 10 minutes rounds 40 minutes to 45 minutes total in the following example:
(https://github.com/ocpi/ocpi/blob/master/mod_cdrs.asciidoc)

"In the cases that TIME and PARKING_TIME Tariff Elements are both used, the total duration is used for the step_size Example:
Charging cost 1.00 euro/hour, parking 2.00 euro/hour both have a step_size of 10 minutes. If a driver charges 20 minutes, and
keeps his EV connected while it is full for another 20 minutes, a total of 40 minutes is charged. The step_size rounds this up to
**45** minutes total. It does NOT round the parking duration to 30 minutes, making it a total of 50 minutes."

Could you please explain ?

Thanks and regards,

**Comment by RobertdeLeeuw-IHomer** [comment]
Thanks for reporting this. I still have a item on my todo list for going over all the step_size texts, as not everything is very clear.
This was one was not yet on my list. I will look at it. It is not correct, hen everything is rounded to 10 minutes, when using 20 minute s will not cause any rounding. But I want to show some rounding, So I think the example should be: 

"If a driver charges 18 minutes, and keeps his EV connected while it is full for another 15 minutes, a total of 38 minutes is charged. The step_size rounds only the last time based TariffDimension, so in this case the PARKING_TIME of 15 minutes to 20 minutes. It does NOT round earlier time based TariffDimensions, so the charging time is not rounded to 20 minutes, which would then have made the total time of 40 minutes"
