### ISSUE TITLE
Are there JSON Schema files available?

### ISSUE THREAD

**Issue by frankhommers** [ocpi/ocpi#290]
Are there JSON Schema files available?

**Comment by RobertdeLeeuw-IHomer** [comment]
Nope, sorry. We do have OpenApi/Swagger files on the roadmap.

**Comment by juherr** [comment]
For the record: You can find some on GitHub like https://github.com/rvwoens/ocpi-schema or https://github.com/ChargeMap/ocpi-protocol/tree/master/resources/jsonSchemas
