### ISSUE TITLE
Generic Error for Hubs missing: 4000 (Status codes)

### ISSUE THREAD

**Issue by frankhommers** [ocpi/ocpi#291]
Each range has an generic error except hubs. Is this on purpose?

**Comment by RobertdeLeeuw-IHomer** [comment]
Good one! Don't know how that was missed.

**Comment by RobertdeLeeuw-IHomer** [comment]
For now, as a workaround use a 49xx code if is does not match one of the 3 predefined statuses. 

BTW if you find an status code missing, let us know.
