### ISSUE TITLE
Add ability to exchange pricing that's based on time AND charging speed

### ISSUE THREAD

**Issue by rutgerplantenga** [ocpi/ocpi#3]
Several market parties are using time-based pricing on chargepoints whereby the tariff applied depends on the charging speed / output power used*, whereby the charging speed is either averaged over the full session duration OR over brackets of e.g. 15-minutes. 

To properly inform EV-drivers of these (slightly more complex) pricing models it is important that the tariff-information supporting this price-model can be exchanged in a standardised manner. 
- This is done for several reasons:
- To incentivise freeing up the charge point when battery is full, without applying too high tariffs once charging is finished.
- To meet legal requirements (not charging per kWh) whilst still relating the tariff to the power consumed, rather than time-only. This is important as cars have such a wide variety of max charging speeds.

**Comment by RobertdeLeeuw-IHomer** [comment]
Is possible with OCPI 2.1
