### ISSUE TITLE
X-Total-Count, X-Limit, X-Request-ID, X-Correlation-ID and X-"Headers" in general

### ISSUE THREAD

**Issue by frankhommers** [ocpi/ocpi#304]
What is your opinion on this?

https://developer.mozilla.org/nl/docs/Web/HTTP/Headers

Custom proprietary headers can be added using the 'X-' prefix, but this convention was deprecated in June 2012, because of the inconveniences it caused when non-standard fields became standard in RFC 6648;

**Comment by RobertdeLeeuw-IHomer** [comment]
We tried to keep the header names inline with other known REST API pagination implementations, these seemed to be the most common names.
