### ISSUE TITLE
14.4.2.4 Can or Required?

### ISSUE THREAD

**Issue by frankhommers** [ocpi/ocpi#311]
![image](https://user-images.githubusercontent.com/7355878/103775364-39995580-502e-11eb-8f40-ba68c17a85c2.png)

MUST or SHALL, not can.

**Comment by RobertdeLeeuw-IHomer** [comment]
You are right. This has been a sort of standard text in OCPI. I have checked 2.2 for this sentence and fixed them.
While doing this I found a bigger issue: Required: 1??? 

![image](https://user-images.githubusercontent.com/11439081/107541313-4aa62b00-6bc7-11eb-891a-d43b0df6a10c.png)
