### ISSUE TITLE
Tokens / Client Owned Objects vs Pull

### ISSUE THREAD

**Issue by bramus** [ocpi/ocpi#319]
We currently have a few integrations running, both in the CPO as the MSP role. For this issue/question I'm detailing here we are the CPO and the other party is the MSP.

By default we prefer the Push model for all Tokens, where the MSP pushes their tokens to the CPO. In this situation it is clearly stated that the `country_code` and `party_id` **MUST** match to that of the credentials.

> If a client tries to access an object with a URL that has a different `country_code` and/or `party_id` then given during the credentials handshake, it is allowed the respond with an HTTP 404 status code, this way blocking client access to objects that do not belong to them.

This is a good call imo, as it prevents party's from updating Tokens that don't belong to them.

We have noticed that the other party that's talking to use tries to update Tokens that don't belong to them. E.g. they are NL-PARTY1, but are pushing out tokens for NL-PARTY1, NL-PARTY-2, NL-PARTY3, etc.

Given the limitation above we, as per spec, don't allow this.

After weeks of talking and trying to point out this mistake on their end, they now suggest that we switch to a Pull Model and pull in all changes.

Here comes the question now: when we pull in their Tokens, they will also include the tokens for NL-PARTY2, NL-PARTY3, etc. As these tokens still are Client Owned Objects, I'm wondering if the limitation as defined for “Client Owned Object Push” section also applies or not.

- If yes: this scenario is not covered in the spec, as “Client Owned Object Push” only talks about the parameters in the URL which are not present here. It should be expanded to talk about the `country_code` and `party_id` present in the Token.
- If no: how then do we prevent party's from sending out rogue tokens? E.g. we might trust them to send out for NL-PARTY2 and NL-PARTY3, but not NL-PARTY4.

**Comment by RobertdeLeeuw-IHomer** [comment]
I guess this is OCPI 2.1.1? OCPI started as a Peer-to-peer protocol, from 1 CPO to 1 MSP. Starting with OCPI 2.2. it is now possible to send information for multiple CPO's/MSP's over one "OCPI connection", but also then all these CPO's/MSP's need to be reported in the Credentials object. 
But with any version of OCPI, the idea is to only send data that belongs to a party reported in the Credentials handshake. In the case of 2.1.1, that can only be of one party.
Tokens are always "client-owned-objects", even when pulling. The problem with 2.1.1 is bigger when pulling Tokens from multiple MSP's, as the Token object itself does not contain the party_id, you do not know they belong to a different CPO.

**Comment by bramus** [comment]
@RobertdeLeeuw-IHomer Yes, this is about OCPI 2.1 indeed … apologies if I wasn't clear. Guess we're kinda stuck here with 2.1 based on the information you've provided me with. Thanks for clarifying! I'll link back to $OtherParty with this info.

Good to read that OCPI 2.2 supports setting multiple `CredentialsRole`s and that `Token` Object now includes the `party_id` and `country_code` — Great additions! Perhaps the “4.1.5. Client Owned Object Push” section in the OCPI 2.2 spec could use a small rewording to reflect what you've said here — e.g. that it can (must?) check the contents of the object.

**Comment by RobertdeLeeuw-IHomer** [comment]
@bramus I added a branch with some improvements in the client object push wording a new new short section on client object pull. Do you have any improvements on this?
https://github.com/ocpi/ocpi/commit/2b1c2b996b66986db09de1a3046af52ec75d6b9c#diff-74d8e2008c50f3baf4abb0d29d2e3c0ee1d180c4d494b9e539c4823777fba1cf

**Comment by bramus** [comment]
Looks good to me. Perhaps also explicitly mention that it's allowed _(required?)_ for a receiver to ignore an object (when pulling) in case the owner doesn't match those of the `CredentialsRole`s?

**Comment by RobertdeLeeuw-IHomer** [comment]
Agreed, I added some wording for ignoring unknown roles in the pull case: https://github.com/ocpi/ocpi/commit/c2b28c3174e35b22f0cb726af0ab8f1294312893

**Comment by bramus** [comment]
Thanks for the fast iteration on this. Looks good to me! 👍

I'll leave this issue here open for you to close on the changes have been merged, thanks.
