### ISSUE TITLE
OCPI and OCPP Implementation question

### ISSUE THREAD

**Issue by maurerle** [ocpi/ocpi#322]
Hello,

In OCPI and OCPP I can only identify the connectors and evses by a
given id which does not give information of the according connector
type (like Type2 or chademo..)

From a user perspective I don't care about the specific evse_id or
connector_id. I would just provide the given Location and the
Connector_type for a reservation and would be okay with any free evse at the
location.

Is it true that the only information I can get to provide the mapping
between the evse_id+connector_id to a connector_type is through a
custom chargingstation-dictionary which maps the vendor+model from the OCPP
bootNotification to the connectortype of known devices?
This would mean that you always have to know the connectortypes of connected
vendor+models..?
Do you know of any data source which provides such a mapping?

Also: the Session PUT endpoint has a mandatory evse_id and
connector_id, which is unneeded if the user (and eMSP) does not
care about the specific evse at the chargepoint. Just that there is an
evse with the requested connector available?

I really hope you can help me with this and I'd like to know how this
is implemented in existing solutions to comply with the standard :)

Thank you

**Comment by RobertdeLeeuw-IHomer** [comment]
@maurerle With OCPP 1.5/1.6 you are correct. There is no knowledge of the connector type. This has long been a known issue for the OCA (responsible for OCPP) After 1.5 they started work on fixing this in 2.0. As an intermediate step they release 1.6 to add JSON WebSockets and Smart Charging to OCPP. without making too much changes to the rest of OCPP. With OCPP 2.0(.1) this is now solved and Charging Stations should be able to be installed plug-n-play as they should be able to report on the configuration of the Charging Station, including the different connector types. 

"Also: the Session PUT endpoint" Do you mean the Command START_SESSION? 
In most cases the driver knows which EVSE/Connector he/she wants to start. The EV is already parked in a parking bay before the start is send. If this would be a charging plaza with 20 sockets, and you would send a START_SESSION without an EVSE/Connector id, you could end up starting an connector 4 parking bays away... not what a driver would want. 

If a driver wants to make a reservation of any connector on a Location, that is already possible with OCPI. What is not yet possible is to make a reservation of a specific connector type on that location. That has been added to OCPP 2.0.1. It is on our list for things to add to a next version of OCPI.

**Comment by maurerle** [comment]
Hello, i am using OCPP 2.0.1
The specification of OCPP only mentions the connectorType in context of a ReserveNow request.
As far as I found, there is no method for the chargingstation to communicate the connectortype any time to the CSMS (it is neither part of the BootNotificationRequest nor of the StatusNotificationRequest)?

And I am referring to the Session PUT as of: https://github.com/ocpi/ocpi/blob/master/mod_sessions.asciidoc#mod_sessions_msp_put_method

My use case is:
EV Driver makes a reservation for charging tomorrow morning at a location and has a given connectortype available. Session object is created with status RESERVED, but evse_id (and even the chargepoint as of https://github.com/ocpi/ocpi/blob/master/mod_locations.asciidoc#112-group-of-charge-points) is not determined yet (not possible with current ocpi) .

The next day the CPO has planned which evse is available to serve the reservation and tells the user which chargepoint/evse_id/connector_id to use.

My current thought is:
1. create reservation Session with any evse_id/connector_id
2. extract connector_type from evse_id/connector_id and only save connector_type internal
3. a few hours before the reservation is actually needed, update the session with the actual used evse_id and connector_id

The second step is quite counterintuitive.

Is there a roadmap for the next OCPI version?

**Comment by RobertdeLeeuw-IHomer** [comment]
@maurerle 

OCPP 2.0.1: Look at use case B07.  In the FullInventory report, every 2.0.1 Charging Station is require to report this for every connector. See:  page 447, section 2.13.4

You are correct, I think we have missed the option of a Reservation for a not specified EVSE in the Session object. Reservation is rarely used, we have had more things missing with reservation on 2.1.1. As a workaround I would like to propose report evse_uid and connector_id as "N/A". We have another issue were this is also the idea. I will discuss this with the EVRoaming Foundation Dev WG.

**Comment by maurerle** [comment]
Oh okay thanks! I totally missed the ConnectorType variable on page 447.

Setting evse_uid and connector_id sounds good, but instead of those two I want to specify the connector_type with a new reservation session. 
Do you think it makes sense to add the connector_type to the session object?

One would then have to specify either location_id+connector_type or location_id+evse_uid+connector_id

**Comment by RobertdeLeeuw-IHomer** [comment]
I have put reservation of a connector type on a location on the wish list for the next version of OCPI.
There will be a limit, OCPP 1.x does not support this. So the CPO might then still need to reserve a specific EVSE if there are different connectors types on the same location.

I Think you are confusion Session and START_SESSION Command. The Session object is reported by the CPO to the MSP, the START_SESSION Command is the request from the MSP to the CPO.

The Connector ID is already part of the Session object, if the Location module is also implemented the MSP is able to determine what the connector type of the connector is.
For the START_SESSION command, as I have written above, I don't she how this should work in the real world. As an EV driver you are standing at a Charging Location, EV already parked, and a random EVSE at that Location is started. Are you then going to move your EV?

**Comment by maurerle** [comment]
I think I am bending the specification a little bit.
My use case is as follows:
eMSP has some kind of user app. Users can make a reservation for the future through the app for the next day.
So the eMSP would add a session for the next day to the CPO (which is currently not possible through RESERVE_NOW/START_SESSION, as the reservation should only start at the given time [ad-hoc charging is not needed]).
This is currently only possible through a session post from eMSP to CPO (which is possible, but not intended by the specification).

How would you suggest to make this possible?

**Comment by RobertdeLeeuw-IHomer** [comment]
@maurerle As long as the parties you connect with agree you can always bend the specification a bit, that happens a lot. But to prevent problems in the future when you connect to new partners, I always advice to use a custom module, based on the existing module, but then with some changes and a customized name, this way, your partners will know this is not a standard OCPI spec module.

You want to do a reservation in the future? Yes, that is currently not possible with OCPP and OCPI. There are some practical reason why this was never added. You will not know that a driver is able to charge at a Charging Station, as you cannot be sure that another drive will stop charging in time and move his/her EV. I have been involved in a project were we have done a lot of work around to make future reservation possible on DC Fast Chargers, as session on DC Fast Chargers tend to last only 30 to 45 minutes max. 

Maybe we could discuss this in a call, maybe that is easier. Can you send me an email? robert.de.leeuw@ihomer.nl
