### ISSUE TITLE
2.1.1 -> 2.2 changelog names renamed parameters that do not exist

### ISSUE THREAD

**Issue by OskarD** [ocpi/ocpi#324]
The [changelog](https://github.com/ocpi/ocpi/blob/master/changelog.asciidoc) says that the `Tariffs / Tariff Object` has, among others, the following changes:

> - Renamed start_datetime field to start_date_time, to bring the naming inline with the rest of OCPI.
> - Renamed end_datetime field to end_date_time, to bring the naming inline with the rest of OCPI.

But these two fields (`start_datetime` and `end_datetime`) are not part of the [2.1.1 specification](https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_tariffs.md#31-tariff-object).

I assume that it's just a mistake in the changelog, but I thought I would check before creating a pull request.

**Comment by RobertdeLeeuw-IHomer** [comment]
@OskarD you are right, the `start_date_time` and `end_date_time` fields are new in 2.2, this is an error in the changelog. 

Can you create a pull request?
