### ISSUE TITLE
Session receiver interface PATCH contradiction

### ISSUE THREAD

**Issue by Paristha** [ocpi/ocpi#325]
[The PATCH endpoint](https://github.com/ocpi/ocpi/blob/master/mod_sessions.asciidoc#patch-method) contains the following lines:
`When a PATCH request contains the charging_periods field, this SHALL be processed as a request to add all the ChargingPeriod Objects to the existing Session Object.`

`If existing ChargingPeriod Objects in a Session need to be replaced or removed, the Sender SHALL use the PUT method to replace the entire Session Object.`

`all the exiting charging_periods SHALL be replaced by the once in the PATCH request.`

The first two lines imply ChargingPeriod objects in a PATCH request body would be appended to the existing Session object's `charging_periods` field, and the only way to replace or remove objects in said field would be through a PUT. 

The last line appears to describe, through some typos, very different behavior: _replacing_ ALL ChargingPeriod objects in the existing Session object's `charging_periods` field with the ones in the request body. Which is correct?

**Comment by ahzf** [comment]
Hi,

I would say OCPI uses more or less a JSON Merge Patch ( https://tools.ietf.org/html/rfc7386 ). So the charging periods array can only be replaced with a PATCH request.

This is clearly not very efficient for long running charging sessions, but at least is stays as close as possible to really open standards ;)

**Comment by Paristha** [comment]
> So the charging periods array can only be replaced with a PATCH request.

Could you be more specific?

Say, for example, I send a PATCH request body with a charging_periods field that has a list with a single, new ChargingPeriod object, mapping to an existing Session object that has a list of 5 ChargingPeriod objects in its charging_periods field. Does this replace the list of 5 with a list of 1 or append, updating the list to a list of 6?

**Comment by ahzf** [comment]
It would be replaced, when you assume that the OCPI PATCH request ist a JSON MERGE PATCH.

**Comment by RobertdeLeeuw-IHomer** [comment]
@Paristha The last sentence was a type/error in the documentation. There is an improved description in the bugfix branch. https://github.com/ocpi/ocpi/commit/1d5c6a6311ac45f180662d6c9cc9de62c0df03c3

See: https://github.com/ocpi/ocpi/blob/release-2.2-bugfixes/mod_sessions.asciidoc#patch-method

Does this improved description make things more clear?

**Comment by Paristha** [comment]
> Does this improved description make things more clear?

Not really, if @ahzf 's explanation is accurate. This sentence is the source of my confusion:

`If existing ChargingPeriod objects in a Session need to be replaced or removed, the Sender SHALL use the PUT method to replace the entire Session object (including all the charging_periods).`

If the `charging_periods` field in an existing Session object is replaced by the `charging_periods` field in a PATCH's request body, if present, then the above is incorrect.

**Comment by ahzf** [comment]
Well, I can not say what is "correct". I can only say what the IETF has defined for very good reasons. There are two versions of HTTP Patch (Merge Patch and Patch documents) available to solve this problems. And I would say IETF standards >> OCPI experiments ;)

The same problem exists btw. with charging locations and the array of EVSEs and within an EVSE and its array of sockets. But there OCPI has specialized HTTP methods to modify EVSEs and sockets. These are missing for charging sessions and charging periods.

Keep in mind... OCPI is neither stable, nor production ready yet.

**Comment by Paristha** [comment]
@RobertdeLeeuw-IHomer 

Just to have as clear an understanding as possible, for this example: https://github.com/ocpi/ocpi/blob/master/examples/session_patch_example_charging_period.json

Is the expected behavior that the TARGET of this PATCH...
1. Have its `charging_periods` field replaced by the one in the PATCH _or_
2. Append the ChargingPeriod obj to its `charging_periods` field
?

**Comment by RobertdeLeeuw-IHomer** [comment]
@Paristha 
PATCH Appends ChargingPeriods
PUT replaces the entire Session object. 

When CharginPeriods need to be replaced: use PUT, if ChargingPeriods need to be appended: use PATCH.

**Comment by ahzf** [comment]
@RobertdeLeeuw-IHomer What about revoking this part of the specification and providing a specification errata which is aligned with international IETF standards? Because I know some bigger players which do _not_ implement this in the way you described it.
