### ISSUE TITLE
Description of the tariff object

### ISSUE THREAD

**Issue by fsimba** [ocpi/ocpi#333]
Hello, In the description of the [tariff object](https://github.com/ocpi/ocpi/blob/master/mod_tariffs.asciidoc#131-tariff-object), it is mentioned that only one tariff per type of element can be active at a time, but several types of tariffs can be active at the same time. IE you can have an `ENERGY` element and a `TIME` element active at the same time, but only the first valid element of each.

Will this mean that charging time and energy cannot be billed at the same time?
```
"elements": [
    {
		"price_components": [{
            "type": "TIME",
            "price": 1.00,
            "step_size": 60
        }]
	},
    {
		"price_components": [{
            "type": "ENERGY",
            "price": 1.25,
            "step_size": 60  
        }]
	}
]
```

If so, is it possible to combine multiple priceComponents of different dimensionType in one tariffElement? For example `FLAT + TIME + ENERGY` 

Thank you beforehand

**Comment by fsimba** [comment]
```
{
  "country_code": "FR",
  "party_id": "ALL",
  "id": "17",
  "currency": "EUR",
  "elements": [
    {
      "price_components": [
        {
          "type": "FLAT",
          "price": 0.5,
          "step_size": 1
        },
        {
          "type": "ENERGY",
          "price": 1.5,
          "step_size": 1
        }
      ],
      "restrictions": {
          "min_duration": 120,
          "min_kwh": 1
      }
    },
    {
      "price_components": [
        {
          "type": "FLAT",
          "pprice": 1,
          "step_size": 1
        }
      ]
    }
  ],
  "last_updated": "2018-12-17T11:36:01Z"
}
```
What will happen if we have this kind of tariff for these different cases:
- when the load is below 1kWh
- when the load is 3kWh for 30min 

Thank you in advance for your suggestions

**Comment by RobertdeLeeuw-IHomer** [comment]
Good point, there is nothing describing the use of multiple restriction at the same time, no examples.
I will discuss with the development group.

How I think this should work: Multiple restrictions should be treated as an AND.
So
The first Tariff Element is only active when you charge longer then 120 minutes and more then 1 kWh.
The "fallback" tariff is 1 euro FLAT fee.

- when the charge is below 1kWh: you pay 1 euro.
- when the charge is 3kWh for 30min: you pay 1 euro.

**Comment by fsimba** [comment]
Thank you for your explanation. 
I agree with you for the first case. 
But for the second case, I think that min_duration is in seconds. 
So in my opinion, the two tariffElements are active both and I would have proceeded in this way:
(1.5 euro * 3kWh) + 0.5 euro + 1 euro = 6 euro


What do you think about that?

**Comment by RobertdeLeeuw-IHomer** [comment]
First of all, sorry for the late response, had other priorities last week.

My bad, you are right, min_duration is in seconds.

The price will be: (1.5 euro * 3kWh) + 0.5 euro = 5 euro

The second tariff element (FLAT 1 euro) is not used:

_"When the list of Tariff Elements contains more than one Element with the same Tariff Dimension (ENERGY/FLAT/TIME etc.), than the first Tariff Element with that Dimension in the list with matching Tariff Restrictions will be used. Only one Tariff per Element type can be active at any point in time, but multiple Tariff Types can be active at once."_

**Comment by fsimba** [comment]
Hello, thank you for your review.
In order to fully understand how the valuation of a charge works, I did some research on my own to try to find a calculation core on existing projects using OCPI but in vain.

So, I would like to know if you would have a simulation engine so that I can do some tests on my side.
Otherwise would you have an algorithm model so that I can draw inspiration from it?

Thank you in advance for your suggestions

**Comment by RobertdeLeeuw-IHomer** [comment]
@fsimba 
As far as I know there is nothing available on the market (yet) that you can give a Tariff and a Sessions object and let it calculate the correct price. Would be very useful for a lot of companies.
