### ISSUE TITLE
rounding up according to the value of step_size

### ISSUE THREAD

**Issue by fsimba** [ocpi/ocpi#334]
Hello, Based on the explanations found in the description of the [CDR object](https://github.com/ocpi/ocpi/blob/master/mod_cdrs.asciidoc#131-cdr-object) and [tariff object](https://github.com/ocpi/ocpi/blob/master/mod_tariffs.asciidoc#142-pricecomponent-class) on the impact of the interpretation of step_size on the calculation of the price of a charge, I know that amounts that are less than `step_size` are rounded up to the given `step_size`. 
But when it is necessary to switch from tarrifElement, the rounding up process is not very clear.

In the examples below taken from the description of the CDR object, we can see that for the first example, only the last chargingPeriod (parking time) has been rounded up while in the second example it is the two chargingPeriod of the session which has been rounded up. 

At last, for the third example, token from the [examples](https://github.com/ocpi/ocpi/blob/master/mod_tariffs.asciidoc#example-tariff) which can be found in the pricing module, it is the duration of the session (two chargingPeriod of `TIME` ) that has been rounded up.

- Example 1: `step_size` for both charging `TIME` and parking is 5 minutes. After 21 minutes of charging, the EV is full but remains connected for 7 more minutes.
The cost of charging will be calculated based on 21 minutes (not 25). 
The cost of parking will be calculated based on 10 minutes (`step_size` is 5).

- Example 2: Charging cost 0.20 euro before 17:00 and 0.27 after 17:00 both have a step_size of 500 Wh. If a driver charges 4.3 kWh before 17:00 and 1.1 kWh after 17:00, a total of 5.4 kWh is charged. The step_size rounds this up to 5.5 kWh total. It does NOT round the energy used after 17:00 to 1.5 kWh.

- Example 3: Charging cost 1.20 euro for a `step_size` of 1800sec before 17:00 and 2.40 after 17:00 and have `step_size` of 900sec. 
An EV driver plugs in at 16:35 and charges for 35 minutes (`TIME`).
After that they immediately unplug, leaving with a total session time of 35 minutes and a bill over the following costs:

    - 25 billable minutes of charging time before 17:00, generating costs of 0.50 euro.
    - 20 billable minutes of charging time after 17:00, generating costs of 0.80 euro.
        As the Price Component of the last Tariff Element being used has a `step_size` of 15 minutes,
        the total duration is rounded to up to 45 minutes.
        When considering the already billed 25 minutes of charging time before 17:00,
        we are left with 20 minutes to bill after 17:00.
    - The total for this charging session is therefore *1.30 euro*.

Can someone explains me how it works ?

Thanks in advance for your help

**Comment by RobertdeLeeuw-IHomer** [comment]
There are some mistakes in the step_size descriptions, especially around switching from one tariff to another. 
It is on my todo list. I hope to write this asap.
