### ISSUE TITLE
Origin of the contract_id field (Tokens Module)

### ISSUE THREAD

**Issue by tlindener** [ocpi/ocpi#339]
Hi,

I'm wondering about the origin of the contract_id described in the tokens module. 
Given that it is declared as required I would like to know where it comes from and which side needs it for what purpose.

Any help is appreciated.

**Comment by RobertdeLeeuw-IHomer** [comment]
They idea has been that the contract_id is the number that is used between CPO and MSP for billing purposes. This identifies a specific contract the MSP has. It is left open to the MSP, how they use the contract_id. They can give every Token a unique contract_id. But they could also group a set of cards under one contract. the last might be useful when the customer is a fleet owner. On the other hand, the MSP could still give every Token of a fleet a unique contract_id and join all sessions on the same invoice to the fleet owner.

**Comment by tlindener** [comment]
Thanks for the explanation!

**Comment by ahzf** [comment]
The contract id is often used as a one-time-token or session id, as it violates the GDPR.
