### ISSUE TITLE
Party id registry in IT

### ISSUE THREAD

**Issue by softwareloop** [ocpi/ocpi#341]
Hi, is there a registry for party id's in Italy? I'm asking as an eMSP.

**Comment by RobertdeLeeuw-IHomer** [comment]
As far as I known, not yet. Have you asked the larger already existing CPOs?

**Comment by mbayings** [comment]
No. There is no official IDRO (ID Registration Office) in Italy yet. At least not one known with the countries that have one or are setting up one. Besides possible own effort to setup IDRO via the government, there are two other options: 1. you can use ID from other IDRO (so from other country) in Italy. Within EU it is agreed that ID from can be used also in other countries than the one where it was requested. 2. You can create your own IT code, and take the risk that at a certain moment you can register it officialy.

**Comment by softwareloop** [comment]
Thanks. Yes I'm in touch with the main CPO's in Italy. I'll post here if I get any news regarding an official IDRO, as it may be of interest to others.
