### ISSUE TITLE
Specify headers for rate limiting/throttling

### ISSUE THREAD

**Issue by tlindener** [ocpi/ocpi#342]
I would like to suggest to already specify headers that can be used to tell a client about rate limits when accessing bulk resources (e.g. locations). 
The goal is to ensure that if a client requests e.g. locations in bulk the service can tell the requester to slow down the number of requests in order to ensure processing of real time requests. 

To be inline with the current headers those could be:
"X-Ratelimit-Remaining" (int)
"X-Ratelimit-Reset" (int, in ms)

If no headers are provided the client is free to act like today but if the headers are provided the client SHALL honor them or get an 429 once the limit is broken.

**Comment by RobertdeLeeuw-IHomer** [comment]
Thank you for the suggestion.
Have you read https://github.com/ocpi/ocpi/blob/master/CONTRIBUTING.md?

**Comment by tlindener** [comment]
Yes, what part are you specifically referring to?

**Comment by RobertdeLeeuw-IHomer** [comment]
We ask anybody that wants to contribute to the specification, especially if you want to add new functionality, to sign the IPR agreement so we can try as best as possible to keep OCPI free from IPR.

**Comment by tlindener** [comment]
> 
> 
> We ask anybody that wants to contribute to the specification, especially if you want to add new functionality, to sign the IPR agreement so we can try as best as possible to keep OCPI free from IPR.

Good morning, yes I saw that part and already asked for the CLA. The response was this:
`As the OCPI development and maintenance is ‘taken over’ by the EVRoaming Foundation, the only way to contribute now is to become a Full Contributor of the EVRoaming Foundation.`
A 4k price point is just not fitting to my involvement. I sure hope I can still propose ideas via issue tracker (or some other way?)?

**Comment by RobertdeLeeuw-IHomer** [comment]
By posting things here in Github we cannot look at them as new ideas. We cannot know if you are adding IPR. On the other hand, you are putting in time, posting ideas here, not aware of the development work happening within the EV Roaming foundation. So might be posting things that are already on our list of ideas/improvements.

**Comment by tlindener** [comment]
Seems like a misunderstanding to me. I thought the goal of this repository was to have an open development process of the OCPI standard so I wanted to contribute if possible. Paying to be allowed to contribute IMHO only makes sense for a company but not for an individual. Anyways, sorry for wasting your time. Really appreciate the work you guys are doing.

**Comment by mbayings** [comment]
We always try to find the right balance, which will never make everyone happy. We want to keep OCPI free to use without risks of IPR/royalty claims. If we would allow individuals to contribute for free and only ask money to companies, all companies would exist out or many individuals - it is impossible to verify if an individual is indeed only contributing as individual and not on behalf of a company. From the other side, although we appreciate input from everyone, it are the companies that use OCPI and not indivividuals, unless they have a business reason to use it which might make it interesting again to pay the contribution fee.
But again, we realize that finding the right balance is hard.
