### ISSUE TITLE
GBT/GBT_DC connector type

### ISSUE THREAD

**Issue by softwareloop** [ocpi/ocpi#345]
Hi. A CPO and us (an EMSP) are dealing with some connectors of type GBT and GBT_DC.
Have you already reserved ConnectorType values for these?
What would be the best way to approach this in OCPI 2.1.1? Extending the enumeration? Or using a fixed value OTHER?

**Comment by RobertdeLeeuw-IHomer** [comment]
For OCPI 2.1.1 the best workaround is to extend the enumeration. But the CPO needs to be careful to which MSP they send them. 
For OCPI 2.2 this is going to be fixed in OCPI 2.2.1, which we hope to release very soon.

**Comment by softwareloop** [comment]
Thanks
