### ISSUE TITLE
Charging Profile startProfile

### ISSUE THREAD

**Issue by thanaParis** [ocpi/ocpi#347]
In the description of 'duration' in ChargingProfile, it says "If the duration is left empty, the last period will continue indefinitely or until end of the transaction in case startProfile is absent."

I think 'startProfile' is a typo, and I checked the bugfix branch this time; there's no fix there. This line appears to have been copy/pasted from the OCPI description of 'duration' in the definition of ChargingSchedule, where 'startProfile' was 'startSchedule', which is 'start_date_time' in an OCPI ChargingProfile. So, should  'startProfile' be 'start_date_time'?

**Comment by RobertdeLeeuw-IHomer** [comment]
You are correct, indeed a copy/paste error from OCPP. 
Are you able to create a pull request to fix this?

**Comment by thanaParis** [comment]
#348
