### ISSUE TITLE
Clarify status code usage

### ISSUE THREAD

**Issue by kix** [ocpi/ocpi#35]
[Protocol and endpoints doc](https://github.com/ocpi/ocpi/blob/master/3.%20Protocol%20and%20endpoints.md#a-note-on-error-responses) states that the status code of the response is contained in the JSON body. Does this mean the HTTP response might contain a different status code? If it (hopefully) won't, why is this duplication needed?

To clarify, this is how I imagine the response should look (full view with headers):

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Date: Thu, 23 Jul 2015 07:26:23 GMT
...

{
    "status_code": 200, 
    "timestamp": "...",
    "data" : {
        ...
    }
}
```

This way, status code `200 OK` would get duplicated both in the headers and in the JSON body.

**Comment by poohsen** [comment]
the status code is supposed to map to errors from the OCPI domain, i.e. communication between chargepoint operators and mobility service providers. It's not about HTTP codes. To further distinguish the two, we'll use 4 digits for OCPI status codes.

**Comment by RobertdeLeeuw-IHomer** [comment]
Improved definition of status_code to make it more clear that OCPI status codes should be used, not HTTP
