### ISSUE TITLE
TariffElement with TIME and ENERGY PriceComponents

### ISSUE THREAD

**Issue by langiole** [ocpi/ocpi#356]
Does OCPI define behavior for a TariffElement that has both an `ENERGY` PriceComponent and a `TIME` PriceComponent? I haven't seen such a tariff in any of the examples, but have not seen anything in the OCPI spec to indicate that such a list of price components is invalid.

OCPI seems to define the behavior at the TariffElement level with:

> When the list of Tariff Elements contains more than one Element with the same Tariff Dimension (ENERGY/FLAT/TIME etc.), than the first Tariff Element with that Dimension in the list with matching Tariff Restrictions will be used. Only one Tariff per Element type can be active at any point in time, but multiple Tariff Types can be active at once. IE you can have an ENERGY element and TIME element active at the same time, but only the first valid element of each.

But not at the PriceComponent level. Consider the tariff:
```
"elements": [
    {
        "price_components": [{
            "type": "TIME",
            "price": 1.00,
            "step_size": 60
        }, {
            "type": "ENERGY",
            "price": 1.25,
            "step_size": 60  
        }]
    }
]
```
Would both the `TIME` PriceComponent and `ENERGY` PriceComponent be applied? If so, which dimension is this TariffElement then considered to be? `TIME` or `ENERGY`? Also, what might the behavior be if we had another TariffElement in the list that contains a `TIME` PriceComponent and an `ENERGY` PriceComponent?

**Comment by thanaParis** [comment]
TariffElements can have multiple PriceComponents, therefore multiple TariffDimensions, therefore multiple element types such as FLAT and TIME or, in your example, TIME and ENERGY.

If there was another TariffElement in the list that contained either a TIME or an ENERGY component, only the first valid element applies, as is said in the part of the specification you quoted. For example:

```
"elements": [
    {
        "price_components": [{
            "type": "TIME",
            "price": 1.25,
            "step_size": 60
        }, {
            "type": "ENERGY",
            "price": 1.25,
            "step_size": 60  
        }],
        "restrictions": {
            "day_of_week": ["SATURDAY", "SUNDAY"]
        }
    },
    {
        "price_components": [{
            "type": "TIME",
            "price": 1.00,
            "step_size": 60
        }, {
            "type": "ENERGY",
            "price": 1.25,
            "step_size": 60  
        }]
    }
]
```

On the weekend, only the first element applies. During the week, only the second element applies. This behavior is alluded to in the specification:

> It is advised to always add a "default" Tariff Element per Dimension (ENERGY/FLAT/TIME etc.). This can be achieved by adding a
> Tariff Element without Restrictions after all other occurrences of the same Dimension in the list of Tariff Elements (the order is
> important).
