### ISSUE TITLE
Typo in EnergyMix

### ISSUE THREAD

**Issue by thanaParis** [ocpi/ocpi#357]
The description of the `environ_impact` field in the EnergyMix class definition is

> Key-value pairs (enum + percentage) of nuclear waste and CO2 exhaust of this location’s tariff.

`environ_impact` is of type EnvironmentalImpact. However, the EnvironmentalImpact class definition has as its description

> Amount of waste produced/emitted per kWh.

And its second field, amount, is in g/kWh, not percentage. I'm not sure which field(s) have an incorrect description here, but it is inconsistent.

**Comment by RobertdeLeeuw-IHomer** [comment]
Yes, you are correct, this seems to be a copy/past error. IS should be: 

`Key-value pairs (enum + amount) of nuclear waste and CO2 exhaust of this location’s tariff.`
