### ISSUE TITLE
Discrepancy between class definition and examples

### ISSUE THREAD

**Issue by langiole** [ocpi/ocpi#359]
In the documentation, the `TariffElement` class defines a `restrictions` property with a cardinality of zero or more indicating that this field is an array of `TariffRestrictions`.

In the various `Tariff` examples, however, this `restrictions` field is depicted as an object. For example:
```
{
	"price_components": [{
		"type": "PARKING_TIME",
		"price": 6.00,
		"vat": 10.0,
		"step_size": 300
	}],
	"restrictions": {
		"start_time": "10:00",
		"end_time": "17:00",
		"day_of_week": ["SATURDAY"]
	}
}
```

**Comment by thanaParis** [comment]
[The specification does not have a cardinality of one or more.](https://github.com/ocpi/ocpi/blob/release-2.2-bugfixes/mod_tariffs.asciidoc#144-tariffelement-class)

`?` represents a cardinality of `0...1`
