### ISSUE TITLE
Notes OCPI workshop #10

### ISSUE THREAD

**Issue by poohsen** [ocpi/ocpi#36]
- status codes:
  - 1xxx: Success
  - 2xxx: Client errors
  - 3xxx: Server errors
    with x000 being a generic catch-all for each category
- voltage will be defined as „line-to-ground“ for now; 
  - power is then `nr_of_phases x voltage x amperage`
- energy classification: 
  - flat list  
  - „unspecified“ is implicit
- CDR specification
  - it’s proposed to put a Location, Evse and Connector_number object in the CDR so it contains all the information that could possibly be relevant to the price-making of the provider
  - vat dropped from cdr for now for several reasons
    - the cdr is not a financial document
    - putting the right vat in there places more burden on the operator because the rules behind applying the right VAT is complicated
    - we keep total_cost because it’s simple; at the same time we include all information that led up to calculating it
- NDR: redefine as unfinished CDR; extend CDR with any fields not present in the CDR spec yet
- CDR object

```
id
status
start_datetime
end_datetime
kwh
authorization_id
location: Location object
evse: Evse object
connector: Connector object
meter_id
currency
charging_periods: [
   (start_datetime, end_datetime, tariff_number, kWh, cost, max_power)  —> The rest of the details will be taken from the tariff information on the EVSE object . This object is Optional               
]               
total_cost (excl. VAT)
```

**Comment by cristinarc** [comment]
@poohsen do you have the information you collected about the CDR object in that meeting? Is that the one I have just added there?

**Comment by simonphilips** [comment]
Photograph of the whiteboard:

![img_20150731_125440](https://cloud.githubusercontent.com/assets/3263809/9712679/a31a99ca-554c-11e5-9010-79365f5e7e7f.jpg)
