### ISSUE TITLE
When should EVSE status INOPERATIVE be used?

### ISSUE THREAD

**Issue by lantw44** [ocpi/ocpi#360]
OCPI 2.2 describes `INOPERATIVE` as 'not yet active or no longer available (deleted)', but both explanations are similar to the other status values. For 'not yet active', it sounds like `PLANNED`. For 'no longer available (deleted)', it sounds like `REMOVED`. When should `INOPERATIVE` be used instead of these alternatives? Can it be used to mean the OCPP charger availability is set to `Inoperative`, or the CPO temporarily makes the charger unavailable to users?

**Comment by RobertdeLeeuw-IHomer** [comment]
The differences between the status that explain to a driver that charging is not possible can be small. Most important is to tell the driver that charging will not be possible. So if it then is BLOCKED, INOPERATIVE, OUTOFORDER, PLANNED or REMOVED is, in my eyes less important. 

Mapping OCPP "Unavailable"? I would say: "OUTOFORDER". 
I agree that the description of INOPERATIVE has an overlap with PLANNED and REMOVED.

**Comment by lantw44** [comment]
> The differences between the status that explain to a driver that charging is not possible can be small. Most important is to tell the driver that charging will not be possible. So if it then is BLOCKED, INOPERATIVE, OUTOFORDER, PLANNED or REMOVED is, in my eyes less important.

It is true that most status values (except for `REMOVED`) aren't treated specially in the protocol, and I agree that users probably don't care the difference. But there should be a reason for each of these values to exist, right? Since the description of `INOPERATIVE` is similar to other status values, it can make people wonder what is the intended use case of it.

> Mapping OCPP "Unavailable"? I would say: "OUTOFORDER".
> I agree that the description of INOPERATIVE has an overlap with PLANNED and REMOVED.

It would be nice if the description can be updated to avoid the overlap, so it could be less confusing to people implementing OCPI.

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed https://github.com/ocpi/ocpi/commit/d8af448f353a61bc033aea083f5385e533a812b7
