### ISSUE TITLE
Is SignedData url really case-insensitive?

### ISSUE THREAD

**Issue by lantw44** [ocpi/ocpi#361]
OCPI defines `URL` type as a case-sensitive `string(255)` following the URL format, but the `url` field of `SignedData` class uses `CiString(512)`. Shouldn't it use `string(512)` because URLs are case-sensitive?

**Comment by frankhommers** [comment]
Dupe of or at least related to https://github.com/ocpi/ocpi/issues/293 ?

**Comment by lantw44** [comment]
It is related to https://github.com/ocpi/ocpi/issues/293 but it is not a duplicate of it. https://github.com/ocpi/ocpi/issues/293 resolves the problem for `public_key`, `plain_data`, `signed_data` fields but not `url` field.

**Comment by RobertdeLeeuw-IHomer** [comment]
You are right, thanks for reporting this.
