### ISSUE TITLE
OCPI WORKSHOP #11

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#37]
## Regarding the Release 1
- Update the specifications for release 1 so now we allow also to pinpoint the specific resources for updating with **PUT** and **PATCH**. _…/locations/{1}_, _…/evses/{1}_, etc
- This give us the possibility of making easier and more intuitive commanding the url. We will also add inside the Evse information an object called “Capability” and will have an id and a URL that will be the one that will be called if the provider would like to make use of this capability.

```
"capabilities": [
{"id": "start", "url": ".../evses/1/start"},
{"id": "stop", "url": ".../evses/1/stop"}
]
```
### Social charging scenarios:
1. Neighbor charging in a charge point for too long time, the owner of the charge point wants to charge there but they don’t have any contact details about the user that is charging there, so request would need to go to the CPO and the CPO would need to send it to the eMSP of the user that is charging there, so it can deliver it to the user.
2. The user has found out that the charge point is not the right spot, is broken or something, then the user should be able to send this information to the CPO so they can use it if the want.
### Sessions:
- **CPO requests to the eMSP**  
  - **POST**: For session started                                                    >>  …/sessions
  - **PATCH**: Information update about an specific session        >>  …/sessions/id
             “status” = “SessionEnded” -> Will be used to seal the dynamic session and ‘create’ the CDR  ->  After that we should not allowed to accept any PATCH any more, just inform that is too late to update it
        use an index for the “status” field has been added to the CDR (dynamic)
  - **PUT**: Not allowed
- **eMSP requests to the CPO**
  - **GET**: For requesting information about the CDR                 >>  …/sessions/id or …/sessions?{filters}
### Notes:
- The stored information about the CDRs is compatible with the information has been set as CDR in **emi3** specifications.
- The information is contained in the CDR included the whole object so the CDR is an isolated and independent object, that doesn’t depend on “how updated” the DB of the eMSP is. Then in case of any possible doubt about the status of the session is clear what was sent with the CDR. The eMSP can store whatever considers needed in their DB.
- Status field possible values, Simon’s idea is: “pending”, “active”, “completed”, “invalid”. Compare with previous version of OCPI, OCPP and OCHP direct during the next workshop.

**Comment by cristinarc** [comment]
I think is interesting we have a look to the answer that was given to a question on how to make commands RESTful: http://stackoverflow.com/questions/3468177/restful-way-to-send-commands

Sounds interesting to me the fact that a request can be identified, but I am not sure if assigning an id to a request makes that much sense in our scenarios. That could be a nice way of keeping track of the requests that are pending to process or getting response about.

E.g. 
_eMSP to the CPO_        
* REQ: **POST** .../evses/evse01/start {}
* RES:                  Ok, 201 {"id": "start_evse01_001"}
_CPO  to the eMSP_
* REQ: **POST** .../evses/evse01 {"id": "start_evse01_001", "status": "failed", "description": "no car connected"}

I think is interesting we keep that in mind in the commands chapter.

**Comment by simonschllng** [comment]
@cristinarc this can be very helpful for debugging between multiple systems. If both log the IDs it can help very much.

**Comment by poohsen** [comment]
small remark from followup workshop: as written in README.md, the release numbers start with 2.0, not 1. 2.0 deals with evses and locations, 2.1 deals with CDRs, and so on

**Comment by simonphilips** [comment]
Photograph of the whiteboard:

![img_20150821_112704](https://cloud.githubusercontent.com/assets/3263809/9712725/f12bb16c-554c-11e5-83aa-9339c290bcbd.jpg)

(This is more of a memory refresher and not really useful information for those who were not at the meeting.)
