### ISSUE TITLE
Credentials GET method 

### ISSUE THREAD

**Issue by SoloVeniaASaludar** [ocpi/ocpi#372]
Sorry for use an issue for something that is more a question than a issue (there are anywhere a forum or mail list for questions about OCPI? ).

I'm trying to understand method GET in Credentials interface. The specification says:

```
7.2.1. GET Method
Retrieves the credentials object to access the server’s platform. The request body is empty, the response contains the credentials
object to access the server’s platform. This credentials object also contains extra information about the server such as its business
details.

```

As previous statement says, this method has no body. Moreover, no URL syntax with the endpoint structure definition. So, the only additional information that the server can use is the http headers, in particular, the Authorization one.

From phrase "credentials object also contains extra information about the server such as its business details" I infer that the answer must contain information about the server credentials, not information about the client credentials that the server stores in its database.

**My question: What are "the credentials object to access the server’s platform" ?.** 

Obviously, the server must not reveal any secret token. The specification says that the first token to register a peer is sent outside protocol (mail, ...) and changed for a new token during credentials handshake (GET/GET/POST/GET/GET/result as described in chapter 7.1). 

The only possibility I can imagine is that Credentials GET is used by an already authenticated party not to retrieve a "credentials object to access the server" but to refresh the roles information (credentials.roles[]) of the server.

**Comment by reinierl** [comment]
> there are anywhere a forum or mail list for questions about OCPI?

There is a Slack group at https://join.slack.com/t/ocpi/shared_invite/zt-zyn1zczq-1WakU4ZGh6NBuFcMs56ZmQ , but using Github is fine too.

I will get back to your question about GETting credentials later today.

**Comment by reinierl** [comment]
My question: What are "the credentials object to access the server’s platform" ?

That's the credentials object, as [described in the spec](https://github.com/ocpi/ocpi/blob/2.2.1/credentials.asciidoc#131-credentials-object), for the server. So it _does_ contain the token that the client is already using to authenticate to the server. That's not the best idea and that's why we're going to do authentication differently in OCPI 3.0.

**Comment by SoloVeniaASaludar** [comment]
@reinierl : Thanks a lot for your support.

Assume that, after the message interchange described in paragraph "7.1.1. Registration", the "sender" (using same names that in the specification, that is, the http client) sends a "GET /ocpi/cpo/2.2/credentials" to the receiver. It includes an authorization header equal to CREDENTIAL_TOKEN_C. 

If I understand correctly your answer, the "receiver" (the http server ) must answer the GET with a body equal to:

```
{ token: _CREDENTIALS_C_,
url: "/ocpi/cpo/versions"
roles: [ role: "CPO", ... ]  }
```

(a few useless, because, as you say, the token was already included in the GET request, the main url should not change, only "roles" can have some use).
