### ISSUE TITLE
Connector status

### ISSUE THREAD

**Issue by SoloVeniaASaludar** [ocpi/ocpi#374]
In OCPP, the message StatusNotificationRequest informs about the status of a connector in an evse of a charging station. Possible status are: Available, Occupied, Reserved, Unavailable, Faulted.

In OCPI (Locations module) only the EVSE has an state (even when the status descriptions says "The EVSE/Connector is ..."). No status field in Connector object.

It seems very feasible that a connector of an EVSE was faulty while remainder connectors of the same EVSE was functional. +1 for OCPP status for each connector.

It seems very unlikely to reserve a specific connector of an EVSE, because only one connector can be active in a EVSE at certain moment. +1 for OCPI status at EVSE level.

Do you have a recommendation about this subject ?

**Comment by reinierl** [comment]
I have no particular recommendation. I know that I and other people have dealt with this issue in the past. You have to stop and think about it indeed but we've managed.

Furthermore I can say the following about it.

OCPP 1.x's notion of a connector status mixes three concepts:
 * whether the EVSE is currently available for a new user (Available vs Occupied/Charging/Preparing/Finished/SuspenededEVSE/SuspendedEV)
 * whether the connector and EVSE are currently operational (Faulted and Unavailable on the one hand vs all the others on the other hand), and
 *  what the current status of the ongoing transaction is if there is any (the difference between Occupied, Charging, Preparing, Finished, SuspendedEVSE and SuspendedEV among each other)

OCPI's EVSE status is used only for the first two but not the third, which is dealt with in the sessions module in OCPI.

Gireve's proprietary protocol splits the three concepts cleanly I think. OCPP 2.x also started separating the concepts but I don't know off the top of my head how it does it.

So pretty much every CPO's IT landscape will have to map and convert between different protocols' modelling of charging infrastructure's status, and in fact all other properties of charging infrastructure. There are at least 6 of these protocols I can think of: OCPP 1.x, OCPI, OCPP 2.x, Gireve proprietary, Hubject proprietary, e-clearing proprietary. To deal with this, it can help to use a [hexagonal architecture](https://en.wikipedia.org/wiki/Hexagonal_architecture_(software)) to write your core business logic using one model and employ multiuple adapters to translate from the core logic's format to the other formats you need to support.
