### ISSUE TITLE
Tokens receiver URL

### ISSUE THREAD

**Issue by SoloVeniaASaludar** [ocpi/ocpi#375]
Minor comment, in Tokens module -> 12.2.1. Receiver Interface, the URL:

`{token_endpoint_url}{country_code}/{party_id}/{token_uid}[?type={type}]
`
probably a slash before country_code is missing:

`{token_endpoint_url}/{country_code}/{party_id}/{token_uid}[?type={type}]`

**Comment by reinierl** [comment]
Thanks! It's fixed on the release-2.2.1-bugfixes branch now.
