### ISSUE TITLE
CDR object, tariff field

### ISSUE THREAD

**Issue by SoloVeniaASaludar** [ocpi/ocpi#376]
The following field description can be seen at CDR object:

```
Property: tariffs 
Type: Tariff 
Cardinality: * 
Description: List of relevant Tariff Elements, see: Tariff. When relevant, a Free of Charge tariff should also be in this list, and point to a defined Free
of Charge Tariff.
```

Note the type is "tariff" but the description talks about "relevant Tariff **Elements**". This is a few contradictory, could be it should be "List of relevant Tariffs, see ..." (without word "Elements").

**Comment by reinierl** [comment]
Thanks! Fixed now on the release-2.2.1-bugfixes branch.
