### ISSUE TITLE
link  "ocpi-3 repository" in README.md is broken

### ISSUE THREAD

**Issue by md42** [ocpi/ocpi#377]
![image](https://user-images.githubusercontent.com/857448/147888871-55f79ad1-1111-4e80-bd98-75fd30f27b12.png)

**Comment by mbayings** [comment]
It is not broken. Working perfectly. But as you can read, it is only accessible for Contributors of the EVRoaming Foundation. You are welcome to become a contributor and get access to it. See for more information: www.evroaming.org.
