### ISSUE TITLE
Change Location > Connector > TariffIds on OCPI 2.2.1 

### ISSUE THREAD

**Issue by sdgroeneveld** [ocpi/ocpi#379]
Please consider changing or adding to the 8.3.3 > Location > Evse > Connector > tariffIds.
A list of tariffIds changed or suplemented with a complex type 'connectorTariffs' with at least the following properties:
* tariffId (refs to a existing tariffId)
* start_date_time
* end_date_time
this to indicate when a tariff is applicable on this connector and allows for better and scheduled changing of the connector to a different tariff. Same restriction apply as on the Ids but with the option of switching a tariff on a connector without invalidating any used tariffs.

**Comment by Alan-Stewart** [comment]
I agree.  We had to do this to a number of tables so that we could track when certain things were in effect.  This is especially important when looking at stuff that happened in the past.

**Comment by reinierl** [comment]
I agree as well. This ties in with a security risk that was identified for OCPI 3.0. The OCPI 3.0 Github project is accessible only to members of the EV Roaming Foundation, but if you are one, you can find it here: https://github.com/ocpi/ocpi-3/issues/94
