### ISSUE TITLE
More restrictive allowed characters in IDs (than current CIString)

### ISSUE THREAD

**Issue by nowosprz** [ocpi/ocpi#382]
Currently (true for 2.2.1) IDs (e.g. [tariff](https://evroaming.org/app/uploads/2021/11/OCPI-2.2.1.pdf#mod_tariffs_tariff_object) ID, Location ID, CDR ID) are of type [CIString](https://evroaming.org/app/uploads/2021/11/OCPI-2.2.1.pdf#types_cistring_type) which: 

> Only printable ASCII allowed. (Non-printable characters like: Carriage returns, Tabs, Line breaks, etc are
not allowed)

That is too broad set of characters. We encountered a problem upon receiving a tariff which contained "/" within tariff ID. Valid ID according to OCPI, but tough to handle (not to look far: endpoint like `/api/tariff/{tariff_id}`) .
IMO IDs (and potentially other fields) should be more restrictive than current guidelines for [CIString](https://evroaming.org/app/uploads/2021/11/OCPI-2.2.1.pdf#types_cistring_type).

**Comment by reinierl** [comment]
We can't make breaking changes to 2.x for such issues - the spec is clear enough and your implementation is not compliant.

We will consider your feedback for OCPI 3.0. If you'd like to participate in its development you can join [the EV roaming foundation](https://evroaming.org/about-us/).

**Comment by mbayings** [comment]
@nowosprz Thank you for your feedback. The fact that the protocol allows it, does not mean it is also the best way to use it. To me it is strange if that companies use "/", as that will also generate issues in their systems and in many other systems. But their might be situations where it is possible to use it. We try to make the protocol broadly usable. It is possible that this is to broad, but in most situations it is OK and need good implementation from companies. We can also consider to make a comment in the protocol that in situations where CiString is used, a few specific characters are not advisable and likely to use.
My suggestion is to contact that organization and discuss it with them.

**Comment by nowosprz** [comment]
Well, obviously it will be fixed in our system. And @ahzf the example I provided is tip of the iceberg if you allow too much.

At the same time I believe that (and here agree with @reinierl ) that should be considered for OCPI 3.0. Consider how difficult it sometimes is to convince customer of yours not to do something that is not the best practice, but allowed by a specification.
