### ISSUE TITLE
CdrToken in CDR example doesn't contain (new) mandatory fields

### ISSUE THREAD

**Issue by markvandenbergh** [ocpi/ocpi#384]
OCPI 2.2.1 specifies that CdrToken should contain country_code and party_id:

> Added mandatory country_code and party_id fields to make sure that a CdrToken uniquely identifies a charge token

The CdrToken in the CDR example in 10.3.1.1 doesn't contain those fields:

```
  "start_date_time": "2015-06-29T21:39:09Z",
  "end_date_time": "2015-06-29T23:37:32Z",
  "cdr_token": {
    "uid": "012345678",
    "type": "RFID",
    "contract_id": "DE8ACC12E46L89"
  },
  "auth_method": "WHITELIST",
  "cdr_location": {
```

**Comment by reinierl** [comment]
Should be fixed on the release-2.2.1-bugfixes branch now!
