### ISSUE TITLE
OCPI Slack forum

### ISSUE THREAD

**Issue by Llocer** [ocpi/ocpi#387]
I'm sorry for a few off-topic issue. 

I'm trying to post a message in any OCPI related forum to announce the delivery of an open source set of librarians with complete implementations of OCPP, OCPI protocols and CPO node ( see [https://github.com/Llocer](https://github.com/Llocer) ). However, forum at [Slack](https://ocpi.slack.com/) seems closed to public users. Any hint how to share this information?

**Comment by reinierl** [comment]
You can join there and I can approve you. I will check if we can make it open.

**Comment by Llocer** [comment]
Thanks for your answer. When you say "You can join there" do you mean where ?

**Comment by mbayings** [comment]
Hi, I tried to make it now as open as possible, but think that it still requires some kind of request or link to use it. It is not our intention to limit the accessibility, but we are of course bound to the restrictions and possibilities of Slack.

**Comment by reinierl** [comment]
This link should let you join for now: https://join.slack.com/t/ocpi/shared_invite/zt-17wchyp8w-isW7hE4er6NTJ09L0~9flA

**Comment by Llocer** [comment]
Thanks a lot @reinierl  and @mbayings, the link you provided allowed me to join Slack.
Now learning the structure of the forum folders, before to write anything.
Thanks again.
