### ISSUE TITLE
How does TIME and ENERGY price_components work when they are in different TariffElements ?

### ISSUE THREAD

**Issue by anasquazbary** [ocpi/ocpi#389]
Hello ! I have a question concerning how price_components work when they are in different TariffElements.
Let's consider this example : 
The charging lasts 2 hours and the EV receives 10 kWh.

The tariff_elements are  : 
```
{
	"elements": [
		{
			"price_components": [
				{
					"type": "ENERGY",
					"price": 1,
					"step_size": 1
				}
			]
		},
		{
			"price_components": [
				{
					"type": "TIME",
					"price": 2,
					"step_size": 1
				}
			]
		}
	]
}
```

I am not sure which one of these 2 results is correct : 
result A : we consider only the first tariff_element since there is no restrictions, so the final cost is : 10kwh x 1 = 10€
result B : we consider the first tariff_element for ENERGY and the also the second one for TIME since the first one does not contains TIME price component and the final cost will be calculated this way : 10kwh x 1 = 10 for ENERGY plus 2hours x 2 = 4€. So the final cost is 14 €

Thank you for reading this question.

**Comment by SoloVeniaASaludar** [comment]
From 2.2.1 specification "you can have an ENERGY element and TIME element active at the same time, but only the first valid element of each". 

Thus, the answer to your question is "result B". The different elements in your tariff example are related to different tariff dimensions, they can apply both at same time.

**Comment by anasquazbary** [comment]
@SoloVeniaASaludar All right it is clear now thank you for you answer !
