### ISSUE TITLE
How to interpret Credit CDR workflow

### ISSUE THREAD

**Issue by julius-yang** [ocpi/ocpi#399]
I am implementing the CDR workflow as an eMSP.  I don't understand this sentence.

> After having sent the Credit CDR, the CPO can send a new CDR with a new unique ID and the fields: credit and credit_reference_id omitted.

Does it mean this?

> CDR `abc123` for session_id `a1` -> total_cost 10.00
> CDR `xyz789` for session_id `a1` with credit_reference_id `abc123` -> total_cost -5.00 (partial refund)
> CDR `jkl567` for session_id `a1` and no credit_reference_id -> total_cost 5.00

If so then I have some questions:

1.  The third CDR seems to be optional ("the CPO can send").  What is the purpose of the CPO sending this?
2.  How does the eMSP correctly calculate the amount actually billed to the user for this session?  Adding the CDR total costs in this scenario still results in the amount of 10.00.  If only full credits are possible then this problem goes away, but that seems like an unreasonable restriction.  We could look only at the last CDR for the session ... but then if this third "summary" CDR is optional, then we wind up calculating the total cost as -5.00.

**Comment by julius-yang** [comment]
My coworker suggested this interpretation:

CDR 1 -> Bill user 10.00
CDR 2 -> Credit user 10.00

If performing a full refund of CDR 1, then no third CDR is ever delivered.
If the CPO is amending the amount to bill the user, then the third CDR is sent.

CDR 3 -> Bill user new amount (could be more or less than 10.00)

**Comment by reinierl** [comment]
Without having read the spec closely, I think your co-worker's interpretation makes sense.

In fact we could model crediting a CDR as a simple operation without extra field about "how much" you credit. The crediting operation just invalidates the whole previous CDR and removes any financial obligations that the CDR originally created. That cleans the slate then for the CPO to send a new CDR that overrides the credited one.

In fact that could be turned into one operation: deliver a new CDR which mentions an older one to be overridden.

**Comment by reinierl** [comment]
Yes indeed, the specification agrees with your coworker:

> This credit CDR SHALL have a different CDR.id which can be a completely different number, or it can be the id of the original CDR with something appended like for example: -C to make it unique again. To indicate that a CDR is a Credit CDR, the [credit](https://github.com/ocpi/ocpi/blob/release-2.2.1-bugfixes/mod_cdrs.asciidoc#mod_cdrs_cdr_object) field has to be set to true. The Credit CDR references the old CDR via the [credit_reference_id](https://github.com/ocpi/ocpi/blob/release-2.2.1-bugfixes/mod_cdrs.asciidoc#mod_cdrs_cdr_object) field, which SHALL contain the [id](https://github.com/ocpi/ocpi/blob/release-2.2.1-bugfixes/mod_cdrs.asciidoc#mod_cdrs_cdr_object) of the original CDR. The Credit CDR will contain all the data of the original CDR. Only the values in the [total_cost](https://github.com/ocpi/ocpi/blob/release-2.2.1-bugfixes/mod_cdrs.asciidoc#mod_cdrs_cdr_object) field SHALL contain the negative amounts of the original CDR.

**Comment by julius-yang** [comment]
> Without having read the spec closely, I think your co-worker's interpretation makes sense.
> 
> In fact we could model crediting a CDR as a simple operation without extra field about "how much" you credit. The crediting operation just invalidates the whole previous CDR and removes any financial obligations that the CDR originally created. That cleans the slate then for the CPO to send a new CDR that overrides the credited one.
> 
> In fact that could be turned into one operation: deliver a new CDR which mentions an older one to be overridden.

OK, we will try to work with this.  However I'd like to present our use case.

We bill drivers immediately instead of invoicing them periodically.  Here is our flow:

1) Driver activates session
2) We perform an authorization hold on the driver's credit card
3) Session ends
4) We receive a CDR to bill the driver $10.00.
5) We capture $10.00 from the driver immediately.

If there is a credit, then the subsequent flow would be:

6) Receive CDR for same session with -$10.00.
7) Refund the initial $10.00 capture.
8) Receive CDR for the same session with $8.00 (or $12.00, if the CPO deems the user to have underpaid -- I would hope this never occurs)
9) Bill the driver for $8.00 (or $12.00)

Step 9 has two complications:
a) The driver's credit card may be at the credit limit and cannot bill the driver $8.00.  Even after a credit of $10.00 the bank may still not let a card at its limit be used.
b) The driver will possibly be rebilled many days after the initial session.  That is confusing to see on a credit card statement:
2022-06-20 $10.00 for Foo
2022-07-15 -$10.00 credit
2022-07-15 $8.00 for Foo
User complains they did not charge at Foo on July 15.

I would prefer to see this flow, assuming that the CPO can never bill the user for more than initially billed:

1) Receive CDR for $10.00
2) Bill user for $10.00
3) Receive CDR for -$3.00
4) Credit user $3.00
5) Receive CDR for -$7.00
6) Credit user $7.00 (session is now completely free)

As I said, we will implement our flow assuming that only full credits are possible, but I hope that the advantages of the desired flow are apparent and will be possible in future OCPI versions.

**Comment by reinierl** [comment]
You seem to have a good use case there. I will bring it up in the OCPI 3.0 development process.

**Comment by mbayings** [comment]
Hi. This is not directly a protocol issue but more in general how to deal with CDRs and credit-CDRs.
A CDR must reflect the transaction and be in line with the information that user received or could see/receive before the transaction. That in theory could also lead to situation where not enough is put in the CDR and that a new CDR is needed with higher amount. I would say that the only acceptable situation here would be when the CDR is by mistake using a tariff of 0 (zero) Euro/dollar. And that must then also be 'known' by the user. And otherwise, I would not recommend correcting the CDR to a higher amount. This is also in line with jurisdiction where only if the consumer could see and understand that an amount is far too low to be true and clearly a mistake, these kind of corrections can be done. 

From a personal point of view I would say that a full credit of the CDR and then create a new CDR with the correct amount and values is easier and more clear to the user as the CDR contains also time or volume (kWhs) and not just an amount. 

In any case the situation and example of your first comment where you first deduct 5 and then add 5 again, does not make sense. So that last CDR jkl567 for session_id a1 and no credit_reference_id -> total_cost 5.00, should not be there. 

Not sure if anything needs to be changed in the protocol as I think it is more between parties and how to deal with credit CDRs and invoices in general and between the parties. But I might be missing something.

**Comment by julius-yang** [comment]
My first example was based on an incorrect interpretation of the spec and can be ignored.

As currently designed, whenever we receive a CDR for a negative amount, it will always be the full amount of the original CDR, and we should refund the full initial charge.  Receiving any positive CDR implies that we should bill that driver that amount, regardless of what has happened before.  Here are some edge cases for such a design.  I am not suggesting that the spec should handle all edge cases, no matter how unlikely, but I think it is worth thinking through possible situations to see if other approaches are worth exploring.  And again, I am focused on our particular use case where we bill or credit the driver as soon as possible.

**Order matters**
1. Receive two positive CDRs in a row, with no intervening refund (e.g. a refund CDR was missed)
2. Receive two negative CDRs in a row, with no intervening billing (e.g. an amended positive CDR was missed)
3. Receive a negative CDR before a positive CDR (e.g. race conditions on the CPO side)

I don't think last_updated helps in this case, because a given CDR cannot be amended; it is not a case of comparing two incoming requests for the same object to see whether we can discard one of the requests.

**Accounting**
1. The amount billed to the driver is the most recent CDR for the Session ... except if the last CDR for the session is negative, the amount billed is actually zero (because it always a full refund).

I am suggesting a more flexible option where a CPO can send a CDR with any amount, positive or negative, and that amount is credited or billed to the driver regardless of other CDRs.  If a CPO wants to continue performing full credits followed by a new amount to bill as specified in 2.2, they can.  I acknowledge that a CPO might want to bill the user more than originally billed.  I think that would lead to pretty unhappy users and I hope that a CPO would never, ever do that, but allowing it within the spec seems reasonable to me.

Thanks for reading.
