### ISSUE TITLE
Add a field for exchanging a link to the terms of use of a chargepoint

### ISSUE THREAD

**Issue by rutgerplantenga** [ocpi/ocpi#4]
The operator's Terms and Conditions of using a public chargepoints may apply directly to the EV-driver (depending on how this is set up in the bi-lateral contract between operator and provider). To allow the service provider to present these T&C to the driver, it should be possible to exchange a link to the chargepoint's Terms & Conditions (provided by operator). 

As provider may actively ask/require driver to accept terms before charging it is important that the T&C are not exchanged as a free/random text field but as a field dedicated to T&C.

**Comment by RobertdeLeeuw-IHomer** [comment]
Is possible with OCPI 2.1
