### ISSUE TITLE
OCPI Workshop #12 (2015-08-28)

### ISSUE THREAD

**Issue by simonphilips** [ocpi/ocpi#40]
For archival purposes only: a photograph describing the initial session flow and API. This is updated by OCPI Workshop 13 which contains all the relevant information (see #38).

![img_20150828_132033](https://cloud.githubusercontent.com/assets/3263809/9712918/55ac415a-554e-11e5-9224-c52e0b6c93d9.jpg)
## Summary

The idea was to create a session and then update that object until it's finished. At that point the session must be stopped by an explicit call (the create_cdr property) which would inform the eMSP that the session object is frozen and that it has become a CDR.

CDR's are records and must have a different API (hence the /cdrs endpoint) that allow querying, invalidating and correcting a CDR. There is also a status 'DISPUTED' to facilitate that end.

In the next workshop (#13) we improved these concepts and constructed something more consistent.
## A note about VAT

We decided not to include the VAT into the CDR (unlike EMI3) for the following reasons:
- VAT is an invoice property. CDR (charge detail records) are not invoice lines, they are records between CPO and eMSP. It is up to the eMSP to calculate the VAT for their users, not the CPO.
- Call detail records do not include VAT either.
- VAT law is a very complicated beast and varies per country, we want to avoid complicating OCPI.

When, at some point in the future, it turns out that including an extra field for the VAT is a good idea then we will reconsider it.

**Comment by poohsen** [comment]
another result of the workshop was a draft of the sessions chapter, which can be found here:
https://github.com/ocpi/ocpi/commit/753e13da8070b4aa9c7e0a6cae72fb42f951d0e1
