### ISSUE TITLE
Clarification for OCPI 2.2.1 section 6.2.2

### ISSUE THREAD

**Issue by julius-yang** [ocpi/ocpi#403]
The Endpoint class requires an InterfaceRole enum in the `role` property.  However there is also a note which says "for the credentials module, the role is not relevant as this module is the same for all roles".  The phrase "not relevant" confuses the situation.  What is the correct intended implementation?

1) "credentials" Endpoint class has no `role` property
2) "credentials" Endpoint class has a `role` property with null value
3) "credentials" Endpoint class has a `role` property, but the value is either SENDER or RECEIVER, and the value should be ignored
4) two "credentials" Endpoint classes are defined, one with role SENDER and one with role RECEIVER
5) Other

**Comment by ahzf** [comment]
As this module is inherently insecure, as the client can send what it wants and thus inpersonate everyone... you have to build trust your own way anyway, e.g. depending on the auth token. So:
1. is an invalid message
2. is an invalid message
3. this I do not understand, perhaps you could explain it a bit more 
4. best way to go is one role per auth token

**Comment by julius-yang** [comment]
> As this module is inherently insecure, as the client can send what it wants and thus inpersonate everyone... you have to build trust your own way anyway, e.g. depending on the auth token. So:
> 
> 1. is an invalid message
> 2. is an invalid message
> 3. this I do not understand, perhaps you could explain it a bit more
> 4. best way to go is one role per auth token

My question does not have to do with authorization of the request.  It has to do with how the response to a version details HTTP request should be structured per section 6.2.2.

GET https://ocpi.server.com/2.2.1/details (section 6.2)
```
{
    "data": {
        "version": "2.2.1",
        "endpoints": [
            {
                "identifier": "credentials",
                "url": "https://ocpi.server.com/2.2.1/credentials",
                "role": ???
            }
        ]
    }
}
```

**Comment by reinierl** [comment]
@julius-yang I'm interpreting it as your option (3). 

There has to be a "role" field because the cardinality is specified as "1". The only possible values are SENDER and RECEIVER. And then the sentence you quote says that whether it's "SENDER" or "RECEIVER" is irrelevant for the credentials module.

I can bring this up in the next OCPI Development Working Group call to see if people agree with that interpretation. If so we can update the specification text to reflect that more clearly.

**Comment by reinierl** [comment]
Also, in OCPI 3.0 the whole connection setup and connection authentication system is reworked so this oddity is gone.

**Comment by julius-yang** [comment]
Thank you for the clarification.

**Comment by reinierl** [comment]
We have improved the documentation for this: https://github.com/ocpi/ocpi/commit/a6d36f5dddcc623d0b7c8d8e74f4c8f73c06d5d6
