### ISSUE TITLE
OCPI handshake frequency

### ISSUE THREAD

**Issue by quant-daddy** [ocpi/ocpi#407]
The OCPI credentials module is used for handshake/registration to exchange tokens that are used for rest of the communication between the CPO and eMSP. As an eMSP, do I need to do this handshake every time our server starts or should this be a manual process that is done every once in a while (such as when the OCPI version if updated?)

**Comment by reinierl** [comment]
It's typically a manual process that is done every once in a while.

We know it's not really up to the state of the art in security and it will be dramatically improved in OCPI 3.0.
