### ISSUE TITLE
Not an issue just a question for HUB implementation 

### ISSUE THREAD

**Issue by Aashutosh7138** [ocpi/ocpi#408]
It’s somewhat unclear about how would a client send a request to HUB. what should be the endpoint specification
Like if an eMSP wants a location data from multiple CPO what endpoint it should use for HUB GET all .
And for all routing request what should be the endpoint of HUB
And should a HUB store mapping of endpoint for each connected client to route the request to that endpoint ?

**Comment by reinierl** [comment]
> Like if an eMSP wants a location data from multiple CPO what endpoint it should use for HUB GET all .

They should just use the Locations endpoint that's given to them in the version module (https://github.com/ocpi/ocpi/blob/release-2.2.1-bugfixes/version_information_endpoint.asciidoc) . Nothing special going on there.

> And for all routing request what should be the endpoint of HUB

The same as for GET ALL above: just the endpoint returned from the Version endpoint of the Platform that the Hub is hosted on.

If you need to supply a Country Code and a Party ID in the URL, you can use those of the Hub that are given to you in `role` field of the Credentials object (https://github.com/ocpi/ocpi/blob/release-2.2.1-bugfixes/credentials.asciidoc#131-credentials-object).

> And should a HUB store mapping of endpoint for each connected client to route the request to that endpoint ?

Yes, definitely.
