### ISSUE TITLE
Opening Times... till next day

### ISSUE THREAD

**Issue by ahzf** [ocpi/ocpi#413]
Would the following time period be allowed in OCPI?

```
      {
        "weekday": 2,
        "period_begin": "08:00",
        "period_end": "02:00"
      }
```

Or would it be required to splitt this up into two entries?

```
      {
        "weekday": 2,
        "period_begin": "08:00",
        "period_end": "00:00"
      }
      {
        "weekday": 3,
        "period_begin": "00:00",
        "period_end": "02:00"
      }
```

**Comment by Alan-Stewart** [comment]
I could've sworn there was a note about "if period_end <= period_begin then it is assumed to wrap through midnight (00:00)" but I'll be danged if I can find such a phrase.  Perhaps that is just something we have had to implement, which would not be strictly 100% OCPI compatible.

**Comment by reinierl** [comment]
I have the same dim recollection as @Alan-Stewart. That applies to Tariffs though.

I guess it makes sense to add similar wording to Opening Hours as well, but I think that's a a functional change so I can't just add it to the 2.2.1 bugfixes.

Is this a real business problem for you @ahzf or are you just theorizing?

**Comment by ahzf** [comment]
@reinierl Well charging station owners send be such opening times and I ran into some implementation issues. So I asked Hubject, and they did not like the first version for their protocol... me neither... so I asked you guys ;)

**Comment by 314eter** [comment]
In the second case,
```
{
    "weekday": 2,
    "period_begin": "08:00",
    "period_end": "00:00"
}
```
is not allowed either, since `00:00` is before `08:00`. So you'll have to use `23:59`, which is quite ugly.

The easiest solution (in a next version of OCPI) would be to allow 8:00 - 2:00, and always assume that `period_end` is between 1 minute and 24 hours after `period_begin`.

In case a location is open from Monday 8:00 to Wednesday 2:00, you'll still have to split it up in `8:00 - 0:00`, `0:00 - 0:00` and `0:00 - 2:00`.

**Comment by ahzf** [comment]
Well, because of your last sentence it would like to avoid your solution in the sentence before, because this just add complexity and not much benefit.

**Comment by 314eter** [comment]
It still fixes the problem that you can't do `8:00 - 0:00`. But that can be done by explicitly allowing it as a special case too.

**Comment by ahzf** [comment]
But when I implement it I would asap "normalize" this after importing it, because it makes lookups very very inefficient. So to say, I would never export this again. So what would be a real benefit of it? I guess even humans would do "lookup errors" when this is allowed ;)

**Comment by reinierl** [comment]
Allowing the opening times for one day to talk about the next day opens up another pandora's box of edge cases I think.

So if we just allow "00:00" as a `period_end` value, as a special case to signify "until end of day"? That solves all problems isn't it?

Then this becomes possible:

```
      {
        "weekday": 2,
        "period_begin": "08:00",
        "period_end": "00:00"
      }
      {
        "weekday": 3,
        "period_begin": "00:00",
        "period_end": "02:00"
      }
```

and this remains invalid as it already is:

```
      {
        "weekday": 2,
        "period_begin": "08:00",
        "period_end": "02:00"
      }
```

Or well, we get more problems if the nightly closing window starts after midnight. So if we have that opening from 00:00 to 02:00 on weekday 3, how do we say that the Location will open again on 10:00 of weekday 3 until 22:00 of weekday 3?

**Comment by reinierl** [comment]
In OCPI 3.0, we'll go with @314eter 's and @reinierl's proposal to solve this by allowing "00:00" as an end time meaning "until midnight at the end of the day" and allowing multiple opening hours entries per weekday.

In OCPI 2.2.1, everything will stay as it was of course.
