### ISSUE TITLE
About SENDER-RECEIVER defined in interfaceRole enum and Credentials module

### ISSUE THREAD

**Issue by emintokluu** [ocpi/ocpi#414]
### Typical OCPI implementations per Role ([OCPI 2.2.1 - 2.3.1](https://evroaming.org/app/uploads/2021/11/OCPI-2.2.1.pdf#2.3.1.%20Typical%20OCPI%20implementations%20per%20Role))
 is specified as follows:
`The following table shows the typical modules implemented by the different roles. These are not required. The table shows the
typical communication role: Receiver, Sender or Both....`

### InterfaceRole enums ([OCPI 2.2.1 - 6.2.3](https://evroaming.org/app/uploads/2021/11/OCPI-2.2.1.pdf#6.2.3.%20InterfaceRole%20enum))
is specified as follows:
| Value    | Description                                                                                                                                   |
|----------|-----------------------------------------------------------------------------------------------------------------------------------------------|
| SENDER   | Sender Interface implementation. Interface implemented by the owner of data, so the Receiver can Pull information from the data Sender/owner. |
| RECEIVER | Receiver Interface implementation. Interface implemented by the receiver of data, so the Sender/owner can Push information to the Receiver.   |

### Credential ([OCPI 2.2.1 - 7.3.1](https://evroaming.org/app/uploads/2021/11/OCPI-2.2.1.pdf#7.1.1.%20Registration))
is specified as follows:
`To start the exchange of credentials tokens, one platform has to be selected as Sender for the Credentials module....`

As you can see, the definition of SENDER-RECEIVER is defined in 3 different ways in 3 different places.
Looking at the examples below, we see that an interfaceRole is defined for the Credential module.
According to the OCPI Protocol, SENDER-RECEIVER is defined differently for credential and for other modules with interfaceRole enum. But in the version/details section, we see that these definitions are combined with interfaceRole. This part is confusing.

For the CPO to NSP example, the CPO location module must be the sender, and the NSP must be the receiver. But for the credential module, there can be a RECEIVER for the CPO because this operation for credential module is defined as both. We cannot define interfaceRole in other modules with the Receiver definition specified in the Credential module. 

Can you give detailed information about this issue?

#### [OCPI 2.2.1 - 6.2.3](https://evroaming.org/app/uploads/2021/11/OCPI-2.2.1.pdf#6.2.6.1.%20Examples)
```
{
    "version": "2.2",
    "endpoints": [
        {
            "identifier": "credentials",
            "role": "SENDER",
            "url": "https://example.com/ocpi/2.2/credentials/"
        },
        {
            "identifier": "locations",
            "role": "SENDER",
            "url": "https://example.com/ocpi/cpo/2.2/locations/"
        }
    ]
}
```
```
{
    "version": "2.2",
    "endpoints": [
        {
            "identifier": "credentials",
            "role": "RECEIVER",
            "url": "https://example.com/ocpi/2.2/credentials/"
        },
        {
            "identifier": "locations",
            "role": "SENDER",
            "url": "https://example.com/ocpi/cpo/2.2/locations/"
        },
        {
            "identifier": "tokens",
            "role": "RECEIVER",
            "url": "https://example.com/ocpi/cpo/2.2/tokens/"
        },
        {
            "identifier": "locations",
            "role": "RECEIVER",
            "url": "https://example.com/ocpi/msp/2.2/locations/"
        },
        {
            "identifier": "tokens",
            "role": "SENDER",
            "url": "https://example.com/ocpi/msp/2.2/tokens/"
        }
    ]
}
```

**Comment by reinierl** [comment]
Hi @emintokluu, did you see the latest wording at the `release-2.2.1-bugfixes` in this repository? It can be found here: https://github.com/ocpi/ocpi/blob/release-2.2.1-bugfixes/version_information_endpoint.asciidoc#122-endpoint-class . Especially this bit:

> Note | for the credentials module, the value of the role property  is not relevant as this module is the same for all roles. It is advised  to send "SENDER" as the InterfaceRole for one’s own credentials endpoint  and to disregard the value of the role property of the Endpoint object  for other platforms' credentials modules.
