### ISSUE TITLE
connector/tariff relationship

### ISSUE THREAD

**Issue by julius-yang** [ocpi/ocpi#415]
Section 8.3.3 says a Connector can have one or more tariff ids.  However nothing in the spec says that the CiString in the `tariff_ids` attribute has to exist when fetching Tariff objects.

Is it an implied requirement that if Locations present a Connector with a Tariff id, that the Tariff exist when fetching Tariff objects?

If not, how should an EMSP handle a Connector defining a Tariff id that it can't retrieve?

**Comment by reinierl** [comment]
I don't think OCPI really says anything about that. The most reasonable thing for the eMSP to do would be to report the situation as it is: the CPO reports that some tariff applies, but we don't know what that tariff is.

**Comment by julius-yang** [comment]
OK thanks.  I viewed it as a relationship like a foreign key constraint, but in the future if the CiString points to no Tariff then we will treat it as if it didn't exist.
