### ISSUE TITLE
Token Response in Sender Interface

### ISSUE THREAD

**Issue by HamedAkhavan** [ocpi/ocpi#417]
Hi,
what is the response in the [POST method (Token Sender interface)](https://github.com/ocpi/ocpi/blob/2.2.1/mod_tokens.asciidoc#post-method) when a token is not known to the EMSP? why we have different responses for the same condition. below are the two different responses in the documents for the same condition. is there any difference in conditions?
1- 
> When the eMSP does not know the Token, the eMSP SHALL respond with an HTTP status code: 404 (Not Found).

2-
> If the token is not known, the response SHALL contain the status code: 2004: Unknown Token, and no data field.

**Comment by evcharger** [comment]
Hello,
I think you are looking at two different status fields/codes. As per OCPI documentation:  https://github.com/ocpi/ocpi/blob/master/status_codes.asciidoc 
"There are two types of status codes:

    Transport related (HTTP)

    Content related (OCPI)
...
Requests that reach the OCPI layer SHOULD return an OCPI response message with a status_code field as defined below."

I think that means that when a token is not known, the HTTP status must be 404 (not found) and in the "status_code" of the response the status must be 2004: Unknown Token.

**Comment by HamedAkhavan** [comment]
> Hello, I think you are looking at two different status fields/codes. As per OCPI documentation: https://github.com/ocpi/ocpi/blob/master/status_codes.asciidoc "There are two types of status codes:
> 
> ```
> Transport related (HTTP)
> 
> Content related (OCPI)
> ```
> 
> ... Requests that reach the OCPI layer SHOULD return an OCPI response message with a status_code field as defined below."
> 
> I think that means that when a token is not known, the HTTP status must be 404 (not found) and in the "status_code" of the response the status must be 2004: Unknown Token.

@evcharger thanks for clarification
