### ISSUE TITLE
Support for Response Object in case of PUT and PATCH to emsp for Session and Charging period

### ISSUE THREAD

**Issue by statiqantriksh** [ocpi/ocpi#421]
@RobertDeLeeuw  @reinierl 
Unclear from the documentation on the expected response from an emsp when

PUT for the session object
PATCH for the charging periods

**Comment by juherr** [comment]
@statiqantriksh You close the issue before having a response. I suppose the response should be HTTP 200 with the usual OCPI response but the documentation is not clear enough. Do you find the answer?

**Comment by statiqantriksh** [comment]
@juherr Yes the http response part is clear, I'm more of looking for a data object or ID that is returned as an acknowledgement which can then be stored by the CPO system, This way we can have a log trail that can help in case of a dispute.

**Comment by reinierl** [comment]
I think the OCPI response with a success code should be seen as the acknowledgement.

The acknowledgement doesn't have an identifier of just that acknowledgement.

Every request/response exchange in OCPI 2.2.1 does have a request ID in the HTTP headers that you can store to have a reference to the acknowledgement from the other party.

Also, if disputes arise, they will most likely not be about whether the HTTP request was received. The dispute will most likely be about whether the data in the request is correct. That is another question and it's one that you can't really expect the Session receiver to answer within the few milliseconds they have before they have to send the HTTP response. For OCPI 3.0 we are working on a mechanism for CDR receivers to automatically notify CDR senders that they dispute one of their CDRs. This will work asynchronously so receivers can receive the data, validate it, and file disputes seconds, hours or perhaps even days later.

**Comment by juherr** [comment]
@statiqantriksh 
Do you have the documentation reference?
Because the HTTP response was not so clear and my first implementation used HTTP 204 before someone told me that 200 is expected.

@reinierl 
For the record, the point you refer is https://github.com/ocpi/ocpi/blob/master/transport_and_format.asciidoc#12-unique-message-ids

**Comment by reinierl** [comment]
@juherr I can't immediately find a specification of that in an obvious place. That means it's probably just unspecified, and you would have to accept every possible value or lack thereof, and send something that seems intuitive. I think `null` fits best.

A production OCPI implementation that I have access to also leaves `data` unset in this case and that works with a whole bunch of partners worldwide.

**Comment by reinierl** [comment]
Oh and agree that this is unfortunate and that the specification shouldn't leave things like this undefined. In OCPI 3.0 the whole data replication mechanism will be different though so at this point there's no point in fixing it anymore.

**Comment by juherr** [comment]
@reinierl Why not update the current documentation with some MAY recommendations as you did 2 messages ago?
It is not so obvious to dig into issues to find answers that should be located in the documentation. WDYT?

**Comment by reinierl** [comment]
@juherr That could work indeed. I'll add some note or MAY requirement to a 2.2.1-d2 release that we plan to release shortly.

**Comment by reinierl** [comment]
@juherr I added a note on the `release-2.2.1-bugfixes` branch: https://github.com/ocpi/ocpi/commit/5277cb90caff15f42b0d3a45104c93466d59c5a2
