### ISSUE TITLE
Question regarding roles and CdrToken

### ISSUE THREAD

**Issue by j-carvalho** [ocpi/ocpi#425]
Hi there,

we are currently working on the Sessions module and one question came up regarding the cdr_token object.

From our understanding of the protocol, we can have cases where one Session object might be relevant for multiple receivers: eMSP and SCSP / only SCSP.

And a charging sessions could have been originated via OCPI (e.g. eMSP) or directly by one of our drivers. And this is our current confusion with the cdr_token object. 

When the charging session originated from one of our CPO drivers and we need to send it via OCPI to non eMSP roles (e.g. SCSP), what information should we put in this cdr_token object? Would "we" be the MSP/eMSP in this scenario?

**Comment by reinierl** [comment]
The OCPI specification ultimately just specifies the format. You can put in the cdr_token whatever you want. If it is not relevant to the SCSP _who_ is charging, it is fine in my view to send dummy data that fit the syntactic requirements.
