### ISSUE TITLE
Empty charging periods when tariff only have FLAT element

### ISSUE THREAD

**Issue by sssmolarkiewicz** [ocpi/ocpi#426]
OCPI 2.2 defines `charging_periods` inside `CDR` object with cardinality `+`, meaning there have to be at least one element. The same goes for `dimensions` inside `charging_periods`. `CdrDimensionType` doesn't allow FLAT dimension though. What should I do when there is only one tariff element, with one, FLAT price component? Should I create a "fake" charging period with ENERGY type and volume of whole consumed energy, or TIME type with volume of the duration of charging session?

Our application handles both OCPI 2.2 and 2.1.1 - in the latter FLAT is a valid charging period dimension. Because of that (and also for simplicity of calculations) we store FLAT charging periods. This becomes a problem when we send such CDR to OCPI 2.2 partner - we need to filter out those dimensions. But what should we do when those are the only dimensions of the CDR?

**Comment by reinierl** [comment]
There must be more dimensions of a CDR, even if you're not charging for them? I'd just include free time and/or energy dimensions to make the CDR valid.

**Comment by sssmolarkiewicz** [comment]
>There must be more dimensions of a CDR, even if you're not charging for them?

We create charging period dimensions based on price components of tariff element used active during given charging period. So if FLAT is the only price component, it will also be the only charging period dimension.

**Comment by reinierl** [comment]
> > There must be more dimensions of a CDR, even if you're not charging for them?
> 
> We create charging period dimensions based on price components of tariff element used active during given charging period. So if FLAT is the only price component, it will also be the only charging period dimension.

Then I think you have to change the way you create charging period dimensions in order to be OCPI 2.2.1 compliant.

**Comment by sssmolarkiewicz** [comment]
OCPI documentation only states that
> A CPO SHALL at least start (and add) a ChargingPeriod every moment/event that has relevance for the total costs of a CDR.

If tariff does not bill time or energy, then events related to time or energy are not relevant to the total cost of a CDR. How exactly do you mean our way of creating charging periods should be changed? Would it be enough to add a time dimension for entire session when there is no other valid (non-FLAT) dimension?
