### ISSUE TITLE
EVSE and Location Lifecycle: Deletion

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#43]
While restructuring the documentation, I realized that it was not quite clear how to delete an EVSE.

We have parallel push and pull mode. The description ([even before my commit](https://github.com/ocpi/ocpi/blob/f211b5ecb77eca47588aecaf1aeba672db993f1e/locations.md#example-delete-an-evse)) read:
> An EVSE can be deleted by updating its valid_until property.

This means for push mode it is quite clear. While the pull mode could find two situations:

 1. The formerly known object does now have a a `valid_until` date in the past.
 2. The formerly known object is not contained in the result any more.

The second situation was not described. My current description is a "GET and diff", see [here](https://github.com/ocpi/ocpi/blame/master/bo_locations_and_evses.md#L43-L48): 

> Providers who do not support push mode need to call GET on the operator's location endpoint and filter for non-existant master objects. Each of their own valid inheritances (B) which do not have a corresponding master object in a later GET-request have to be marked as invalid with the timestamp of the request.

*Is this how it was intended?*

**Comment by simonphilips** [comment]
Actually, the valid_from and valid_until are no longer used. When comparing with OCHP, it was decide to use the status field for marking an EVSE as invalid: EVSE.status = INOPERATIVE. To inform that an EVSE is scheduled for removal, the status_schedule field can be used. The valid_from and valid_until fields must be removed from the spec.

So in this case: any missing EVSE's in the GET response must have their status set to INOPERATIVE by the eMSP.  I would suggest to avoid the master/inheritance description as it only adds more confusion.
