### ISSUE TITLE
Possible typos in the registration handshake figure

### ISSUE THREAD

**Issue by luisgc93** [ocpi/ocpi#430]
I was reading through the registration process and got a bit confused by this part of figure 22:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/32971373/230339039-949aae29-b86b-400d-8885-fda891cf64a8.png">

On the left it says the Sender generates CREDENTIALS_TOKEN_C but the arrow and description on the right hand side indicate that this is happening on the Receiver.

Similarly, it says the POST credentials request comes from the Receiver (_"returns it in the response to the HTTP POST credentials request from the Receiver above"_) but the arrow in the POST request above (at the top of the screenshot) goes from left to right (the request is being made by the Sender). 

Sorry if I'm missing anything here, appreciate any input.

**Comment by reinierl** [comment]
This has been fixed in the Asciidoc source code since 2021-07-01. Which version of OCPI are you looking at?

**Comment by luisgc93** [comment]
> This has been fixed in the Asciidoc source code since 2021-07-01. Which version of OCPI are you looking at?

Thanks! My bad!
