### ISSUE TITLE
Clarification of GET /locations?date_from behavior

### ISSUE THREAD

**Issue by julius-yang** [ocpi/ocpi#432]
If a Location has 6 EVSEs where four EVSEs have last_updated two days ago and two of them have last_updated from one day ago, and I pull all Locations where date_from is 36 hours ago, what should I see in the Location?

Edit: Location has last_updated from one day ago of course.

1) only the 2 EVSEs where last_updated is more recent than 36 hours ago
2) all 6 EVSEs

**Comment by luisgc93** [comment]
I think the location should be fetched with all EVSEs since you're filtering for location updated

**Comment by reinierl** [comment]
I would expect to see 6 EVSEs. You're pulling Locations, not EVSEs. I didn't check the specification wording though.

**Comment by reinierl** [comment]
If I do check the specification wording it says what I want it to say though. A familiar snippet:

> If the optional parameters {date_from} and/or {date_to} are provided, only Locations with (last_updated) between the given {date_from} (including) and {date_to} (excluding) will be returned. In order for this to work properly, the following logic MUST be implemented accordingly: If an EVSE is updated, also the 'parent' Location’s last_updated field needs to be updated. Similarly, if a Connector is updated, the EVSE’s last_updated and the Location’s last_updated fields need to be updated.

So this talks about _Locations_ being returned. And I'd seriously argue that a Location includes all EVSEs, even those that were not updated.
