### ISSUE TITLE
Different tariffs for different eMSPs

### ISSUE THREAD

**Issue by gvasmatkar** [ocpi/ocpi#433]
We have a scenario where in we might want to present different tariffs for the same location to different eMSPs based on agreement between the eMSP.

So for example, for a same location id, we might want to present a separate/different tariff id to the eMSP.

I would like to understand if such a scenario is a valid usecase or not. 

Thanks a lot!

**Comment by ahzf** [comment]
It is all there... it is just very hard to see ;)

When you have an in-memory representation of Locations, EVSEs and Connectors just replace TariffId / TariffIds with a delegate taking the LocationId, EVSEUId, ConnectorId and EMPId of the partner you are talking to into account and return the correct tariff information from a simple lookup table.

When you use a SQL database just remove the TariffId/TariffIds from the connector and implement a SQL table for the lookups. The JOINs for creating the correct response might be ugly but chatGPT will do it for you.

Mixing static 1-to-many POI data with dynamic 1-to-many EVSE status data and 1-to-1 tariff information is just one of the many reasons why Hubjects OICP is the much better EV roaming protocol ;)


Best...
  Achim

**Comment by ahzf** [comment]
Huh? Are you sure? What is the benefit of managing the enourmous overhead of p2p connections, when you show exactly the same data to everyone?

**Comment by gvasmatkar** [comment]
Thanks for the insight @ahzf  and @reinierl .

I am thinking, along the same lines, because we have a business usecase for that as well - we also want to NOT publish all the locations to all the eMSPs. So a wrapper is needed on top of OCPI to support this.
I believe implementing it using a lookup strategy for pretty much all other such usecases is the only option we have for now with 2.2.1.
