### ISSUE TITLE
Command Response/Result Clarity 

### ISSUE THREAD

**Issue by statiqantriksh** [ocpi/ocpi#437]
Really hoping for a quick response. @reinierl @RobertDeLeeuw 

First and foremost can we please have an example in the examples folder for command response and result.

Second, clarity is in need between the below mentioned command response and result.
Please help me clarify which is the correct response and result.

**1. Response**

```
{
    "data": {
        "result": "ACCEPTED",
        "timeout": 0,
        "message": []
    },
    "status_code": 1000,
    "status_message": "Success",
    "timestamp": "2023-05-08T03:46:01"
}
```

**1. Result** 

```
{
    "data": {
        "result": "ACCEPTED",
        "message": []
    },
    "status_code": 1000,
    "status_message": "Success",
    "timestamp": "2023-05-08T03:46:01"
}
```

**2. Response**  without the 4.1.7 defined response format object

```
{
        "result": "ACCEPTED",
        "timeout": 0,
        "message": []
}
```
**2. Result **  without the 4.1.7 defined response format object

```
{
        "result": "ACCEPTED",
        "message": []
}
```

**Comment by reinierl** [comment]
The response (so the synchronous HTTP response) is wrapped in the usual response format as described in [1.1.7 Response Format](https://github.com/ocpi/ocpi/blob/release-2.2.1-bugfixes/transport_and_format.asciidoc#117-response-format) in OCPI 2.2.1. So your **1. Response** example is correct.

The asynchronous result is not carried in an HTTP response so it is _not_ wrapped in the response format. So for the result, your example **2. Result** is correct.
