### ISSUE TITLE
Proper response for an invalid Authorization header

### ISSUE THREAD

**Issue by julius-yang** [ocpi/ocpi#439]
What is the correct response to this request?

curl https://ocpi.example.com/emsp/versions -H "Authorization: Token this_is_not_the_right_token" -H "Content-Type: application/json"

OCPI 2.2.1 section 5 distinguishes between status codes for HTTP related (transport) and OCPI related (content) errors.  "The transport layer ends after a message is correctly parsed into a (semantically unvalidated) JSON structure."  Since the Authorization token is incorrect, we would never parse the JSON structure.  Thus that means the error is in the transport layer.

I believe the service should therefore return a 401 Unauthorized response.  Is that right?  Or should it return a 200 with an OCPI 2xxx status code?

**Comment by reinierl** [comment]
401 Unauthorized is correct.
