### ISSUE TITLE
CPOs Location and EVSE endpoint

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#44]
The [data object](https://github.com/simonschllng/ocpi/blob/object-based-structure/bo_locations_and_evses.md#data) of the endpoint is described as:

| Property  | Type        | Card. | Description                              |
|-----------|-------------|-------|------------------------------------------|
| locations | Location    | +     | List of all locations with valid EVSE's. |
| evses     | EVSE        | +     | List of all valid EVSE's.                |

Shouldn't the cardinality be `*`, in case that the operator has no EVSEs at the moment? (Example: New operator). This would also meet the definition of the provider endpoint where `*` is defined for both objects.

**Comment by simonphilips** [comment]
Indeed.

**Comment by simonschllng** [comment]
Fixed in f449b7215760f5351e9d9def66ef88811d45d120
