### ISSUE TITLE
CdrToken cardinality is difference in properties and example

### ISSUE THREAD

**Issue by ThaddeusJiang** [ocpi/ocpi#450]
country_code and party_id are `MUST` in properties definitions, but missed in examples.

![CleanShot 2023-08-15 at 15 16 25@2x](https://github.com/ocpi/ocpi/assets/17308201/5721b855-a9f3-4d29-9590-8e21b16d8001)

![CleanShot 2023-08-15 at 15 12 04@2x](https://github.com/ocpi/ocpi/assets/17308201/3815839e-c512-4f62-b88d-fec131d3f327)

**Comment by reinierl** [comment]
It is already fixed in the latest documentation update draft.

**Comment by slachiewicz** [comment]
Where can we find this updated document?

**Comment by ThaddeusJiang** [comment]
@reinierl Where can we find this updated document?
