### ISSUE TITLE
Clarification of the Session.total_cost field

### ISSUE THREAD

**Issue by nick-jones** [ocpi/ocpi#451]
In 2.1.1, for the Sessions module, the `Session.total_cost` field has the following description:

> The total cost of the session in the specified currency. This is the
price that the eMSP will have to pay to the CPO. A total_cost of
0.00 means free of charge. When omitted, i.e. no price information
is given in the Session object, it does not imply the session is/was
free of charge.

The wording here could be interpreted in at least a couple of different ways:

1. The field carries the already known full cost of the session. In other words, the CPO already knows the full and final amount the eMSP will have to pay. Where the cost of a session is based around energy and/or time costs, this would imply this value can only be supplied once the session is marked as `COMPLETED`.
2. The field carries the latest view of the cost of the session. When a session is ongoing, this would mean the `total_cost` value can be set to the latest calculated cost of the session, even though that value is _not_ understood to be the full and final cost. Where the cost of a session is based around energy and/or time costs, this would imply the value increases whilst the session progresses in an `ACTIVE` state. Each time the eMSP receives an update, the value may be different to what it previously received. Once a session is marked as `COMPLETED`, the `total_cost` is understood to be the full and final cost.

Unfortunately I'd say the wording in the description of this field does not make it clear how best to interpret the nature of the `total_cost` field. Anyone able to clarify?

**Comment by reinierl** [comment]
The examples show that also non-completed sessions can have a `total_cost` field, which means that interpretation (2) is the right one.

I agree that the naming and description are not as clear as they could be. They should be improved in OCPI 3.0.
