### ISSUE TITLE
A mistake in the OCPI 2.2.1 document.

### ISSUE THREAD

**Issue by Mohamed-Sedeek** [ocpi/ocpi#455]
You stated in the section (4.1.8.3. Broadcast Push) that "GET SHALL NOT be used in combination with Broadcast Push". And in the example given in section (4.1.8.6. Overview of required/optional routing headers for different scenarios) under (Party to Party Broadcast Push) you used a GET command. I'm referring to the image in the page numbered 31 of the document (Figure 17. Example sequence diagram of Broadcast Push from one Platform to another Platform via a Hub). You even stated that it's a PUSH command in the caption of the image. So please confirm to me if this is a mistake.

**Comment by reinierl** [comment]
This is a mistake indeed. Thanks for reporting it!

**Comment by reinierl** [comment]
It will be fixed in a 2.2.1-d2 documentation update release which will come out one of these days.

**Comment by Mohamed-Sedeek** [comment]
Also, the section (4.1.8.7. GET All via Hubs) should be under the previous section (4.1.8.6. Overview of required/optional routing headers for different scenarios). It is not a new header. This is just a formatting thing, not a huge issue.
