### ISSUE TITLE
Figure 31 from Chapter 13.1 not updated?

### ISSUE THREAD

**Issue by jyakler** [ocpi/ocpi#458]
As RobertDeLeeuw's picture from https://github.com/ocpi/ocpi/issues/200 
"OCPI command with whitelist= NEVER" does not look the same as in figure 31 at Chapter 13.1
from OCPI 2.2.1 Document.

![image](https://github.com/ocpi/ocpi/assets/49812691/76fc74e7-2763-4e71-9c14-db9d1f7320b4)

**Comment by reinierl** [comment]
I think this is because the specification text in 2.2.1 has been changed to say that a START_SESSION command also serves as an implicit real-time authorization. @RobertDeLeeuw remarks that later in that thread:

> During the Strasbourg meeting it was decided to not allow real-time authorization after StartSession, the token in StartSession is already authorized by the MSP._That also solves this issue.
