### ISSUE TITLE
ocpi 2.2.1 document issue: which one is accurate to activate another 'ChargingPeriod'.

### ISSUE THREAD

**Issue by Yirgacheffe** [ocpi/ocpi#462]
Hi, Hello,
I found 2 versions of description related the 'ChargingPeriod'.

Github online version: 
CDR module, Section 1.3.1, it says: "When another Price Component becomes active, the CPO SHALL add a new Charging Period...".

ocpi 2.2.1 pdf version:
CDR module, Section 10.3.1, it says: "When another Tariff Element becomes active, the CPO SHALL add a new Charging Period...".

Can anyone let me know which one is correct? So that I can reference that. Thanks in advance~

**Comment by reinierl** [comment]
"Price Component" is correct. Tariff Elements are just groupings of Price Components and don't become active or inactive as a unit.
