### ISSUE TITLE
Describing a price in OCPI: should the price field be the price per hour or the price per step_size interval?

### ISSUE THREAD

**Issue by toni-garcia-freelance** [ocpi/ocpi#463]
Hello,

To best describe the problem, I will take the example of a charging station which has a price of: 2 euros per hour.
In the documentation: https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_tariffs.md#simple-tariff-example-2-euro-per-hour

In this example, the format for describing the price is:
![image](https://github.com/ocpi/ocpi/assets/119334403/3f580e2e-b66a-411e-bc18-14107a2c6b7e)

step_size = 300, means 300 second, so 5 min
From what I understand, the price per hour is 2 euros. And we apply billing every 5 minutes.
2 euros per hour gives 0.166 euros every 5 minutes. 
If a customer plugs his car in for 6 minutes, he will therefore pay 2 x 5 minutes = 0.33 euros

With other colleagues we have a discussion for format interpretation
For them it is an error in the documentation and the price field should contain: 0.166 
With the idea that this is the price that we must charge every 5 minutes

Can someone please help us by providing an answer in this format? 
Thanks you in advance

**Comment by andacata** [comment]
You're right. This example is explained in the [PriceComponent class](https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_tariffs.md#42-pricecomponent-class).

**Comment by toni-garcia-freelance** [comment]
> You're right. This example is explained in the [PriceComponent class](https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_tariffs.md#42-pricecomponent-class).

Ok thanks @andacata 
So it's not a mistake in the documentation , and the field "price" it's always the price per hour, is that ?

**Comment by andacata** [comment]
[TariffDimensionType enum](https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_tariffs.md#44-tariffdimensiontype-enum) is explicit: `time charging: defined in hours`

**Comment by toni-garcia-freelance** [comment]
> [TariffDimensionType enum](https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_tariffs.md#44-tariffdimensiontype-enum) is explicit: `time charging: defined in hours`

Thanks you very much
