### ISSUE TITLE
Clarification of "contract_id" in the token object

### ISSUE THREAD

**Issue by asyi23** [ocpi/ocpi#480]
based on the explanation of 'contract_id' . it said "Uniquely identifies the EV Driver contract token within the eMSP’s platform (and suboperator platforms). Recommended to follow the specification for eMA ID from "eMI3 standard version V1.0 (http://emi3group.com/documents-links/) "Part 2: business objects." is the contract agreement created by CPO ? or both eMSP and CPO ?

**Comment by reinierl** [comment]
The contract ID is created by the eMSP. It is typically used quite liberally and many eMSPs don't maintain a one-to-one correspondence between contract IDs and contracts with Drivers.
