### ISSUE TITLE
Clarification for Credential Exchange in OCPI 2.2.1

### ISSUE THREAD

**Issue by wooooody** [ocpi/ocpi#483]
Hi all,

I have a quick question to confirm. Does the Credential Exchange happen on Platform level, or on specific entity (CPO, eMSP etc.) level? As attached picture illustrate, OCPI 2.2.1 recommend Case A (two credential tokens in total) or Case B (six credential tokens in total)? 

Really appreciate if I could get some clarification from you!

![ce](https://github.com/ocpi/ocpi/assets/25835/c24232b8-8bab-47cb-ab43-107b1c508681)

**Comment by reinierl** [comment]
The credential exchange happens between platforms. Your diagram "Case A" is the correct one.

In OCPI, parties are not authenticated between each other. That means that parties and platforms have to trust their partner platforms to speak the truth about their partner parties.

**Comment by wooooody** [comment]
@reinierl Nice to see you again :) I just see your replied e-mail also. I totally got what you mean and really appreciate your clarification.
