### ISSUE TITLE
Querying eMSP Endpoints for Entity Validation

### ISSUE THREAD

**Issue by pol-sotos** [ocpi/ocpi#485]
Hello,

I have a question rather than an issue. I see in almost all the modules that when the CPO is not sure about the state of existence of an entity in eMSP's system, the CPO can call GET on the eMSP's endpoint to validate the entity. For instance, in the Session module the protocol states: "When the CPO is uncertain about the state or existence of a Session object in the eMSP’s system, the CPO can call GET on the eMSP’s Sessions endpoint to validate the Session object in the eMSP’s system."

I'm curious about the rationale behind this. Is it intended to conserve bandwidth between the systems? If so, it seems counterintuitive because the eMSP would need to send back the entire entity for the CPO to validate its state, thus consuming the bandwidth that was intended to be saved. Wouldn't it be simpler for the CPO to just transmit the latest state of the entity?

Additionally, eMSPs could implement a pull model, allowing them to retrieve information from the CPO if they've lost data due to an outage.

Thank you.

**Comment by reinierl** [comment]
OCPI 3.0 moves to a push-only pub/sub model. I would agree that the OCPI 2.x APIs where both parties can query and transfer data all the time without ever being certain of anything is very wasteful of bandwidth.
