### ISSUE TITLE
Retrieving Payment Method Information in relation to a Session or CDR Object

### ISSUE THREAD

**Issue by bmadanihntb** [ocpi/ocpi#486]
Hi.

Once a session has been paid for, what object/properties store the payment method that was used (i.e. debit, cash, etc.)?

**Comment by Piepke82** [comment]
Isn't this the TokenType in the Tokens module?
for example RFID (chargepass) or AD_HOC_USER (credit/debit) or APP_USER (smartphone app)

**Comment by bmadanihntb** [comment]
@Piepke82 Thank you for your response. This is very helpful.
