### ISSUE TITLE
Spec V2.2.1 example error for hubclientinfo?

### ISSUE THREAD

**Issue by wooooody** [ocpi/ocpi#491]
Hi, the example of hubclientinfo Receiver Interface PUT method demonstrate:
![image](https://github.com/user-attachments/assets/7f058252-1cec-4833-8ba1-4f3aa9d8e757)
Seems that this example is not 100% correct?

From the URL, "www.server.com/ocpi/cpo/...", it says this request is send to a CPO platform, but what is the "ALL", CPO or eMSP? From the request body, the "role" indicates "ALL" is CPO? But that seems make no sense. HUB should report eMSP connection status to CPO, correct?

Would you please help to clarify that?

**Comment by reinierl** [comment]
"ALL" is a CPO. The example call shows how a hub informs a client that a new CPO is planned to be connected to the hub, and the party ID of the CPO is "ALL".

"ALL" is actually a party ID for a company that exists, namely [Allego](https://www.allego.eu/). It's not a special keyword based on the English word "all".

**Comment by wooooody** [comment]
Hi @reinierl, thanks for replying!

I can understand "ALL" is a company. But from the PUT URL: "https://www.server.com/ocpi/cpo/2.0/clientinfo/NL/ALL", if I understand correct, that means HUB is telling cpo system that ALL's (a CPO) ConnectionStatus. Shouldn't HUB tell emsp (instead of cpo) system ALL's ConnectionStauts? From the URL parameter spec:
![image](https://github.com/user-attachments/assets/db6643b3-0c4e-47e8-84a1-8a6121200959)
country_code and party_id should be EMPS instead of CPO, no? That's why I'm confused.

**Comment by reinierl** [comment]
I am a bit surprised by how the words "eMSP" and "CPO" are used in the description of those fields. It's the Hub Client Info module, so messages can be about a party in any role, either CPO or eMSP or even another role. And the system sending the PUT is going to be a Hub, not an eMSP. So I think there is an error in the texts in the "Description" column of that table.

As for the example URL, the parts before the `/NL/ALL` are not specified by the standard, so we can't say they are wrong. There are some strange things though that make the example harder to understand: the version number 2.0 while this is the specification for version 2.2.1 of OCPI, and the string "cpo" which implies that the receiver of the request is a CPO while the request is also sent on behalf of a CPO.

I'll put the issue of the description texts in the table on the agenda of the next OCPI Development Working Group call.

The example URL I'll leave as it is. It's not great but the OCPI 2.2.1 specification has been out for a while and I don't think we should be spending time on small things like this anymore.

**Comment by wooooody** [comment]
Hi reinierl, yes, the Description is not correct.I can full understand and agree what you said.

Then another question raised. The reason why I'm asking this example is that, I'm trying to figure out how to implement my hubclientinfo scenario: A CPO Platform serves multiple CPOs, A EMSP Platform serves multiple EMSPs. Do you remember the case I send to you in the email:
----
![image](https://github.com/user-attachments/assets/37fbbf62-1387-4b06-9afe-7b786ceb4bee)
----

"eMSP Platform" is one single platform to serve 2 eMSP clients. The same for "CPO Platform".
If my case, seems that OCPI 2.2.1 hubclientinfo cannot describe ClientInfo for CPO1, because CPO1 is CONNECTED to eMSP1, but is PLANNED to eMSP2.

**Comment by madman-81** [comment]
> Hi, the example of hubclientinfo Receiver Interface PUT method demonstrate: ![image](https://private-user-images.githubusercontent.com/25835/350730263-7f058252-1cec-4833-8ba1-4f3aa9d8e757.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTU1NTYsIm5iZiI6MTcyODkxNTI1NiwicGF0aCI6Ii8yNTgzNS8zNTA3MzAyNjMtN2YwNTgyNTItMWNlYy00ODMzLThiYTEtNGYzYWE5ZDhlNzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDE0MTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNTU5Mzg2NmYzYjk3NjY1ZTg5ODQ4MDQyOWIwZmNiOGVmODQ5ODg3MjA2MDhiYzY0M2I0MWY5YTcyYzI1ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7KJ7ESR1sPCHjJ4uXZSqZ0utqlt4ZesV2jAmQDrcfD8) Seems that this example is not 100% correct?
> 

I do think there are a few mistakes in this example. The first one is a small one, but the comma after "PLANNED" makes the json invalid. The second one is the missing "last_updated" attribute. According to the object description in 15.4.1 this attribute is mandatory. Or perhaps the cardinality in the object description is wrong. 

Can you elaborate on this @reinierl ?
