### ISSUE TITLE
ENERGY STEP_SIZE

### ISSUE THREAD

**Issue by Hchier** [ocpi/ocpi#494]
i have a tariff with elements like this
[{
	"priceComponents": [{
		"type": "ENERGY",
		"price": 2,
		"vat": 0,
		"stepSize": 10000
	}],
	"restrictions": {
		"maxCurrent": "20",
	}
},[{
	"priceComponents": [{
		"type": "ENERGY",
		"price": 5,
		"vat": 0,
		"stepSize": 10000
	}],
	"restrictions": {
		"minCurrent": "20",
	}
}],

for a charging session, 
9:00-10:00, driver uses a max of 10A of power, 3kwh are charged,
10:00-11:00, driver uses a max of 40A of power, 3kwh are charged,
11:00-12:00, driver uses a max of 10A of power, 3kwh are charged,
how to bill?
2 * 10 + 5 * 10 + 2 * 10  or  2 * 10 + 5 * 10

**Comment by remkop22** [comment]
Step size is always evaluated over the total volume and applied to the last period with that volume. 

- So the consumed energy is: `3 + 3 + 3 = 9 kWh`
- Then applying step size we round the last period from `3 kWh` to `4 kWh` to make a total of `10 kWh`.
- Then the pricing goes like `(3 kWh * 2.0) + (3 kWh * 5.0) + (4 kWh * 2.0) = 29.0`

[Check out your example in our tool here](https://tools.tandemdrive.com?cdr=%7B%22country_code%22%3A%22BE%22%2C%22party_id%22%3A%22BEC%22%2C%22id%22%3A%2212345%22%2C%22start_date_time%22%3A%222015-06-29T09%3A00%3A00Z%22%2C%22end_date_time%22%3A%222015-06-29T12%3A00%3A00Z%22%2C%22cdr_token%22%3A%7B%22uid%22%3A%22012345678%22%2C%22type%22%3A%22RFID%22%2C%22contract_id%22%3A%22DE8ACC12E46L89%22%7D%2C%22auth_method%22%3A%22WHITELIST%22%2C%22cdr_location%22%3A%7B%22id%22%3A%22LOC1%22%2C%22name%22%3A%22Gent%20Zuid%22%2C%22address%22%3A%22F.Rooseveltlaan%203A%22%2C%22city%22%3A%22Gent%22%2C%22postal_code%22%3A%229000%22%2C%22country%22%3A%22BEL%22%2C%22coordinates%22%3A%7B%22latitude%22%3A%223.729944%22%2C%22longitude%22%3A%2251.047599%22%7D%2C%22evse_uid%22%3A%223256%22%2C%22evse_id%22%3A%22BE%2ABEC%2AE041503003%22%2C%22connector_id%22%3A%221%22%2C%22connector_standard%22%3A%22IEC_62196_T2%22%2C%22connector_format%22%3A%22SOCKET%22%2C%22connector_power_type%22%3A%22AC_1_PHASE%22%7D%2C%22currency%22%3A%22EUR%22%2C%22tariffs%22%3A%5B%5D%2C%22charging_periods%22%3A%5B%7B%22start_date_time%22%3A%222015-06-29T09%3A00%3A00Z%22%2C%22dimensions%22%3A%5B%7B%22type%22%3A%22ENERGY%22%2C%22volume%22%3A3.0%7D%2C%7B%22type%22%3A%22MAX_CURRENT%22%2C%22volume%22%3A%2210%22%7D%5D%7D%2C%7B%22start_date_time%22%3A%222015-06-29T10%3A00%3A00Z%22%2C%22dimensions%22%3A%5B%7B%22type%22%3A%22ENERGY%22%2C%22volume%22%3A3.0%7D%2C%7B%22type%22%3A%22MAX_CURRENT%22%2C%22volume%22%3A%2240%22%7D%5D%7D%2C%7B%22start_date_time%22%3A%222015-06-29T11%3A00%3A00Z%22%2C%22dimensions%22%3A%5B%7B%22type%22%3A%22ENERGY%22%2C%22volume%22%3A3.0%7D%2C%7B%22type%22%3A%22MAX_CURRENT%22%2C%22volume%22%3A%2210%22%7D%5D%7D%5D%2C%22total_cost%22%3A%7B%22excl_vat%22%3A4.00%2C%22incl_vat%22%3A4.40%7D%2C%22total_energy%22%3A15.342%2C%22total_time%22%3A1.973%2C%22total_time_cost%22%3A%7B%22excl_vat%22%3A4.00%2C%22incl_vat%22%3A4.40%7D%2C%22last_updated%22%3A%222015-06-29T22%3A01%3A13Z%22%7D&tariff=%7B%22country_code%22%3A%22NL%22%2C%22party_id%22%3A%22TDR%22%2C%22id%22%3A%22TDR1%22%2C%22currency%22%3A%22EUR%22%2C%22elements%22%3A%5B%7B%22price_components%22%3A%5B%7B%22type%22%3A%22ENERGY%22%2C%22price%22%3A2%2C%22vat%22%3A0%2C%22step_size%22%3A10000%7D%5D%2C%22restrictions%22%3A%7B%22max_current%22%3A%2220%22%7D%7D%2C%7B%22price_components%22%3A%5B%7B%22type%22%3A%22ENERGY%22%2C%22price%22%3A5%2C%22vat%22%3A0%2C%22step_size%22%3A10000%7D%5D%2C%22restrictions%22%3A%7B%22min_current%22%3A%2220%22%7D%7D%5D%2C%22end_date_time%22%3A%222019-06-30T23%3A59%3A59Z%22%2C%22last_updated%22%3A%222018-12-17T17%3A15%3A01Z%22%7D)

**Comment by ahzf** [comment]
And how would you calculate this, when one of the step sizes would be different?

**Comment by mbayings** [comment]
My suggestion is not to use stepsize at all - make it 1 or 0, but do not use for roundings via OCPI. In OCPI 3.0 we remove stepsize as it is very very confusing and only makes sense for rounding at the end of a transaction. If you want that, you can always do that in your own system before sharing the transaction/CDR. Using step size in OCPI makes it unnecessary complex.
