### ISSUE TITLE
Add ability to share the chargepoint's meter-values (exactly as & when sent to the grid operator)

### ISSUE THREAD

**Issue by rutgerplantenga** [ocpi/ocpi#5]
For Smart Charging purposes, in a model where the Provider purchases the electricity directly based on the Power Spot Exchange, it would be necessary for provider to know the chargepoint's meter values.

Request: Ability to request the Operator/ charge point to share the metervalues (exactly as & when sent to the grid operator) with the provider.

**Comment by RobertdeLeeuw-IHomer** [comment]
Is possible with OCPI 2.1: ChargingPeriods in Sessions
