### ISSUE TITLE
Define the request style globally

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#50]
In [bo_cdrs.md – 3.1.1 GET Method](https://github.com/ocpi/ocpi/blob/master/bo_cdrs.md#311-get-method) the request encoding is defined as:

> The request should be encoded as `application/x-www-form-urlencoded`.

Is there a special reason?

There should be a common definition for all methods.

**Comment by poohsen** [comment]
where is this line coming from originally?

**Comment by simonschllng** [comment]
In first appeared in commit 53fde827, added by you.

    $ git checkout 753e13d
    Vorherige Position von HEAD war f211b5e... Add a status code for when the server can not communicate with the client's API (likely because it's an invalid URL).
    HEAD ist jetzt bei 753e13d... Update session descriptions.
    $ grep -n x-www-form-urlencoded *.md
    sessions.md:136:The request should be encoded as `application/x-www-form-urlencoded`. The parameters are TBD.
    $ git blame -L 136,136 sessions.md
    53fde827 (Christoph Zwirello 2015-08-31 22:25:17 +0200 136) The request should be encoded as `application/x-www-form-urlencoded`. The parameters are TBD.

**Comment by poohsen** [comment]
hmm. I have no recollection of writing this, or any reason that might have made me do it.

**Comment by simonschllng** [comment]
@RobertdeLeeuw-IHomer: Could you please check if this is still in the specs. Could the get removed and this issue closed.

**Comment by RobertdeLeeuw-IHomer** [comment]
No longer in the spec
