### ISSUE TITLE
question about Message Routing

### ISSUE THREAD

**Issue by kanglishan** [ocpi/ocpi#501]
In OCPI 2.2.1-d2, Hub provides four routing way, namely Party to Party via Hub, Party to Party Broadcast Push, Party to Party Open Routing Request, GET All via Hubs.

but when one cpo party send request to hub, how can hub distinguish which routing way the cpo want to use? I think there should 

be a header describing the routing way used by the sender, similar to OCPI-to-party-id, OCPI-to-country-code, OCPI-from-party-id,  OCPI-from-countrycode.

Another question, the way of Party to Party Open Routing Request, how to decide routing which msp should be forwarded on hub?  I can not find related data from Hub ClientInfo Object only including role ,party_id, country_code, status.

![20241015-120518](https://github.com/user-attachments/assets/aa8eec6d-8b45-4edc-a79f-a9e46857507c)

**Comment by reinierl** [comment]
OCPI doesn't mean to specify how a Hub does its routing. It only specifies how other OCPI platforms can exchange messages with a Hub.
