### ISSUE TITLE
emi3group.com link rot?

### ISSUE THREAD

**Issue by edwardaskew** [ocpi/ocpi#503]
At various points (for contract_id in Token and CDRToken and evse_id in EVSE and CDRLocation) the standard references "eMI3 standard version V1.0" and links to http://emi3group.com/documents-links/ which seems to no longer be active (and hasn't been since at least [May 21st 2024](https://web.archive.org/web/20240521022347/http://emi3group.com/documents-links)).

Should OCPI be using the Wikipedia approach of linking to an archive (e.g. [here](https://web.archive.org/web/20230603153631/https://emi3group.com/documents-links/)) instead of a direct link or should it be hosting its own version of linked standards?

**Comment by reinierl** [comment]
Hosting our own versions seems a bit over the top for more reliable standards organizations like ISO or IETF.

For EMI3 the archive.org approach is the best one I think.

We'll be making a OCPI 2.3.0 release expanding somewhat upon OCPI 2.2.1 soon. I'll fix this there and in the OCPI 2.2.1 bugfixes branch. Thanks for reporting this!
