### ISSUE TITLE
OCPI 2.1.1: Handling null tariff_id and expected eMSP behavior

### ISSUE THREAD

**Issue by molacoste** [ocpi/ocpi#504]
In OCPI 2.1.1, the `tariff_id` field in the `Location/EVSE/Connector` object is optional and may be null or omitted. The documentation notes that for a 'Free of Charge' tariff, this field should be populated with a `tariff_id` pointing to a defined 'Free of Charge' tariff.

1. I would like to understand the scenarios in which this field would not be required. It appears that a tariff should be specified regardless of whether the station is free or not.
2. What is the expected behavior if a CPO provides a location with a null `tariff_id`? Should the eMSP interpret this as indicating a free tariff, or should it look for tariffs defined on other EVSEs at the same location? Is there a general consensus on handling this case on the eMSP side?

**Comment by reinierl** [comment]
An absent or null tariff means just that: no tariff information. As the receiver of those Locations, you will either have to get tariff information for them from a different source than OCPI, or use the Locations data without knowing the tariffs.

The background to this is that OCPI 2.1.1 is quite old. Back in the day, CPOs and MSPs often did not transfer tariffs using automated systems. They would have a contractual agreement that every session with the MSP's token on the CPO's chargers would be € X per kWh or per hour, and this tariff would be hardcoded in their systems.
