### ISSUE TITLE
Question about Tariff Elements and Price Components

### ISSUE THREAD

**Issue by ptkio** [ocpi/ocpi#506]
Hi, I am a new user of the protocol, and I have a question about a section of the documentation related to tariffs. 

https://github.com/ocpi/ocpi/blob/master/mod_tariffs.asciidoc
*This system of Tariffs, Tariff Elements and Price Components can be used to create complex Tariff structures.*
***When the list of Tariff Elements contains more than one Element that has a Price Component for a certain dimension**, then the first Tariff Element with a Price Component for that dimension in the list with matching Tariff Restrictions will be used. Only one Price Component per dimension can be active at any point in time, but multiple Price Components for different dimensions can be active at once. ****That is you can have an ENERGY component and a TIME component active at the same time, **but only those ones that are in the first Tariff Element that has a Price Component for that dimension and that has restrictions that match at that time.***

**Let’s imagine the following use case:**

- A tariff with a time-based price between 8:00 and 20:00
- A tariff with an energy-based price between 7:00 and 21:00
- A default tariff with a price based on energy

**In this case, we would create 3 Tariff Elements :**

```json
"elements": [
    {
      "price_components": [
        {
          "type": "TIME",
          "price": 1,
          "vat": 20,
          "step_size": 300
        },
        {
          "type": "PARKING_TIME",
          "price": 2,
          "vat": 20,
          "step_size": 300
        }
      ],
      "restrictions": {
        "start_time": "08:00",
        "end_time": "20:00"
      }
    },
    {
      "price_components": [
        {
          "type": "ENERGY",
          "price": 0.25,
          "vat": 10,
          "step_size": 1
        }
      ],
      "restrictions": {
        "start_time": "06:00",
        "end_time": "23:00"
      }
    },
    {
      "price_components": [
        {
          "type": "ENERGY",
          "price": 0.05,
          "vat": 10,
          "step_size": 1
        }
      ]
    }
  ]
```

**Imagines this chargings periods :**

```json
  "charging_periods": [{
    "start_date_time": "2024-11-08T09:30:02Z",
    "dimensions": [{
      "type": "ENERGY",
      "volume": 25
    },{
      "type": "TIME",
      "volume": 1
    }]
  },{
    "start_date_time": "2024-11-08T10:30:02Z",
    "dimensions": [{
      "type": "ENERGY",
      "volume": 25
    },{
      "type": "TIME",
      "volume": 1
    }]
  }],
```

**For each charging period, should it be Solution A or Solution B?**

- **Solution A**: The Time price component of the first Tariff Element will apply, and the Energy price component of the second Tariff Element will apply. (For each price component, it’s the first Tariff Element with a valid restriction.)
- **Solution B**: Only the price components in the first valid Tariff Element will apply, in this case, the Time and Parking time components only. (All price components come from the first valid Tariff Element.)

I believe it’s Solution A, and when I test the TandemDrive tool, it behaves as Solution A. I just want to be sure we’re interpreting the documentation correctly.

**Comment by reinierl** [comment]
Yes, it's Solution A indeed!

**Comment by ptkio** [comment]
thanks for you reply :)
