### ISSUE TITLE
a CPO pushes a Location to a EMSP through hub

### ISSUE THREAD

**Issue by hihanima** [ocpi/ocpi#507]
when a CPO C1 pushes a Location to a EMSP E1 through hub,
As a hub, what are the best practices for handling data related to Location updates from CPOs  to EMSPs ? There are three main approaches:
1 、The hub stores this data and broadcasts it to all EMSPs. If later the CPO C1 pushes this Location to another EMSP E2, the hub updates this data and rebroadcasts it to all EMSPs.
2、The hub does not store this data but forwards the request to the EMSP E1.Alternatively, the hub can store data, but this piece of data should be distinguished from the data sent to:hub, meaning that this data cannot be obtained through GET All via Hub.
3、The hub should only accept requests where the request header contains "to: hub"，so The hub refuses this request because the request header is "to: E1" 
Which approach is considered best practice?

**Comment by reinierl** [comment]
(2) is what I would expect and what the specification is designed for.

If you have your own compelling reasons to do it differently, you can of course.

**Comment by hihanima** [comment]
thank you
