### ISSUE TITLE
a CPO pushes a Location to the HUB

### ISSUE THREAD

**Issue by hihanima** [ocpi/ocpi#508]
when a CPO pushes a Location to the HUB, we think that the HUB should store this data and then broadcast it to all EMSPS.
Regarding why the HUB should store data, we refer to OCPI 2.2.1-d2 Figure 14: 
![20241111-144202](https://github.com/user-attachments/assets/18d1a117-954c-4673-9ea0-6c0d6b7cdd46)
This allows us to support GET All via the Hub.
could  you tell us if we understand it correctly.

**Comment by reinierl** [comment]
Yes, you understand it correctly!

**Comment by hihanima** [comment]
thank you very much
