### ISSUE TITLE
Add remote start capability and capability structure

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#51]
The [capability enum](https://github.com/ocpi/ocpi/blob/master/bo_locations_and_evses.md#capability-enum) has two values: `RESERVABLE` and `CHARGING_PROFILE_CAPABLE`. As the capability to remotely start a charging process is very similar, it should be added here.

Each of these capabilities require to trigger them in the operator backoffice. Therefore a endpoint and a method is required. Thus, the capabilities could be combined with the endpoint information:

#### Capabilities
| Property  | Type        | Card. | Description                    |
|-----------|-------------|-------|--------------------------------|
| type     | CapabilityType  | 1     | The kind of capability.                               |
| endpoint | Endpoint | ?      | The endpoint to make use of this capability                               |

##### Example:

```javascript
{
    //...
    
    "capabilities": [
      {
        "type": "RESERVABLE", 
        "endpoint": 
            {
                "identifier": "reservations",
                "url": "https://example.com/ocpi/cpo/2.0/reservations/nlelae12345"
            }
      },
      {
        "type": "REMOTECONTROLABLE", 
        "endpoint": 
            {
                "identifier": "remotecontrol",
                "url": "https://example.com/ocpi/cpo/2.0/remotecontrol/nlelae12345"
            }
      }
    ],
    
    //...
}
```

**Comment by simonschllng** [comment]
This can be relevant for #77

**Comment by simonphilips** [comment]
This is also relevant for issue #78.

**Comment by RobertdeLeeuw-IHomer** [comment]
Added with commit: https://github.com/ocpi/ocpi/commit/d03d75df7af560927bbc8ed78e50726478fdbf3c#diff-9067189fbb67841f9af58b18656c8a0a
