### ISSUE TITLE
a CPO pushes a Location to two EMSP through hub

### ISSUE THREAD

**Issue by hihanima** [ocpi/ocpi#511]
A CPO C1 pushes one of its locations (id=1) to EMSP E1 (TO:E1) and EMSP E2 (TO:E2) via a hub. Is it possible that some fields of this location pushed to E1 and E2 may differ? For example, the name might be different or the tariff_ids in the connectors within the location might vary. From the perspective of the OCPI protocol, I believe this is possible, but would such scenarios occur in reality? Are there any best practices in real-world applications for reference? Thank you.

**Comment by reinierl** [comment]
It is indeed possible in OCPI.

To what extent this is actually done in practice, you'd have to check with companies running hubs with OCPI, like Gireve, Hubject, Chargehub, Enapi, OCN, ... I can't really speak for all of those.

**Comment by hihanima** [comment]
thank you very much
