### ISSUE TITLE
[2.1.1] Example Shows max_power/min_power in Amps Instead of Kilowatts

### ISSUE THREAD

**Issue by Hamza-nabil** [ocpi/ocpi#516]
The description of the example in the [Complex Tariff example](https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_tariffs.md#complex-tariff-example)  implies that max_power is  32A :

> 2.50 euro start tariff 1.00 euro per hour charging tariff for less than 32A (paid per 15 minutes) 2.00 euro per hour charging tariff for more than 32A on weekdays (paid per 10 minutes) 1.25 euro per hour charging tariff for more than 32A during the weekend (paid per 10 minutes) Parking costs:

```
{
  "price_components": [{
	  "type": "TIME",
	  "price": 1.00,
	  "step_size": 900
  }],
  "restrictions": {
	  "max_power": 32.00
  }
}
```

The [specification](https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_tariffs.md#45-tariffrestrictions-class) however says that `max_power` is in kW:

> max_power | number | ? | Maximum power in kW, for example 20, valid up to this charging speed

I believe it makes more sense to represent max_power in Amps, as this aligns with the information provided in the [CdrDimensionType](https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_cdrs.md#43-cdrdimensiontype-enum).

How should we handle cases where such restrictions are in place?

**Comment by reinierl** [comment]
We already have a "max_current" to give a maximum in Amps. I would regard the example that you quote as mistakenly saying "max_power" instead of "max_current". I will change it to say "max_current" unless you have a better idea.

**Comment by Hamza-nabil** [comment]
While it might seem a good idea to use `max_current` in this context, OCPI 2.1.1 doesn't explicitly define `max_current` as a restriction for Tariffs,  [TariffRestrictions](https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_tariffs.md#45-tariffrestrictions-class) ,  But we have this information in the CDR (`MAX_CURRENT`, `MIN_CURRENT`) [CdrDimensionType](https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_cdrs.md#43-cdrdimensiontype-enum).

I think it would make more sense to add the `max_current` and `min_current` restrictions (not sure if that possible)

**Comment by Hamza-nabil** [comment]
For `max_power` and `min_power`, we don't have the information on the CDR ([CdrDimensionType](https://github.com/ocpi/ocpi/blob/release-2.1.1-bugfixes/mod_cdrs.md#43-cdrdimensiontype-enum) for 2.1.1 not have `MAX_POWER`, `MIN_POWER`).  I think we need to add it.

**Comment by reinierl** [comment]
I see only now that this is about OCPI 2.1.1 in which the max_current wasn't there yet. We're not adding new functionalities to OCPI 2.1.1 so there's not much we can do about that anymore.

**Comment by Hamza-nabil** [comment]
I understand that , but that mean the example is wrong .  we can't correct the example?
