### ISSUE TITLE
OCPI Workshop #15

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#52]
My notes on the tariff structure from the meeting, to be extended:

## Generic Tariff Type

This is the common structure for the tariffs.

```
{
  "tariff_id": "",
  "tariff_type:" ""
}
```

## Type __1__ *Basic Tariff*

Simplest version, flat fees.

```
{
  "tariff_id": "",
  "tariff_type:" "basic",
  "currency": "EUR",
  "start": 0.00,
  "time": 0.00,
  "kwh": 0.00
}
```

## Type __2__ *URL Tariff*

Last fall-back scenario for complex custom tariffs.

```
{
  "tariff_id": ""
  "tariff_type:" "url"
  "url": "https://operator.tld/tariff-table"
}
```

## Type __3__ *Text Tariff*

Second fall-back scenario for complex custom tariffs.

```
{
  "tariff_id": "",
  "tariff_type:" "text",
  "display_text": [
    {
      "language": "nl",
      "text": "Standaard Tarief"
    },
    {
      "language": "en",
      "text": "Standard Tariff"
    }
  ]
}
```

## Type __4__ *Flex Time Tariff*

Structure for tariffs with different rates per date or daytime. 

```
{
  "tariff_id": "",
  "tariff_type:" "flex_time",
  "currency": "EUR",
  "elements": [
    {
      "start_fee": 0.00,
      "time_fee": 0.00,
      "energy_fee": 0.00,
      "valid_times": { //HoursType// }
    },
    {
      "start_fee": 0.00,
      "time_fee": 0.00,
      "energy_fee": 0.00,
      "valid_times": { //HoursType// }
    }
  ]
}

```

**Comment by simonphilips** [comment]
# Whiteboard notes

## Tariffs

I had to paint a bit over this one as some parts were not clear on the photo.

![img_20151016_124900](https://cloud.githubusercontent.com/assets/3263809/10641484/b9438f6e-7819-11e5-8afb-9ab9752f5bce.jpg)

![img_20151016_124908](https://cloud.githubusercontent.com/assets/3263809/10641505/cebbbce0-7819-11e5-9296-86249cab1054.jpg)

## Tokens

![img_20151016_133108](https://cloud.githubusercontent.com/assets/3263809/10641517/dd75311c-7819-11e5-8967-006850894d37.jpg)

**Comment by simonschllng** [comment]
After what @simonphilips  explained in the update call, the Flex Time Tariff schould be changed to:


## Type __4__ *Flex Time Tariff*

Structure for tariffs with different rates per date or daytime. 

```
{
  "tariff_id": "",
  "tariff_type:" "flex_time",
  "currency": "EUR",
  "elements": [
    {
      "tariff": { //TariffType// },
      "valid_times": { //HoursType// }
    },
    {
      "tariff": { //TariffType// },
      "valid_times": { //HoursType// }
    }
  ]
}

```

**Comment by RobertdeLeeuw-IHomer** [comment]
after a call with @simonphilips  and @simonschllng we came up with a new structure for Tariff. Would could not get the current flex_time referenced/inserted into CDR.
We propose the following:

tariff:
```
{
  "id": "1",
  "currency": "EUR",         // ISO 4217 Code
  "elements": [
    {
      "dimensions": [
        {
          "dimension_type": "time",
          "price": 4.00,     // per hour
          "division": 300    // optional in seconds (charge in 5 minute blocks)
        }, 
        {
          "type": "energy",
          "price": 0.20      // per kwh
        }              
      ],
      "restrictions": {
        "current": "",              // optional
        "start_time": "8:00",       // optional, valid between 8:00 and 17:00
        "end_time": "17:00",        // optional
        "start_date": "24-12-2015", // optional, valid between 24-12-2015 and 31-12-2015
        "end_date": "31-12-2015",   // optional
        "min_kwh": "0",             // optional, valid for the first 24 kWh charged
        "max_kwh": "24",            // optional
        "min_power": "0kw",         // optional, valid for power between 0 and 20 kW, only slow charging
        "max_power": "20kw",        // optional
        "min_duration": 0,          // optional in seconds??, valid for the first hour
        "max_duration": 3600,       // optional
        "day_of_week": [            // optional, valid on Saterday and Sunday
            "SATURDAY", 
            "SUNDAY"
        ]
      }
    },
    {
      "dimensions": [
        {
          "dimension_type": "time",
          "price": 5.00           // per hour
        } 
      ],
      "restrictions": {
        "start_time": "18:00",
        "end_time": "24:00"
      }
    },
    {
      "dimensions": [
        {
          "dimension_type": "energy",
          "price": 5.00           // per kwh
        }
      ],
      "restrictions": 
      {
        "start_time": "18:00",
        "end_time": "24:00"
     }
   }
 ]
} 
```

dimension_type: 
```
[
  time,         // defined in hours, default division is 1 second
  parking_time, // defined in hours, default division is 1 second
  energy,       // defined in kWh,   default division is 1 Wh
  flat          // no unit
]
```
In connector we add 2 fields to replace the text/url based tariffs. give an alternative, replacing current PricingScheme

connector:
```
{
  ...
  ...
  "tariff_id": "1",   // optional
  "tariff_alt_text",  // alternative tariff info text
  "tariff_alt_url",   // alternative url to tariff info.
  ...
}
```

CDR will have a list of all the valid tariff information

CDR:
```
{
  "id": "",
  "start_date_time": "",  
  "end_date_time": "",  
  "kwh": "",
  "authorizing_id": "",
  "location": Location Object,
  "evse_id": "",
  "connector_id": "", 
  "meter_id": "",
  "currency": "EUR", // ISO 4217 Code
  "tariffs": [
    // list of relevant tariff objects
  ],
  "charging_periods": [
    // list of charging_periods
  ]
  "total_cost": "13,56",
  "status": "" // unclear what this should be, an Enum? Finished, Ongoing?
}
```

charging_period: 
```
{
  "start_date_time": "",
  "duration": "",
  "kwh": "",
  "min_power": "0kw",     // optional?
  "max_power": "20kw",    // optional?
}
```

We don't have reference to tariffs any more. Based on the periods you should be able to figure out what the correct matchting tariff(s) should be. (yes it might be multiple tariffs for 1 period)

**Comment by simonschllng** [comment]
Some further thoughts and feedback:

##### tariff > elements > restrictions > current

This is redundant with power. However, some might take the power into account and some the current. Imo both should be available as min/max-fields.

Compare: #24

#### min/max entries 

To make it more consistent all min/max fields should be inclusive. Thus the example should read to make this more obvious:

        "start_time": "8:00",
        "end_time": "16:59",


#### connector

Shouldn't tariff_alt_text and tariff_alt_url also be optional? It has be be clear weather no tariff means _free of charge_ or _tariff unknown_. Maybe there should be an optional boolean reflecting this.

#### CDR

In consistency with the dimensions in the tariffs, we should also build the CDR on the same concept. This means remove _kwh_ from the root and add a list of metered dimensions:

      "dimensions": [
        {
          "dimension_type": "time",
          "volume": 2.00           // hours
        },
        {
          "dimension_type": "energy",
          "volume": 5.00           // kwh
        }
      ],

The same concept could then be applied to the periods. This would replace the following and solve the open questions here:

    "kwh": "",
    "min_power": "0kw",     // optional?
    "max_power": "20kw",    // optional?

**Comment by simonphilips** [comment]
> To make it more consistent all min/max fields should be inclusive.

I disagree, a half open interval of [min, max[ is strongly recommended. With closed intervals (that is both minimum and maximum are inclusive) you can no longer describe a chain of intervals when dealing with a continuous domain because you cannot fill the gaps between both intervals.

Examples: 
* one element with current = [0, 15.99] and another element with current = [16, 31.999]. What do you do with a current of 15.999?
* one element with time = [10:00, 15:59] and another element with current = [16:00, 19:59]. What do you do with 15:59:30?

This problem is solved by using half-open intervals: [0, 16[, [16, 32[

**Comment by simonschllng** [comment]
Ok, agreed. But it has to be stated in the documentation either way. This was my point actually. Your explanation could be used right away.

**Comment by simonphilips** [comment]
Now I agree :)

**Comment by simonphilips** [comment]
I just noticed you added units here:

> "min_power": "0kw",     // optional?
> "max_power": "20kw",    // optional?

I'd say plain numbers are a lot easier to parse:

> "min_power": 0,     // kwh   // optional?
> "max_power": 20,  // kwh   // optional?

**Comment by poohsen** [comment]
+1 to that
