### ISSUE TITLE
Tariff-option to be added: Minimum fee

### ISSUE THREAD

**Issue by rutgerplantenga** [ocpi/ocpi#54]
I have seen at least two CPO's who are supporting a 'minimum fee' per session. This means that they're applying a time-based or kWh-based fee with a certain minimum fee per session. It's a fairly straightforward pricing method (quite common in other markets) so I would propose to support this as a basic tariff-type.

**Comment by RobertdeLeeuw-IHomer** [comment]
Is allready in the current version of OCPI: Tariff Object contains a PriceComponent, this contains a type, which is an enum named: DimensionType. DimensionType allready has the following options: 

| Value        | Description                                          |
| ------------ | ---------------------------------------------------- |
| energy       | defined in kWh, default division is 1 Wh             |
| flat         | flat fee, no unit                                    |
| max_current  | defined in A (Ampere), Maximum current               |
| min_current  | defined in A (Ampere), Minimum current               |
| parking_time | defined in hours, default division is 1 second       |
| time         | defined in hours, default division is 1 second       |

**Comment by simonschllng** [comment]
I believe this does not meet Rutger's requirements. This is about the tariffs and a so far not covered feature. It could be added to [Tariffs BO/PriceComponent](https://github.com/ocpi/ocpi/blob/master/bo_tariffs.md#52-pricecomponent-class):

### 5.2 PriceComponent *class*

| Property        | Type          | Card. | Description                                      |
|-----------------|---------------|-------|--------------------------------------------------|
| type            | DimensionType | 1     | Type of tariff dimension, see: [Types](types.md) |
| price           | decimal       | 1     | price per unit for this tariff dimension         |
| step_size       | int           | 1     | ~Minimum amount to be billed.~ This unit will be billed in this step_size blocks. For example: if type is time and  step_size is 300, then time will be billed in blocks of 5 minutes, so if 6 minutes is used, 10 minutes (2 blocks of step_size) will be billed. |
| first_step       | int           | 1     | Minimum amount to be billed. The first step for this unit to be billed. If `step_size` is 60 and `first_step` is 300, then every amount less than 300 will be billed as 300, after that, it will be billed in steps of 60. |

##### Examples:

| step_size | first_step | actually used amount | billed amount |
|--------------|--------------|-------------|---------------|
| 60 | 300 | 50 | 300 |
| 60 | 300 | 200 | 300 |
| 60 | 300 | 301 | 360 |

**Comment by simonschllng** [comment]
@rutgerplantenga: Does the sentence *»they're applying a time-based or kWh-based fee with a certain minimum fee per session«* mean, that the minimum fee is a "over-all" minimum, saying that it can be "consumed" by either energy usage _or_ time usage? Then we would've to implement this in an additional way to what I have stated above.

**Comment by rutgerplantenga** [comment]
@simonschllng In the existing examples there is no combination of time-based AND kWh-based but yes, I would say that it should be treated as an 'overall minimum' or 'session minimum'.

**Comment by achalaggarwal-cpi** [comment]
Standard says pick the first matching tariff based on restrictions but in the complex examples the very first pricing element has no restriction. 
When will the other tariff elements get pick up??? It is like having default as the first choice in switch case construct.

**Comment by KevBelisle** [comment]
@achalaggarwal-cpi I think my previous understanding was incorrect...

And I think this sentence in the Tariffs module pointed me in the right direction:

> ...when none the TariffElements before this **matches the current charging period**

A `ChargingPeriod` is defined in the CDR module:

> List of charging periods that make up this charging session. A session consists of 1 or more periods, where each period has a different relevant Tariff.

> A charging period consists of a start timestamp and a list of possible values that influence this period, for example: Amount of energy charged this period, maximum current during this period etc.

.

It really isn't clear to me how all this fits together. I have so many questions I can't seem to find the answer to...

If we consider the Complex Tariff example:

- If someone charges for 2 min (TIME), then is parked for 2 min (PARKING TIME)... **Will the driver be charged for a full step of each (900s of TIME and 300s of PARKING TIME), for a total of 20min on a 4min session?**

- What if the car is charging at just about 32A, sometimes going over and sometimes under... If the car spends 1min over 32A, then 1min under, then another min over, **will the driver be billed for: 600s over + 900s under + 600s over, aka a total of 35min accumulated in 3min ?**

- **When I'm looking for a TariffElement that _matches the current charging period_, am I supposed to consider both the TariffRestrictions AND the PriceComponents?**
  * If we don't, then we would always match the first TariffElement ($2.50 flat).
  * Even if we pretend that first TariffElement ($2.50 flat) is always at the bottom of the list... We would always match either the 2nd ($1/h, max power 32A) or the 3rd/4th (min power 32A, $2/h or $1.25/h depending on day of week), and the other TariffElements would never be considered.


Does anyone really understand how all this works? Is there more information somewhere other than this repository?

.

Also, I found another problem with the example:

The description states talks of _"less than 32A"_ and _"more than 32A"_ but there is no TariffRestriction for current, so they used `max_power` and `min_power` which are kW, not amps... To reflect the "32A" they mention in the description, the restrictions should be set to "7.68kW" (supposing 240V: 32A * 240V = 7.68kW).

**Comment by RobertdeLeeuw-IHomer** [comment]
Minimum Price (and Maximum) are added

**Comment by mbayings** [comment]
Instead of having a minimum Price, I suggest to use a minimum kWh delivery. A price doesn't mean anything as it does not give info how much you get for it. It would be much more logic, just like with fuel that you set a minimum usage/delivery of volume. I think the way of using minimum prices would be the wrong way.
