### ISSUE TITLE
How to connect to a different version number?

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#56]
**A little bit of background**:
When the handshake process is initiated, the party that initiates it needs to have access to the **versions url** (that is provided offline together with the token). And then roughly it would: 
  1. Get the different versions available for the client 
  2. Choose the highest version number they have in common
  3. Get the endpoints available for this version number
  4. Send the credentials and store the received ones. 

Note that the received credentials don't contain the versions url as a field.

**Issue**:
If this party 1 month later has a higher version available, it wants to know if the other party it is connected to also does. But we don't have a way to know if the versions url we got 1 month ago is the same one or has changed, meaning that we can not automate the refreshment of versions we are connecting to.

I propose we add the **versions_url** to the **Credentials object**, so I can restart the process if I need to without the need of getting these details offline, making therefore possible making use of the versions endpoint as it was another one (since allows it access with the same token than the rest).

A different matter would be how to handle this request from a party that we are already connected to. But regarding the field, I consider that the sooner we add it to the **Credentials object**, the better, otherwise we break backwards compatibility.

**Comment by simonschllng** [comment]
I understood the versions endpoint as a static starting point which should never change. Of course changes could always happen. Also the credentials endpoint could change or all endpoints switch to a new domain.
A solution could be to append a field to each request and response in the protocol (in the [transport and format](https://github.com/ocpi/ocpi/blob/master/transport_and_format.md) section) which reflects the version endpoint URL and a time stamp of it's latest change. Then we can update everything completely dynamically.

The documentation should state if a all-time static endpoint is necessary and contain an example process for updating endpoints.

**Comment by cristinarc** [comment]
I will invalidate this issue cause the versions endpoint url is already there, I didn't notice for some reason. Sorry for the confusion!
