### ISSUE TITLE
ConnectorType enum specification: Replace '-' with '_'

### ISSUE THREAD

**Issue by ahzf** [ocpi/ocpi#58]
Hi all,

the ConnectorType enum (5.5) at https://github.com/ocpi/ocpi/blob/master/mod_locations_and_evses.md#55-connectortype-enum used '-' in the enum specification. As this leads to problems within programming languages, it would be better to replace it with '_', like done at most other defined enums in the current OCPI documentation.

Best from Jena, Germany
  Achim

**Comment by poohsen** [comment]
that's a fair point. There's no need to stick to the dashes for the enum values here. Since this originally came from OCHP, I'd like to ask for @simonschllng 's opinion on this

**Comment by simonschllng** [comment]
I don't mind. As long as the enum list is the same, it is straight forward to map it to the OCHP version.

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed, OCPI uses enums with Capitals and _
