### ISSUE TITLE
Additional EVSE status "OFFLINE"?

### ISSUE THREAD

**Issue by ahzf** [ocpi/ocpi#59]
Hi all,

some EVSE operators/CPOs use the EVSE status "OFFLINE" whenever no communication is currently possible with an EVSE, e.g. caused by low quality mobile communications. In most cases those EVSEs also use special local authentications methods whenever an EVSE has no communications to the operator backend. In my eyes neither "UNKNOWN - No status information available", nor "OUTOFORDER - The EVSE is currently out of order, nor "INOPERATIVE - The EVSE is not yet active or it is no longer available (deleted)." are good mappings for "OFFLINE". Therefore what are your opinions about defining an additional "OFFLINE" status?

Best from Jena, Germany
  Achim

**Comment by poohsen** [comment]
the status UNKNOWN is meant to cover the scenario you describe: since no communication is possible with the EVSE, we cannot know its status.
