### ISSUE TITLE
Physical number on EVSE object

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#61]
Currently the *physical_number* on the [EVSE](https://github.com/ocpi/ocpi/blob/master/mod_locations_and_evses.md#42-evse-object) is defined as follows:

Property | Type | Card. | Description
------------|--------|---------|----------------
... | ... | ... | ...
physical_number | string(4) | ? | A number on the EVSE for visual identification.
... | ... | ... | ...

Some operators might print the full EVSE ID onto the charge point. Weather this is user friendly or not, it's their decision and should be supported. The comment could hint that short numbers are better.

**Comment by RobertdeLeeuw-IHomer** [comment]
do you have a proposal for the comment? "It is advised to use a number only. To support more elaborate numbering schemes , the type of this field in string"

**Comment by simonschllng** [comment]
Yes, something like that. A good numbering scheme could also be `[A, B, C, ...]`. Maybe add, that the purpose is to help the user to identify a charge point in _one location_. But some operators numerate all their chargepoints like `[1, ..., 100, ..., 1000, ...]` what imho would also be ok.

**Comment by RobertdeLeeuw-IHomer** [comment]
This is the numbering of EVSEs. EV-Drivers dont understand EVSEs, they understand connectors. They need to know which connector... 

My personal opinion, the EVSe is something that is technical and only for engineers

**Comment by simonschllng** [comment]
Yes, this is a opinion I can understand. However, you can not unlock one connector but only the full EVSE and we have the field `physical_number` on the EVSE-level. This means we are currently not able to numerate connectors for that use-case.

**Comment by mbayings** [comment]
I should stay as close as possibleI to how it is defined in OCPP 1.5 / 1.6. Isn't that possible?

**Comment by poohsen** [comment]
We should elaborate on the usage of the physical_number field in release 2.2 (which, I understand, will contain remote start/stop). 
There should be a hint  to make sure devs implementing the CPO and MSP roles agree on the semantics of the this field and on what to do if it's not filled. 
Probably an empty physical_number field should by default result in falling back to displaying the EVSE-ID field to accomodate CPOs that print the full EVSE-IDs on their chargepoints.

**Comment by cristinarc** [comment]
Did we take into consideration what is the current situation? meaning, what is the number they print currently? Unfortunately I don't know that. Do you @rutgerplantenga or @mbayings ?

In case it is the EVSE_ID I would say that this solution looks good for now (till we get to the commands module), in case there's different kind of numbers printed, then we need to find out which ones are those and make sure the String is able to cover these cases. Even if we advice to use smaller "numbers" (4 digits).

**Comment by simonphilips** [comment]
Shouldn't we split them up into visual_number and ordering_number or something?

**Comment by mbayings** [comment]
@cristinarc we did not take into account the number they print currently. You would say that both a visual and technical connector ID could be the solution. We can add the visual number in a next release.  But we must think about this very good. As the visual number is not unique. So you must still identify the station and be 100% sure that that is the station. I would say that the concept of printed visual numbers is a bit old-fashioned - we should introduce or support modern ways like NFC code or beacons or something like that. Finally you must go to the socket anyway to put the connector in it - you can easily touch with your phone the RFID/NFC tag or something like that. 
Having said that, we might still keep an 'open field' where operators can enter a visual number for the socket - to deliver also a solution for the 'old' stations.

**Comment by cristinarc** [comment]
@mbayings I agree it should allow more modern ways of selecting the evse to initiate, but it is also tricky since it can be that the same chargepoint has serveral evses. A QR code support would also be a good idea, since it is specific and at the same time modern and easy to use. I think we could go deeper and deeper in this matter in person, but I think the conclusion about this issue is that we all want a `physical_number` in there, the question is, what is the length of that String, (if that value is a string we should maybe call it `physical_reference`).

Can we close this issue? or do you think there is something we should discuss here @simonschllng ?
