### ISSUE TITLE
Unclear step in OCPI registration process - endpoint URL

### ISSUE THREAD

**Issue by markvandenbergh** [ocpi/ocpi#65]
In the registration process after the eMSP retrieved the versions and details of 2.0 the next step is that the eMSP posts to the credentials endpoint of 2.0.

In the example the URL is a relative URL, not an absolute one. Is the idea here that the CPO detects the IP address of the requester and construct a URL based on that? Or should the specification be altered so that the credentials posted contain an absolute URL.

**Comment by poohsen** [comment]
no, this is supposed to be an absolute URL to the eMSP API. It's been shortened to fit into the sequence diagram. 
The credentials are supposed to look like the example given in https://github.com/ocpi/ocpi/blob/master/credentials.md#example

**Comment by poohsen** [comment]
I hope the addition in commit 2b7afc6 will make it clear for others who stumble upon this.
