### ISSUE TITLE
Please refactor the /locations collection

### ISSUE THREAD

**Issue by ahzf** [ocpi/ocpi#67]
Dear all,

the current specification of the /locations data collection is rather uncommon and will lead to many headaches for implementators. Therefore I suggest the following _future_ refactorings:

- /locations will only include location objects
- GET /locations [ ?skip=2&take=200 ] will return an array of location objects, possible query parameters are skip and take to enable pagination

- /locations/{locationId} will enable access to an individual location object
- GET /locations/{locationId} will return a single location object
- PUT /locations/{locationId} will add or update the entire location object
- PATCH /locations/{locationId} will update parts of location object [optional]

There should be an agreement to use the operator id as a prefix for location ids in the same way as evse ids are defined. Currently multiple operators might use the same values for locations ids and no conflict management is defined.

- /evses will only include evse objects
- GET /evses [ ?skip=2&take=200 ] will return an array of evse objects, possible query parameters are skip and take to enable pagination

- /evses/{evseId} will enable access to an individual evse object
- GET /evses/{evseId} will return a single evse object
- PUT /evses/{evseId} will add or update the entire evse object
- PATCH /evses/{evseId} will update parts of evse object [optional]

Static evse data is slowly changing, but the status of evses can change multiple times within a couple of hours. Therefore it would be good to have specialized resources for this.

    GET /evsestatus [ ?skip=2&take=200 ]
    {
         "DE*GEF*12345678*1": "AVAILABLE",
         "DE*GEF*12345678*2": "CHARGING",
         ...
    }

    PUT /evsestatus
    {
        "DE*GEF*12345678*1": "CHARGING",
        "DE*GEF*12345678*2": "RESERVED",
        ...
    }

    PUT /evsestatus/DE*GEF*12345678*1
    {
        "newstatus": "CHARGING"
    }

In a next step it would perhaps also be nice to support a list of future status changes (maintenance windows etc.pp) or adding the total number of object in a collection as meta data into the HTTP response header (e.g. X-TotalCount: 4096).

**Comment by RobertdeLeeuw-IHomer** [comment]
Thanks for you input. 
There is a proposal for changes in all modules. GET/PUT/PATCH will be aligned between modules. GET en the CPO side will get Pagination. Facebook style Offset-based

Also the Locations module will be changed, EVSE will become part of Location. With some changes to the Objects. I hope to make all the changes before Christmas.
