### ISSUE TITLE
use JSON object instead of array to define total_usage (16.)

### ISSUE THREAD

**Issue by poohsen** [ocpi/ocpi#70]
In 'total_usage', elements are defined as array items, which allows for repetition of same type elements. There is no comment on reasoning behind this and how anybody should interpret such cases. It may be valuable to turn 'total_usage' from array to object with dimension type being key and 'volume' with 'step_size' being values. For example instead of 
```
"total_usage": [{
	"type": "TIME",
	"volume": "1.973"
}, {
	"type": "ENERGY",
	"volume": "15.342"
}]
```
use 
```
"total_usage": {
	"TIME": "1.973",
	"ENERGY": "15.342"
}
```

**Comment by cristinarc** [comment]
Argument: Decimals as JSON numbers is the standard for serialization libs and diverging from it means making custom serializers for which there is no reason

**Comment by finetuned89** [comment]
Even simpler:

`"total_usage": {
    "TIME": 1.973, 
    "ENERGY": 15.342
}`

**Comment by RobertdeLeeuw-IHomer** [comment]
Add comment: these are absolute values, not use the step_size

**Comment by RobertdeLeeuw-IHomer** [comment]
We agreed to add this to v2.1.
Question: The current version can add the following totals: 
ENERGY (Usefull for CDR total_usage)
FLAT (not usefull)
MAX_CURRENT (might be usefull for CDR total_usage, maximum current during the charging)
MIN_CURRENT (might not be so usefull?)
PARKING_TIME (usefull for CDR total_usage)
TIME (usefull for CDR total_usage)


So change to:
"total_usage": {
    "ENERGY": "15.342",
    "MAX_CURRENT": "7.890",
    "PARKING_TIME ": "0.173",
    "TIME": "1.973"
}

All fields optional?

**Comment by simonschllng** [comment]
I'm not quite sure if `MAX_CURRENT` and `MIN_CURRENT` are useful or not here. I mean we still have it in the periods. But the phrase _total usage of maximum current_ is so wrong. We should find a better name then.

**Comment by RobertdeLeeuw-IHomer** [comment]
True, so make it:
"total_usage": {
  "ENERGY": "15.342",
  "PARKING_TIME ": "0.173",
  "TIME": "1.973"
}

all 3 parameters optional?

**Comment by RobertdeLeeuw-IHomer** [comment]
Fixed (all my last proposal)
https://github.com/ocpi/ocpi/commit/1358b8dcf531a9c3433c6cc8d4e669e218cbc9fa

**Comment by poohsen** [comment]
fine by me
