### ISSUE TITLE
Definition of `operating_times` and `twentyfourseven`

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#71]
@RobertdeLeeuw-IHomer: If i recall it right, the commit https://github.com/ocpi/ocpi/commit/6ecd986fecd204a65cb83353962c4273ecf27c4a should be reverted, as it invalidates the example. The cardinality of `twentyfourseven` is one, but it is an either/or combination with `operating_times`. Or did we want to remove the either/or and force `twentyfourseven` to false if times are given?

**Comment by RobertdeLeeuw-IHomer** [comment]
You are right, we should revert this commit. It breaks the example!

**Comment by simonschllng** [comment]
Has this been reverted? We should check before v2.1

**Comment by RobertdeLeeuw-IHomer** [comment]
The option is remved by #144
