### ISSUE TITLE
Add Location facilities (19.)

### ISSUE THREAD

**Issue by simonphilips** [ocpi/ocpi#73]
There was some discussion about this a few months ago. It would be nice if we could add extra information about facilities at the location. Here are a few suggestions:

- Horeca
    - Hotel
    - Restaurant
    - Cafe
- Shopping:
    - Mall
    - Supermarket
    - Other store: …
- Recreation
    - Sport
    - Recreation area
    - Nature
    - Museum
- Other: …
    - Business centrum
- Mobility
   - Bike sharing
   - Bus stop
   - Taxi stand
   - Train station
   - Airport
   - Carpool parking

**Comment by simonphilips** [comment]
Additional options: toilet, wifi

**Comment by simonphilips** [comment]
Perhaps http://wiki.openstreetmap.org/wiki/Key:amenity can provide some inspiration.

**Comment by mbayings** [comment]
I should reduce it and make it optional (toilet is already part of most items mentioned, but wifi is relevant):
Horeca 
◦Hotel
◦Restaurant
◦Cafe

Shopping: 
◦Mall
◦Supermarket

Recreation / culture
◦Sport
◦Recreation area
◦Nature
◦Museum

Other
◦Bus stop
◦Taxi stand
◦Train station
◦Airport
◦Carpool parking
- Fuel Station
- Business: remote work possibility
- Wifi/internet available
- Other: FREE TEXT OF MAX 20 CHARACTERS

**Comment by simonphilips** [comment]
There are two problems with free text: 

1. it cannot be understood by machines
2. translations?

Using a fixed set of categories as enums is a lot better in my opinion.

**Comment by mbayings** [comment]
Normally I would agree, but in this case the free text is not needed to be understood. Translations are also not needed as most categories will be understood and more or less the same in many languages. 
It prevents that we must add new facilities very frequently on request of users. 
But if we do not free text, I am also fine with it. In that case I should also not add "other" as that is just as unclear as nothing at all. 
If it is up to me we don't discuss this for too long now.

**Comment by simonphilips** [comment]
I've added a proposal to extend the location objects. See pull request #75

**Comment by simonschllng** [comment]
Could we change the description from...

 > A list of available facilities at this location.

to something like...

> Facilities this charge point directly belongs to.

This could encourage the operator to only send facilities, the charge point directly belongs to as _the hotel has a charge point_ and not like _the public charge point is close to a hotel and a supermarket_.

 I'm still in doubt that those facilities are a real value-add in the long run. Items like `SPORT` and `CARPOOL` are very generic. What would be the use case? Is it: _I have to charge my car, and he, as there is some kind of **sport** at this CP, I'll prefer it over the other!_ or even _I want to do any kind of **sport**, but only if I can charge my car there._

Could you please give a use case and evaluate the enum values on base of that?

(Another possibility would be to start with a short/empty enum list and see what is really used over time. This is something in between fixed enum and free text.)

**Comment by simonphilips** [comment]
> Facilities this charge point directly belongs to.

Then I'd change that to "Facilities this charge location directly belongs to." Because it's a location property, and not an EVSE property.

There are two reasons mostly:

- Some sort of branding advertising of the owner of the charging station. This makes it easier to convince private companies to invest in 'public' charging infrastructure. Don't underestimate this part, especially not in countries that are still developing an infrastructure network.
- When a user is looking at the details of a charging location, he can quickly recognise what sort of location it is by its characteristics - even if he has just seen it on the map. So you need enough categories to get a general idea about a specific location as a memory aid without having to resort to the details.

**Comment by simonschllng** [comment]
_From face to face meeting:_

Agreement/solution:

 * We add a list of enums to the owner/branding
 * We use the list from c09b7020448cab334614684db9c4af4baefe498b

**Comment by RobertdeLeeuw-IHomer** [comment]
Added.
https://github.com/ocpi/ocpi/commit/7e8edc1e4214451d3233032fda46c4abdf8896c2
