### ISSUE TITLE
Realtime checking of Tokens (1.)

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#77]
Make it possible to do a realtime cheching of a Token.
Do we need to extend the field: allow_whitelist? Whitelist when eMSP is offline?
What should be in the request? Location object? Is allowed to charge at the location? Also the relevant Tariff objects?
Do we want it in Auth_Request or in Session?

**Comment by simonschllng** [comment]
For reference the situation in OCHP:

#### Live Authorization

 * used, when the token is not known to the operator
 * it is a _phonebook lookup_ in the clearing house
 * the clearing house generates a additional ID to reference the live
   authorization process
 * the LiveAuthID is send in the CDR to reflect this authorization
   process (reliablity reasons))

![Live Authorization](https://github.com/e-clearing-net/OCHP/raw/master/media/SingleAuthorisation-2.png)


#### Authorization via OCHP direct

OCHP direct is an addon to OCHP, which allows to have a session between
the operator and the provider. This session is used for authorization
and for information exchange.

When OCHP direct is used, the MSP can start charging sessions at the
CPO. The authorization is not explicitely part of this, as the
connection via e-clearing.net authorized the MSP **upfront** for all
requests:

1. Both roaming partners trust the clearing house
2. The operator authorises the provider to use their charging stations
   generally, by setting the roaming connection in the clearing house
3. The operator authorises and trusts the provider to authorise their
   customers at the operator's charge points generally
4. _The provider authorises their own customers at the charging
   stations of the operator for inividual charging sessions_

**This could be the same for OCPI:**

1. Both roaming partners use OCPI and are connected to each other
2. The operator authorises the provider to use their charging stations
   generally, by **exposing the module respective endpoint**
3. The operator authorises and trusts the provider to authorise their
   customers at the operator's charge points generally
4. _The provider authorises their own customers at the charging_
   _stations of the operator for inividual charging sessions_

In this new situation the operator gives the responsiblity to authorise
charging sessions away to the provider. A operator therefore should not
decline an remote authorisation for other than contractual or technical
valid reasons.

![OCHP direct](https://github.com/e-clearing-net/OCHP/raw/master/media/OCHPdirectProcess-1.png)

In the OCHP CDR, the token is stored. For OCHP direct authorized
sessions, the token is of type `remote` ant the token instance is the
OCHP direct session ID.

**In OCPI** it is to decide, if the authorization gets somehow combined
with the the session, or if it should be a complete seperate endpoint.
 * The first one makes sense as a successfull authorization will result
   in a session in either case.
 * The second one allows for more flexibility and keeps the modular
   structure.

**Comment by simonphilips** [comment]
One of the things I would like to see during the authentication exchange is something along the lines of:

1. User swipes card / eMSP initiates remote request with auth_id
2. CPO contacts eMSP with (auth_id, [available_evses/connectors])
3. eMSP verifies auth_id and returns [allowed_evses/connectors]

If step 2 sends an empty list of connectors, then it's assumed that the CPO can't distinguish between connectors.

The reason for that is the following fuel station scenario typically found at parking garages:

1. User swipes card at a central terminal
2. Terminal sends available connectors to the eMSP
3. Terminal only lets the user select one of the allowed connectors return by eMSP
4. Session starts

**Comment by simonschllng** [comment]
@simonphilips: Is the process you describe in ...
> The reason for that is the following fuel station scenario typically found at parking garages:
> 1. User swipes card at a central terminal
> 2. Terminal sends available connectors to the eMSP
> 3. Terminal only lets the user select one of the allowed connectors returned by eMSP (e.g. only AC)
> 4. Session starts

...the only use case? Are there others?

**Comment by simonschllng** [comment]
## Thoughts to the initial questions:

#### Make it possible to do a realtime cheching of a Token.

* What are the use cases? This is important to define the module. (_see below_)

#### Do we need to extend the field: allow_whitelist? Whitelist when eMSP is offline?

If the station is offline, it would fulfill the requirements for `allow_whitelist`:

> It is allowed to validate a charging session with token without requesting and authorization from the eMSP?

The extended version could be, that we have more states:

 * `no_whitelist` – every charging session has to be authorized by the MSP
 * `msp_offline_whitelist` – if the MSP does not respond or is known as offline, the charging session may be authorized from the whitelist
 * `cp_offline_whitelist` – if a station is offline, the charging session may be authorized from the whitelist
 * `provisional_whitelist` – a charging session may be authorized from whitelist but has to be authorized by the MSP within x seconds. (This speeds up the user interaction.)

**Questions:** Do we want to support those cases? Are there other necessary distinctions?

#### What should be in the request?

Location object? Is allowed to charge at the location? Also the relevant Tariff objects?

 * In the whitelist case, the operator selects the applying tarrif and authorizes the charge point.
 * The reason for the _'phonebook + authorization'_-case is, that the MSP wants to authorize. To do so, all information relevant informations have to be present.

→ The MSP needs to receive the relevant _Location_ object with the selected EVSE(s) and Connector(s), as well as the applying _Tarriff_ object(s).

#### Do we want it in Auth_Request or in Session?

It would probably work well within the session module. However, sinse OCPI is designed modular, it makes sense to define a seperate module for it. Not every party might want to use this module as some are OK with the whitelisting for now.
A separate module makes it also easier maintainable for further development.

As the successfull authorization will lead to a session, the modules should be combined. E.g. in a way, that the reply to the authorization does already contain the session ID or endpoint. This helps both partys to connect authorization events with the sessions they initialize.

→ It should be a separate module.


## Use Cases

 1. User swipes token in front of an idle charge pole. The MSP authorizes for all EVSEs of that pole.
 2. User swipes token in front of a charge pole with one EVSE available. The MSP authorizes for the specific EVSE.
 3. User swipes token in front of a charge pole or central terminal. The MSP authorizes for specific _EVSEs_ only.
 4. User swipes token in front of a charge pole or central terminal. The MSP authorizes for specific _connectors_ only.

**Questions:** Which use cases are to support? Are there other required use cases?


## Proposed Request

This is how a request could look like:

<div></div>
| Parameter     | Datatype                              | Required | Description                                          |
|---------------|---------------------------------------|----------|------------------------------------------------------|
| Token         | [Token](mod_tokens.md#31-token-object)| 1        | The token to be authorized.                          |
| Location      | [Location](mod_locations.md)          | 1        | The location at which the token is to be authorized. |
| EVSEs         | [EVSE](mod_locations.md)              | ?        | The selected EVSE(s) to be authorized at.            |
| Tarriffs      | [Tarriff](mod_tarriffs.md)            | +        | The applying tarrifs for this charging process.      |
<div></div>


**Questions:**

 * If the location has multiple EVSEs, a big number of tarrifs could apply, differently for each EVSE. Do we need to give a stronger connection between EVSE and tarriff?
 * The tarriff list could also get longer, as the authorization is in generall for infinite time. All tarriffs that could apply in the future would show up in the list. Should we limit it somehow?


## Proposed Response

This is how a response to the request could look like, if the authorization was successfull:

<div></div>
| Parameter     | Datatype                              | Required | Description                                          |
|---------------|---------------------------------------|----------|------------------------------------------------------|
| ExtraTokens   | [Token](mod_tokens.md#31-token-object)| ?        | Additional tokens which may end the charging process |
| EVSEs         | [EVSE](mod_locations.md)              | ?        | The allowed EVSES. (empty list = all)                |
| Tarriff       | [Tarriff](mod_tarriffs.md)            | ?        | The allowed tarriffs. (empty list = all)             |
| SessioID      | String(15)                            | ?        | If a session was started, it's ID.                   |
<div></div>

**Comment by simonschllng** [comment]
## Thoughts to the initial questions:

#### Make it possible to do a realtime cheching of a Token.

* What are the use cases? This is important to define the module. (_see below_)

#### Do we need to extend the field: allow_whitelist? Whitelist when eMSP is offline?

If the station is offline, it would fulfill the requirements for `allow_whitelist`:

> It is allowed to validate a charging session with token without requesting and authorization from the eMSP?

The extended version could be, that we have more states:

 * `no_whitelist` – every charging session has to be authorized by the MSP
 * `msp_offline_whitelist` – if the MSP does not respond or is known as offline, the charging session may be authorized from the whitelist
 * `cp_offline_whitelist` – if a station is offline, the charging session may be authorized from the whitelist
 * `provisional_whitelist` – a charging session may be authorized from whitelist but has to be authorized by the MSP within x seconds. (This speeds up the user interaction.)

**Questions:** Do we want to support those cases? Are there other necessary distinctions?

#### What should be in the request?

Location object? Is allowed to charge at the location? Also the relevant Tariff objects?

 * In the whitelist case, the operator selects the applying tarrif and authorizes the charge point.
 * The reason for the _'phonebook + authorization'_-case is, that the MSP wants to authorize. To do so, all information relevant informations have to be present.

→ The MSP needs to receive the relevant _Location_ object with the selected EVSE(s) and Connector(s), as well as the applying _Tarriff_ object(s).

#### Do we want it in Auth_Request or in Session?

It would probably work well within the session module. However, sinse OCPI is designed modular, it makes sense to define a seperate module for it. Not every party might want to use this module as some are OK with the whitelisting for now.
A separate module makes it also easier maintainable for further development.

As the successfull authorization will lead to a session, the modules should be combined. E.g. in a way, that the reply to the authorization does already contain the session ID or endpoint. This helps both partys to connect authorization events with the sessions they initialize.

→ It should be a separate module.


## Use Cases

 1. User swipes token in front of an idle charge pole. The MSP authorizes for all EVSEs of that pole.
 2. User swipes token in front of a charge pole with one EVSE available. The MSP authorizes for the specific EVSE.
 3. User swipes token in front of a charge pole or central terminal. The MSP authorizes for specific _EVSEs_ only.
 4. User swipes token in front of a charge pole or central terminal. The MSP authorizes for specific _connectors_ only.

**Questions:** Which use cases are to support? Are there other required use cases?


## Proposed Request

This is how a request could look like:

<div></div>
| Parameter     | Datatype                              | Required | Description                                          |
|---------------|---------------------------------------|----------|------------------------------------------------------|
| Token         | [Token](mod_tokens.md#31-token-object)| 1        | The token to be authorized.                          |
| Location      | [Location](mod_locations.md)          | 1        | The location at which the token is to be authorized. |
| EVSEs         | [EVSE](mod_locations.md)              | ?        | The selected EVSE(s) to be authorized at.            |
| Tarriffs      | [Tarriff](mod_tarriffs.md)            | +        | The applying tarrifs for this charging process.      |
<div></div>


**Questions:**

 * If the location has multiple EVSEs, a big number of tarrifs could apply, differently for each EVSE. Do we need to give a stronger connection between EVSE and tarriff?
 * The tarriff list could also get longer, as the authorization is in generall for infinite time. All tarriffs that could apply in the future would show up in the list. Should we limit it somehow?


## Proposed Response

This is how a response to the request could look like, if the authorization was successfull:

<div></div>
| Parameter     | Datatype                              | Required | Description                                          |
|---------------|---------------------------------------|----------|------------------------------------------------------|
| ExtraTokens   | [Token](mod_tokens.md#31-token-object)| ?        | Additional tokens which may end the charging process |
| EVSEs         | [EVSE](mod_locations.md)              | ?        | The allowed EVSES. (empty list = all)                |
| Tarriff       | [Tarriff](mod_tarriffs.md)            | ?        | The allowed tarriffs. (empty list = all)             |
| SessioID      | String(15)                            | ?        | If a session was started, it's ID.                   |
<div></div>

**Comment by simonschllng** [comment]
_From the face 2 face meeting_

Agreement/solution:

 * Realtime checking is added to the tokens module
 * If all tokens are on `whitelist_allowed`, the realtime checking
   implementation is not needed
 * The request goes to `POST /tokens/{id}/authorize`
 * The request contains a optional list of a `locationReference` objects
   containing location-IDs, EVSE IDs and connector-IDs
 * The result contains
   - a `AuthorizationResult` enum
   - a message to the user in one language
   - a list of `locationReference` objects
 * Add a `GET /location/evse/` endpoint to CPO

**Comment by RobertdeLeeuw-IHomer** [comment]
Busy writing realtime checking....
I will write what we discussed.

I have my doubts about the locations-IDs in the locationReference. What is the use-case for this? When would an CPO ask the eMSP to authorize a Token with a list of locations? I could think of a Mobile app asking to get a list of Locations a Token can be used, but a CPO?

**Comment by simonphilips** [comment]
How would the eMSP know the location then? For example: the eMSP might refuse sessions in a foreign country.

**Comment by RobertdeLeeuw-IHomer** [comment]
I'm only talking about a list of location, I see the use-case for 1 location including the EVSEs and Connectors in that Location. I just don't see a use case for a list of Locations.
If a EV Driver presents his RFID card at a Location, that is always at that Location, not for a list of locations.....

**Comment by RobertdeLeeuw-IHomer** [comment]
What is the expected response for the following situation:
A valid Token is used at a Location it is not allowed to charge?
Enum we thought up during the meeting: Allowed/expired/blocked/no_credit,....
I think all of these don't fit? Expired and Blocked are states of the Token..
NotAllowed?

**Comment by RobertdeLeeuw-IHomer** [comment]
Added: https://github.com/ocpi/ocpi/commit/723fce18ecc23b485e4fc7e2148ec57c68967ecd

**Comment by RobertdeLeeuw-IHomer** [comment]
sphilips: one thing I have some doubts about is this: "If an eMSP doesn't want real-time checking, the GET Authorize method doesn't have to be implemented as long as all their Tokens have Token.allow_whitelist set to TRUE. "
I understand that is what we decided, but "allow_whitelist" sounds a bit soft because it's not a "require_whitelist"
It was decided earlier that allow_whitelist still leaves the choice to do whitelist/live checking with the CPO (edited)
so if the CPO tries to do that GET, it will fail

How can we solve this?

**Comment by simonphilips** [comment]
Solution: replace by a `whitelist` enum:
- required [use this when migrating from 2.0, covers e-clearing too] 
- allowed [whatever the CPO wants]
- only when offline
- always forbidden

**Comment by RobertdeLeeuw-IHomer** [comment]
fixed: https://github.com/ocpi/ocpi/commit/4fcb27d97e5b8de57041cbed7dd42c78fe8dc4b7
