### ISSUE TITLE
Queue messages/events when the other party is off-line? (6)

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#79]
Stan J: Notify sending party immediately, then it is up to sending party to retry or not - with some text of reason.

**Comment by cristinarc** [comment]
The CPO will push to a new meta-channel endpoint about the messages that have failed to send to a party, it will be just a counter per endpoint that:
if when pushed get a successful response -> reset the counters
else keeps increasing with every message that fails.

Then the eMSP will be able to get in sync itself based on that information that will be sent. Example:
[
 {
   "num_failed": 6,
   "first_missed": "2016-02-02T10:14:04+02:00",
   "endpoint": "location"
 }
]

Then the eMSP will connect to the locations endpoint to request the _locations_ information of the locations with *last_update* filter set with the value is set in the *first_missed* field.

**Comment by cristinarc** [comment]
Robert will make a proposal

**Comment by RobertdeLeeuw-IHomer** [comment]
Added text about NOT queueing
https://github.com/ocpi/ocpi/commit/673beb0d87d5c7facd655aedb28a5160ec2632d1
