### ISSUE TITLE
Branding of Charge Point (20.)

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#83]
Add owner with fields: name, logo and websit to Location. Type: BusinessDetails

**Comment by simonphilips** [comment]
Suggested description:

### 3.1 _Location_ Object

<div></div>
| Property                                     | Type                                                     | Card. | Description                                                                            |
|----------------------------------------------|----------------------------------------------------------|-------|----------------------------------------------------------------------------------------|
| operator                                     | [BusinessDetails](#41-businessdetails-class)             | ?     | Information of the operator. When not specified, the information retrieved from the `api_info` endpoint should be used instead. |
| suboperator                                  | [BusinessDetails](#41-businessdetails-class)             | ?     | Information of the suboperator (when the operator above is working on behalf of another operator).
| owner                                  | [BusinessDetails](#41-businessdetails-class)             | ?     | Information and branding of the owner of the Location. 
<div></div>

**Comment by RobertdeLeeuw-IHomer** [comment]
Add new type: 
OwnerDetails:
- BusinessDetails: 1
- Factilities: * (type Facilities)

**Comment by simonschllng** [comment]
_from face 2 face meeting:_

Agreement/solution:

 * We add a `OwnerDetails` object, which wraps `BusinessDetails` and the
   location facilities from #73

**Comment by RobertdeLeeuw-IHomer** [comment]
Added
https://github.com/ocpi/ocpi/commit/efe16de31887a4a973286e53310676f73d33bf51
