### ISSUE TITLE
Add solution for customized versions of end-points (21.) 

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#84]
To be able to use when 'own' mondules are added.

**Comment by simonschllng** [comment]
_from face 2 face:_

Agreement/solution:

 * Custom endpoint identifiers have to start with a dash (-)
 * The version endpoint should only send out endpoint information of
   custom endpoints to parties which whom those were defined.
 * This will be added as description about customization, no changes to
   the protocol needed.

**Comment by RobertdeLeeuw-IHomer** [comment]
prefix your custom modules - and add more then just the original module id.
