### ISSUE TITLE
Add a changelog (0.)

### ISSUE THREAD

**Issue by cristinarc** [ocpi/ocpi#85]
Should it be at protocol level or document level?
- Initial idea: I would propose that it wil only contain the changes in messages., added messages, removed fields etc.
So only on protocol release. between document releases the messages/datatypes etc should not change. It is there to help developers on what they should change in there implementation.

- Argument: change log is interesting on both scenarios, since the developer could have made a mistake based on the mistake of the specs, therefore it would be nice that the developer is able to go exactly where these corrections have being done

**Comment by simonschllng** [comment]
_From the f2f meeting_

What has to be part of it:

 * Only changes on protocol level
 * Impact assesment for breaking changes
 * One changelog file per version change

**Comment by RobertdeLeeuw-IHomer** [comment]
Changelog now part of documentation. 
Worjk in progress...
https://github.com/ocpi/ocpi/blob/master/changelog.md
