### ISSUE TITLE
add "updated_since" parameter to all GET requests

### ISSUE THREAD

**Issue by poohsen** [ocpi/ocpi#87]
the usecases I can think of for executing a GET for all modules are:

1) your service was down/offline, for instance due to a deployment, and you want execute a GET to retrieve all data you might have missed
2) you want to periodically execute a GET to guard against missing messages due to connection problems that you were not aware of
3) you initiate communications with a new party and want to retrieve all available data

In the first two cases, you are only interested in a subset of the data. You want the delta since your last GET request. There is no need to retrieve all available data sets if only a subset changed.

Therefore, a (maybe optional) `updated_since` parameter would be handy for all GET requests.
The same is being done in OCHP 1.2 for charge tokens and chargepoints. There, the parameter is called `lastUpdate`, which would also be an option.

**Comment by simonphilips** [comment]
Should this same parameter also be included as a field in each object?

**Comment by poohsen** [comment]
I don't mind if we do.

**Comment by simonphilips** [comment]
Parameter will be `last_updated` and is added to both the GET request and a field of the object on which the GET request applies.

**Comment by RobertdeLeeuw-IHomer** [comment]
quick question: CDRs allready have a filter based on the created start of charging.
I think it is better to also add last_updated to the CDRs and change, for 2.1 the filter of CDR also to last_updated.
