### ISSUE TITLE
discuss the need for separating the party_id in OCPI into an msp_party_id and a cpo_party_id

### ISSUE THREAD

**Issue by poohsen** [ocpi/ocpi#88]
it seems that one and the same party can have two different IDs in the same country depending on whether it's acting as a CPO or an MSP. We need to discuss whether and how to address this fact in OCPI

**Comment by simonphilips** [comment]
Isn't this already addressed? Let's suppose you have two companies that act both as CPO and eMSP. Then they will have to set up two OCPI connections (so two OCPI registrations). Send a different party_id for the CPO registration and for the eMSP registration. How you store those different party_id's is internal kitchen of your OCPI implementation I'd say, no?

**Comment by simonschllng** [comment]
This means, that TNM, who is active in at least 5 different countries as CPO and MSP, has to establish 10 connections to a partner active in one country, 20 for one active in two, 100 for a partner active in 5 countries...

**Comment by simonphilips** [comment]
I've never understood why party_id and country_code is needed though. I just store it and do absolutely nothing with it.

**Comment by poohsen** [comment]
@simonphilips my interpretation of OCPI 2.0 is that 
1) you only know the correct value for the country_code and party_id when you receive them in the credentials object.
2) you want to prevent NL-TNM from accessing parts of your locations API that are not qualified by NL/TNM

I understand that your access authorization is based solely on the authorization token. So if we as TNM access NL/GFX locations, we will get a 401 or sth. because in your system, the party identified by our token does not own any of the GFX locations, and not because of what the URL looks like, correct?

I think this implementation makes sense. 
But I also think that the URL scheme with `.../country_code/party_id/...` also makes sense from an API design POV. And from that scheme follows that you want to forbid access to other country_code/party_id combinations, which you can only do if you have the country_code and party_id of the API user. Which takes us back to point 1) above

**Comment by simonphilips** [comment]
Indeed. If someone bases access permissions on this URL scheme, then I think they have a flawed implementation.

The API design point is a good one as id's are only unique per 'owner' (CPO for locations, eMSP for tokens). With the simplistic URL scheme the `/emsp/2.0/locations/1` url for operator A would point to a different object than the `/emsp/2.0/locations/1` url for operator B which is a bit odd indeed.

However, that means it's already been taken care of and @simonschllng 's point is not really valid because this has nothing to do with the country code/party id of the location or token. It's the country code of where the roaming partner's headquarters are located so if the roaming partner operates in 10 countries, there is still only 1 country code.

As I understand, the entire reason for the `/country_code/party_id/` scheme is that "party_id" is only unique within one country because each country has a different identification system (if they even have any). So `TNM` might be the Dutch party_id for *The New Motion* and it might be the US party_id for *The Next Moped*. To solve this conflict, the country code is added. At least that's how I interpreted it.

**Comment by simonschllng** [comment]
About the usage if IDs and if one company should have only one (headquarters) or multiple (active countries):

 * Current implementations, also in e-clearing.net, are, that you have one ID per role and per country you are active in.
 * There is still no official "standardized way" of implementing it. However, part 2 of the eMI3 "standard" gives a first proposal:
   * eMI³ requires the EVSE-ID of a charge point to reflect the country code to _"represent the country where the EVSE is installed"_. They also say, _"An operator can apply to get the same Spot Operator Id in every country they are operating in."_
   * For the provider an the eMA-ID, the definition is similar: "_**1.4.1.2 Issuing of Global Service Provider-IDs** The country code of eMAID refers to the country where the contract between customer and EVSP has been made. Any EVSP shall be registered by the local issuing authority for every country he will perform charging service. Hence, “Country code” + “Service Provider Id” is a unique information referring to an Provider operating charging services in a specific country._"
 * A working group in the DG Move of the STF (Sustainable Transport Forum) is going to harmonize it and will issue it until end of the year. ( @mbayings, you're known to be involved here? )

**Comment by poohsen** [comment]
@simonschllng good to know the eMI3 has this definition of the country code. 
@RobertdeLeeuw-IHomer this runs counter to your interpretation so far, I believe.
@simonphilips:
>  If someone bases access permissions on this URL scheme, then I think they have a flawed implementation.
we currently use _both_, the token and the URL. How does your implementation prevent TNM from sending a PUT with a _new_ location to NL/GFX ?

**Comment by simonphilips** [comment]
@poohsen: I do raise a 403 when TNM puts something to `NL/GFX/newLocId` but if I removed those 3 lines of code then TNM could send a PUT to `US/Tesla/newLocId` for all I care and I would still register the object with newLocId to TNM (because I know it's you from your auth token, I ignore the URL entirely). 

So my check is just really 3 lines of eye candy to follow the spec but nothing more. It would still work correctly without.

**Comment by poohsen** [comment]
@simonphilips so, even if it _is_ only 3 lines, can we conclude that we do need to distinguish CPOs from MSPs here to make those 3 lines do the right thing?

**Comment by simonphilips** [comment]
After some talking to Max from E-Clearing, it seems that this issue can go away entirely if we clarify that country_code/party_id are defined in function of the company that has set up the OCPI connection (typically the clearing house or the main CPO/EMSP in the case of P2P) 

- E-Clearing can then use the /DE/ECN/ URL infix regardless of the suboperator and subprovider.
- Suboperator and subprovider information should go in the location/token objects respectively. These are the fields that actually identify them.
- Every party needs to set up maximum 1 eMSP and 1 CPO connection with E-Clearing
- All of the above already works in OCPI 2.0 and nobody needs to change anything

So we do ... nothing and everybody's happy!

**Comment by mbayings** [comment]
I can't oversee if this will indeed work. Thought that e-Clearing also had problems with the suboperator field. But if we al agree that this way it is solved or a non-issue, I am happy. But it sounds good.

**Comment by simonschllng** [comment]
After all those discussions I vote for the following:

 * Completely remove all country codes and party id's from the protocol. They do only confuse us.
 * Extend the location and EVSE id to string 48 to be able to use a emi 3 EVSE ID here if wanted.
 * Write a clear text about how uniqueness of objects on the server side is obtained. (Simon Phillips' approach). Write that one needs one connection per role to each party.
 * Optionally change the cardinality of the party id's in the credentials object to "+" (array). It is standard in e-clearing, Hubject, eMI3 that a company has a operator and provider id per country. We should reflect that.

Do all this in 2.1 to end the discussion.

Wish to see all this solved soon.

**Comment by mtdern** [comment]
I fully support all of Simons suggestions. All of them would help us a lot in making a platform implementation.

**Comment by RobertdeLeeuw-IHomer** [comment]
After a discussion during the Strasbourg meeting, it was decided to add party_id and country_code to all objects, which is really the other way around from this issue.
OCPI 2.2 now support platforms, allowing 1 platform to host multiple services for even different roles. So only 1 OCPI connection is needed. Does that solve this issue?
