### ISSUE TITLE
Recommend to use EVSE-ID

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#89]
To be compatible with roaming platforms, we should recommend to use the eMI3 EVSE-ID syntax within the location object.

**Comment by RobertdeLeeuw-IHomer** [comment]
Ss the definition of eMI3 EVSE-ID different from 15118? The specification now states: Compliant with ISO/IEC 15118-2 - Annex H "Specification of Identifiers". 

I always understood that they should be the same.

If everybody agrees, we can change this.

**Comment by simonschllng** [comment]
They should but are not. There are fundamental differences. (unfortunately)

**Comment by RobertdeLeeuw-IHomer** [comment]
My opinion: We should follow the official standards as much as possible. If IEC/ISO has a standard, we should use that. eMI3 is good and all, but it is not part of an recognized standardization body. 

But again, that is just my own personal opinion. If the majority agrees that we should follow eMI3 that we should do that.

**Comment by rutgerplantenga** [comment]
Might be good to double-check that with Michel as he is quite deep into
these standards.


Met vriendelijke groet / Kind regards,

Rutger Plantenga

*International business development*+31 6 2907 6069

[image: The New Motion]
www.thenewmotion.com | +31 88 010 9500
[image: facebook] <https://www.facebook.com/thenewmotion> [image: twitter]
<https://twitter.com/thenewmotionnl> [image: linkedin]
<https://www.linkedin.com/company/the-new-motion> [image: download our app]
 app <https://www.thenewmotion.com/producten/new-motion-app/> [image:
subscribe to our newsletter] newsletter
<http://thenewmotion.us7.list-manage2.com/subscribe?u=69f8e1377308b97f478467ff1&id=f36f3eebc8>
[image: NL] Keizersgracht 585, 1017 DR Amsterdam
[image: DE] Tempelhofer Ufer 17, 10963 Berlin
[image: FR] 15 Avenue du Centre, 78280 Guyancourt

**Comment by mbayings** [comment]
Currently in a meeting, so a short reply for now.
True that ISO is an official standardization body. EMI3 is also an official organization focussed on interoperability but not as standardization org. 

EMI3 defined the format for IDs. This was taken over in ISO 15118. However ISO did not implement all agreements how to use it.

EMI3 members include most roaming organizations. They all use the eMI3 definition of IDs. It is the same as the ISO one but with a few more agreements how to use /implement it. And the eMI3 definition is free available. Where the ISO standard need to be bought. 

So it should be compatible with each other. Using the eMI3 code just give more info.

I can send details of the differences later if required. 

In any case I suggest to use the eMI3 definition.

**Comment by simonschllng** [comment]
I got fedback from the 15118 developers. The eMAID syntax is specified in _ISO15118-2 Annex H_, to where we could link/reference. However, there are known problems which will be corrected in the next release of 15118. The problem is the inconsistency with eMI3:

    ISO 15118-2:
    <EMAID>  = <Country Code> <S> <Provider ID> <S> <eMA Instance> <S> <Check Digit>
    eMI3 standard:
    <eMA ID> = <Country Code> <S> <Provider ID> <S> <ID Type> <eMA Instance> <S> <Check Digit>

Note the missing `<ID Type>` in 15118. This will be added in the next release by aligning with eMI3.

We could reference the more official ISO 15118 standard with a hint, that the _corrected_ version is to be used. **Note:** This is only the eMA-ID, not the EVSE-ID, which is not part of 15118.

**Comment by mbayings** [comment]
This is very good news! Will solve a lot of discussion about the difference. I am fine by adding this to the specs. And also mention clearly that the EVSE-ID is not part of 15118, as it prevents people searching for it in a place where it is not mentioned anyway.

**Comment by RobertdeLeeuw-IHomer** [comment]
fixed
