### ISSUE TITLE
Feature request: add language field to Token objects

### ISSUE THREAD

**Issue by simonphilips** [ocpi/ocpi#91]
Context: [Token object](https://github.com/ocpi/ocpi/blob/master/mod_tokens.md#31-token-object)

Use-case: a CPO may want to show interface messages on a charging device or a terminal. When a user swipes his RFID card, the system doesn't know the user's preferred language.

Proposed solution: add the following field to the Token object:

| Property                | Type                                  | Card. | Description                                                                                             |
|-------------------------|---------------------------------------|-------|---------------------------------------------------------------------------------------------------------|
| language                    | [string](types.md#16-string-type)(2) | ?     | Language Code ISO 639-1. This field indicates the user's interface language. If the language is not provided or not supported then the CPO is free to choose its own language. |

**Comment by RobertdeLeeuw-IHomer** [comment]
I agree. 

It is an easy fix, could be added to 2.1, if we can decide on this in the coming days.

**Comment by RobertdeLeeuw-IHomer** [comment]
added: https://github.com/ocpi/ocpi/commit/da71618d3732333f65d74db05341fdd6b98d104f
