### ISSUE TITLE
Discuss: addition of recipient-identification

### ISSUE THREAD

**Issue by mtdern** [ocpi/ocpi#92]
While putting together the specification for the eCHS [e-clearing.net] OCPI interface, Harm and I came up with a possible solution for adding EMP-specific tariffs to OCHP. In our view, this is essential to enable using the OCPI advantage of EMP specific tariffs with non-OCPI eCHS partners. The same goes for OCPI partners that wish to connect through eCHS only (not P2P).

To be able to deal with the platform having to distinguish between tariffs and their recipients, it is essential to have the actual desired recipient (or multiple) recipients added to the tariff object itself. Otherwise, if a tariff object comes in from a CPO to the eCHS platform via OCPI, we currently cannot know who the desired recipient is for that specific tariff (since we only have one connection between a CPO and the eCHS and not one connection for each EMP that is represented by eCHS). As it is now, the eCHS could potentially receive multiple tariffs of ID “T1” (for example), because it represents multiple EMPs, each of which has their individual tariff “T1”.
Our solution would add a “recipient” field/element to the tariff object, thus enabling eCHS to distinguish between multiple tariffs of the same ID for individual EMPs and forwarding only the correct tariff to the correct recipient.

_From Rutger:_
I cannot really judge on the suggested technical solution but conceptually, doesn't the same problem exist elsewhere? I.e. isn't there a broader need to identify the targeted recipient when exchanging data via OCPI with partners 'behind' the platform? 

For instance, I can imagine that this might also apply to CDR-exchange. 

If this is indeed the case, shouldn't we aim for a more generic solution, instead of specifically adding it to Tariffs?

Rutger

_From me:_
The CDR-exchange does not exhibit this problem, as it contains the _auth_id_, which should contain a valid eMA-ID that in turn uniquely identifies the EMSP the CDR is addressed to.

A more generic solution is, from our side, an even better solution of course.

**Comment by mbayings** [comment]
I looked at it and as far as I can judge it, the Tariff object is not the right place for it. I agree with Rutger that this is more a general issue that can happen in more situations. Or the other way we should add it everywhere and make it optional, in a kind of situation like: [if connection not P2P, then indicate recipient] where Recipient can either be a specific party or everyone. Or something like that. Then we can keep OCPI as it is but with additional contstraints when connecting to a central roaming system. Think it would also be good to check how this is with Gireve, and maybe Hubject, that if we define something it is usable for more central systems.

**Comment by mtdern** [comment]
Agreed, the tariff object itself is not the right place, it is simply the only place where we encountered the issue - that's why we originally wanted to place it there.
Adding it everywhere and making it an optional field seems like a far more pragmatic solution. It has to be very clear to all parties in this case that they need to make use of this if they wish to go through a platform. The distinction between specific recipients and "everyone" is also a very nice solution to have in case a party does not distinguish between recipients or sends out data that is the same for each partner (e.g. tokens).

**Comment by mtdern** [comment]
Use custom HTTP-Header specifying one or multiple recipients. To be specified further.
