### ISSUE TITLE
How to handle duplicate commands

### ISSUE THREAD

**Issue by simonschllng** [ocpi/ocpi#95]
In the [commands module](https://github.com/ocpi/ocpi/blob/master/mod_commands.md), how do you reply to a duplicate command. E.g. when a provider sends a `START_SESSION` command for a charge point that already has a running session.

**Comment by simonphilips** [comment]
There are two options:

1. The error is detected when the eMSP sends the command to the CPO: the CPO responds with an error status code. The response is synchronous so the duplicate command is not an issue here.
2. The error is detected at the charging point, the CPO sends a CommandResponse to the response_url provided in the request by the eMSP. If the eMSP is smart, it should make the response_url something like `/emsp/commands/response/{commandId}` which solves the duplicate command issue (as they'll have 2 different id's)

**Comment by simonschllng** [comment]
@mtdern, this will be explained/solved in #99
