### ISSUE TITLE
Extending `evse_uid` to string(48) match EVSE-IDs

### ISSUE THREAD

**Issue by simonphilips** [ocpi/ocpi#97]
To be able to use the protocol via a roaming platform, the `evse_uid`
should be the EVSE-ID as specified by eMI3. Therefore it has to be able
to contain a 48 character string.

See https://github.com/ocpi/ocpi/commit/57ab946b13bbd70c8b335c6cbd9ed10801bab70d

Due to some confusion about it, the commit from the pull request was reverted. Let's have a proper talk about it here before adding it. It might not make the 2.1 release however.

**Comment by RobertdeLeeuw-IHomer** [comment]
The field: EVSE.uid was introduced, pre OCPI 2.0 when Location and EVSE were still to list. It was needed to enable reuse of an EVSE_ID. With the changes done afterwards, moving EVSEs into the  Locations object, this field might not be needed anymore. Then the eMI3 compliant EVSE-ID could/must be used everywere.

**Comment by RobertdeLeeuw-IHomer** [comment]
@simonphilips I checked the eMI3 documentation: http://emi3group.com/documents-links/
I get 38 chars max

CountryCode: 2
Separator: 1
SpotOperator: 3
Separator: 1
IDType: 1
PowerOutletId: 30

Or did I miss anything? Do you have a different definition?

**Comment by simonphilips** [comment]
@RobertdeLeeuw-IHomer 

I honestly can't remember as this issue is so old. It wouldn't surprise me if I somehow managed to turn 38 into 48. The original size was 15 in the commit.

**Comment by RobertdeLeeuw-IHomer** [comment]
Yes, it used to be 15, it has been increased to 39 in 2.1.1
